- Makefile
- Added build-dpi target in Make to compile DPI C-code using gcc
- Updated the vsim commands in the Makefile to include the newly
generated DPI library
- Updated the vsim command with the "-64" switch as we are always
using this switch with vlog
> Fix for #10

- Makefile
- Updated simc target to automatically run the test by adding
run -a in the do command
> Fixes for #16

- README.md
- Added a new section in README about compiling custom C-code
> README update for #21

- src/mult.sv
- Added flush_i port to mult/div module
- Both result and valid are de-asserted when flush_i is high
> :bug: Fixes #26

- include/ariane_pkg.sv
- src/scoreboard.sv
> Fix FP forwarding and missing FP loads/stores

- Makefile
- include/ariane_pkg.sv
- include/riscv_pkg.sv
- src/ariane.sv
- src/cache_subsystem/miss_handler.sv
- src/csr_regfile.sv
- src/frontend/bht.sv
- src/frontend/btb.sv
- src/frontend/frontend.sv
- src/frontend/instr_scan.sv
- src/issue_read_operands.sv
- src/util/instruction_trace_item.svh
Fixes an issue with inactive branch prediction table. Slightly improves IPC.
> :racehorse: Fix #57

- src/ariane.sv
- src/branch_unit.sv
- src/csr_regfile.sv
- src/issue_stage.sv
- src/scoreboard.sv
This commit fixes an issue with single-stepping in debug mode.
> :bug: Fix #99

- fpga/src/bootrom/README.md
Use up-to-date make targets on the ariane-sdk
> Update the SD card howto

- fpga/src/bootrom/src/sd.c
> Bugfix in FPGA bootrom

- CHANGELOG.md
- src/cache_subsystem/wt_cache_subsystem.sv
This is a hotfix for the OpenPiton cache system.
> Ariane 4.1.1 release

- CHANGELOG.md
This adds the correct license headers to the FPU files
> Fix license headers of FPU files (fix #202)

- include/ariane_pkg.sv
- include/riscv_pkg.sv
- src/ariane.sv
- src/commit_stage.sv
- src/csr_regfile.sv
- src/decoder.sv
- src/ex_stage.sv
- src/id_stage.sv
- src/util/exception_trace_item.svh
Patches to make the interrupt subsystem work properly.
> Re-work `irq_subsystem` and `debug_req` to make PLIC behavior more stable

- CHANGELOG.md
- include/ariane_pkg.sv
- src/ariane.sv
- src/ex_stage.sv
- src/issue_read_operands.sv
- src/load_store_unit.sv
- src/mmu.sv
Check for execute permission and do not blindly issue the read to the SoC. This should fix the hang-ups we've experienced in OpenPiton before.
> Execute PMA

- include/riscv_pkg.sv
- src/commit_stage.sv
- src/csr_regfile.sv
@jrrk May I propose the following fix?
> Set `sd` bit

- include/ariane_pkg.sv
- src/frontend/frontend.sv
- src/frontend/instr_queue.sv
- src/instr_realign.sv
Test the code with 32 bit and 64 bit fetch width.
> Generalize the realign module to enable arbitrary fetch width

- src/commit_stage.sv
This section seems to be a duplicate of the section right before (lines `174-207`)
> remove code duplicate

- src/frontend/bht.sv
- src/frontend/frontend.sv
- src/frontend/instr_queue.sv
A minor bug in BHT was found when I implemented multi-issue feature.
> Fix a minor bug in BHT

- include/ariane_pkg.sv
- src/ariane.sv
- src/ex_stage.sv
- src/frontend/bht.sv
- src/frontend/frontend.sv
- src/frontend/instr_queue.sv
- src/id_stage.sv
- src/issue_read_operands.sv
- src/issue_stage.sv
- src/re_name.sv
- src/scoreboard.sv
- tb/ariane_soc_pkg.sv
This PR is to fix #121 
1. Modify the interfaces of different modules to support multi-issue
2. Add second ALU unit
3. Add another FLU write back port. OneFLU is for one ALU and one multiplier. The other one is used by the other ALU, one csr and the branch unit.
4. Fix bugs on bht when multi-issue is enabled
5. re-name is not supported when multi-issue (will fix it soon)
Benchmarks are run to test about the speed up.
Performance and resource usage :
> Enable multi issue 

- fpga/scripts/run.tcl
Hi, All
I make this PR for #333
> Fix empty match file in FPGA flow

- src/commit_stage.sv
Or should the code block above be removed instead?
> commit_stage.sv: remove redundant code block

- Flist.ariane
(cherry picked from commit 71627a3729abda6ed04038dfd387dba6357ff9d9)
> Packages shall be compiled before referencing their items. 

- src/ariane.sv
- src/commit_stage.sv
- src/issue_read_operands.sv
- src/issue_stage.sv
I'm trying to support `NR_COMMIT_PORTS == 1` mode and here are some pieces of patches. However, this is certainly incomplete and need some revision. @zarubaf
> Support NR_COMMIT_PORTS == 1

- src/frontend/frontend.sv
Signed-off-by: Massimiliano Giacometti <massimiliano.giacometti@hensoldt-cyber.com>
related to https://github.com/openhwgroup/cva6/issues/319
> bp_valid = 0 if ras_predict.valid = 0

- README.md
Update the image paths in README
> README.md: update image paths

- src/pmp/src/pmp_entry.sv
Signed-off-by: Emeric Poulin <emeric.poulin@thalesgroup.com>
> fix issue 506

- include/axi_intf.sv
Fix artifact from recent change from global to local imports
> axi_intf.sv: import axi_pkg in AXI_LITE interface

- include/ariane_pkg.sv
- src/cache_subsystem/wt_icache.sv
- src/frontend/frontend.sv
Signed-off-by: Marcelo Orenes <movera@princeton.edu>
> wt_icache: Fix for speculative accesses to NI address range

- src/load_unit.sv
When we receive a d-cache reply and an exception from the MMU in the same cycle, we need to check whether both belong to the same lsu request before forwarding the exception. This is the case iff `state_q == SEND_TAG`, since this is when we receive the translation result (i.e. physical tag / MMU exception) for the current in-flight d-cache request.
Otherwise, the exception belongs to the next request that is already being translated (e.g. `state_q == WAIT_GNT`). In this case of a collision, prioritize and return the valid load, discard the MMU exception, and go for another round in the load FSM.
Test bench passes and works on FPGA.
> load_unit: fix exception forwarding

- tb/ariane_tb.sv
Fix for #596 - forgot to update the path for Questasim.
> ariane_tb: Adjust path in testbench (fixes #596)

- src/clint/clint.sv
- src/frontend/frontend.sv
- src/scoreboard.sv
More verific detected misuses of $fatal.
> fix  syntax errors detected by verific.

- include/ariane_pkg.sv
Signed-off-by: Emeric Poulin <emeric.poulin@thalesgroup.com>
> Index width adaptation to cache size and associativity

- Flist.ariane
- openpiton/ariane_verilog_wrap.sv
Signed-off-by: Tianrui Wei <tianrui-wei@outlook.com>
> [fix] fix openpiton simulation flist with HEAD

- openpiton/ariane_verilog_wrap.sv
- src/ariane.sv
- src/csr_regfile.sv
- src/util/instr_tracer.sv
Signed-off-by: Emeric Poulin <emeric.poulin@thalesgroup.com>
> Fix warning messages when using 32 bits version

- src/alu.sv
this is a correction SRL instruction in CVA6
> correcting SRL instruction in 32b

- src/re_name.sv
Fixes #692 - thanks for pointing to it.
> Update re-namer license

- fpga/Makefile
- fpga/scripts/run.tcl
- fpga/src/ariane_xilinx.sv
- fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/Makefile
- fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/tcl/run.tcl
- fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/Makefile
- fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/tcl/run.tcl
- src/axi_adapter.sv
Hi,
cv32a6 tested on genesys 2 board via baremetal application
cv64a6 tested on genesys 2 with baremetal application and linux running.
> Cv32a6 genesys

- core/csr_regfile.sv
> Fix PMPCFG csr read for 32bit configuration

- README.md
Hi @JeanRochCoulon, this is a very simple pull-request just to test your new powers as a CORE-V Committer.
Signed-off-by: Mike Thompson <mike@openhwgroup.org>
> Clarify scope of Verilator model

- core/decoder.sv
> decoder.sv: remove unnecessary assignment

- .gitmodules
- Bender.yml
- CHANGELOG.md
- Makefile
- core/include/axi_intf.sv
- corev_apu/fpga/scripts/run.tcl
- corev_apu/fpga/src/ariane_xilinx.sv
- corev_apu/tb/ariane_testharness.sv
- Bump `common_cells` to `v1.23.0`
- Bump `axi` to `v0.31.0`
- Remove `axi_node` dependency, replace with `axi_xbar` from `axi` repository
- Slightly bump `register_interface` for `axi` compatibility
> AXI and common_cells upgrade

- core/Flist.cv32a6_imac_sv0
- core/Flist.cv32a6_imac_sv32
- core/Flist.cv32a6_imafc_sv32
- core/Flist.cv64a6_imafdc_sv39
Hello, 
Just a minor fix.
A file was missing in the Flists used by core-v-verif repository.
> Fix flists after commit #791

- core/serdiv.sv
Signed-off-by: Florian Zaruba <florian@openhwgroup.org>
> Fix erroneous division (fixes #421)

- Makefile
> Makefile: add missing incdir for VCS (fix #791)

- core/csr_regfile.sv
> csr: Fix wrong activation vectored mode

- .gitlab-ci.yml
- .gitlab-ci/core-v-verif-cva6.yml
Update for gitlab CI, add new features, fix limitations and optimize resources via new workflow.
Related to  PR : [Update Gitlab CI: new workflow, new jobs, code optimization #1223 ](https://github.com/openhwgroup/core-v-verif/pull/1223)
> Update Gitlab CI: new workflow, new jobs, code optimization

- core/axi_adapter.sv
When a store-conditional fails due to a missing reservation, by specification it must return a non-zero value. In addition, the non-zero value must be a 1, other non-zero values being reserved. Previously a value of `64'b1` was returned by the `axi_adapter`. However, when an atop's address is non-64bit-aligned, the return data has to be realigned. This realignment causes the lower half-word being lost, and the return datum taking a value of `'0`.
This commit fixes the bug by returning 1 from the `axi_adapter` when the request is 64-bit and placing a 1 in both upper and lower halfwords when the request is 32-bit. Externally, the correct halfword is realigned/masked thus returning a value of 1 in all cases. Unfortunately, this requires registering the `size` of the request.
> :bug: wb_dcache: Fix unaligned SC return data bug

- core/cache_subsystem/wt_axi_adapter.sv
- core/cache_subsystem/wt_dcache.sv
- core/cache_subsystem/wt_dcache_ctrl.sv
- core/cache_subsystem/wt_dcache_mem.sv
- core/cache_subsystem/wt_dcache_missunit.sv
- core/cache_subsystem/wt_dcache_wbuffer.sv
- core/include/ariane_pkg.sv
- core/include/riscv_pkg.sv
- core/include/wt_cache_pkg.sv
- core/load_store_unit.sv
- core/load_unit.sv
- core/mmu_sv32/cva6_ptw_sv32.sv
- core/store_buffer.sv
- core/store_unit.sv
This is wt dcache adaptation in 32b, it hasn't been done yet.
That allows to reduce the amount logic resources.
It has been tested on Linux in 32b and 64b version.
> Dev dcache 32bits

- ci/setup.sh
- common/local/util/sram.sv
- core/axi_shim.sv
- core/cache_subsystem/cva6_icache.sv
- core/cache_subsystem/cva6_icache_axi_wrapper.sv
- core/cache_subsystem/std_nbdcache.sv
- core/cache_subsystem/wt_axi_adapter.sv
- core/cache_subsystem/wt_dcache.sv
- core/cache_subsystem/wt_dcache_ctrl.sv
- core/cache_subsystem/wt_dcache_mem.sv
- core/cache_subsystem/wt_dcache_missunit.sv
- core/cache_subsystem/wt_dcache_wbuffer.sv
- core/include/ariane_axi_pkg.sv
- core/include/ariane_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/wt_cache_pkg.sv
- corev_apu/fpga/src/ariane_xilinx.sv
- corev_apu/tb/ariane_axi_soc_pkg.sv
- corev_apu/tb/ariane_tb.cpp
- corev_apu/tb/ariane_tb.sv
- corev_apu/tb/ariane_testharness.sv
2 commits: 
- fix the "dev dcache 32bits" commit: fix one assert activated when VCS is used. @sjthales, could you approve the fix ?
- Add user bits between memories and caches @Gchauvon
> Add user field between memory and caches

- .gitlab-ci.yml
gitlab-ci: minor update in prevision of Dashboard flow through core-v-verif repository
> Update gitlab-ci: add variables for dashboard generation

- corev_apu/tb/ariane_tb.cpp
- corev_apu/tb/ariane_tb.sv
- pd/synth/cva6_synth.tcl
@JeanRochCoulon
Fix some ram paths which were not updated with the tc_srams PR.
> Fix tc_srams paths

- .gitlab-ci.yml
Update workflow to merge regex and add entry for gitlab-pr* branch name
> gitlab-ci: add workflow for github pull request

- .gitlab-ci.yml
Gitlab-ci: Add way to disable workflow policy
> Gitlab-ci: Add way to disable workflow policy

- .github/ISSUE_TEMPLATE/bug.yaml
This template provides an automatic title and label for bug issues.
> Adding a Bug issue template 

- core/cva6.sv
- core/include/ariane_rvfi_pkg.sv
- corev_apu/tb/rvfi_pkg.sv
- corev_apu/tb/rvfi_tracer.sv
> Add cause field in RVFI

- docs/design_spec/source/cva6_axi.rst
- docs/design_spec/source/cva6_intro.rst
- docs/design_spec/source/index.rst
Signed-off-by: Alae Eddine Ez zejjari <alae-eddine.ez-zejjari@external.thalesgroup.com>
> Add AXI specification chapter

- docs/design_spec/source/cva6_intro.rst
- docs/design_spec/source/cva6_isa.rst
- docs/design_spec/source/index.rst
Signed-off-by: Ayoub Jalali <ayoub.jalali@external.thalesgroup.com>
> ISA Specification for cva6

- core/Flist.cva6
- core/ariane_regfile_fpga.sv
- core/issue_read_operands.sv
Regfile optimized for FPGA target
> Regfile fpga

- docs/03_cv32a6_design/source/cv32a6_isa.rst
Signed-off-by: Ayoub Jalali <ayoub.jalali@external.thalesgroup.com>
> ISA spec : Update ISA specification

- README.md
> README.md: core only simulation done via core-v-verif (fix #977)

- core/include/ariane_pkg.sv
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
- core/load_store_unit.sv
Signed-off-by: sjthales <sebastien.jacq@thalesgroup.com>
> added TLB entries configuration

- config_pkg_generator.py
- core/frontend/frontend.sv
- core/include/ariane_pkg.sv
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
> Move ariane_cfg_t definition from ariane_pkg to in cva6_config_pkg

- core/include/ariane_pkg.sv
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
- corev_apu/tb/ariane_soc_pkg.sv
Signed-off-by: sjthales <sebastien.jacq@thalesgroup.com>
> added PMP configuration

- config_pkg_generator.py
To keep it up to date with #1052
> config generator manages TLB

- docs/01_cva6_user/CVX_Interface_Coprocessor.rst
- docs/01_cva6_user/Interfaces.rst
- docs/01_cva6_user/Parameters_Configuration.rst
- docs/01_cva6_user/index.rst
According to https://docs.google.com/document/d/1W3gBZPk0tNWquXo5CkcLWU07CdxaaT0gzsnhQ_dpiIo, Interfaces is a different file.
> [skip ci] Interfaces in a different file

- CONTRIBUTING.md
Guidelines for upcoming contributions to the CVA6 project.
> [skip ci] Update contributing guidelines

- docs/01_cva6_user/Introduction.rst
First attempt to make a complete introduction for the users' guide. The use of ReST features is surely not yet optimal.
> [Skip CI] Users' guide / Introduction

- core/cva6.sv
- core/include/ariane_pkg.sv
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
Added a parameter to generate performance counters
> Perf counter optional 0

- core/Flist.cva6
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/mmu_sv32/cva6_mmu_sv32.sv
- core/mmu_sv32/cva6_ptw_sv32.sv
- core/mmu_sv32/cva6_shared_tlb_sv32.sv
Level 2 shared TLB N-way associative , it allows to reduce the number of ITLB and DTLB entries without degrading processor performance.
> added shared TLB

- .github/workflows/ci.yml
Increase CI parallelism and simplify `ci.yml`
> ci: Combine tests in matrix

- core/controller.sv
- core/cva6.sv
- core/include/ariane_pkg.sv
QuestSim requires to explicitly cast to integer an enumeration variable when comparing against an integer constant.
> Fix enum value comparison: it needs explicit cast to int

- core/alu.sv
- core/branch_unit.sv
- core/ex_stage.sv
- core/fpu_wrap.sv
- core/include/ariane_pkg.sv
- core/issue_read_operands.sv
- core/load_store_unit.sv
- core/load_unit.sv
- core/mult.sv
- core/multiplier.sv
- core/store_unit.sv
Thanks you @umerimran-10xe for the  #1150  github issue report, PR is submitted to fix it
Can you approve it ?
> Replace operator by operatr to avoid C++ keyword names in the SV Code.

- .github/workflows/dashboard-done.yml
This PR is the same as https://github.com/openhwgroup/core-v-verif/pull/1810 but only the GitHub-side part is needed for this repository.
> ci: accept notification from Dashboard

- docs/01_cva6_user/Custom_Instructions.rst
- docs/01_cva6_user/Programmer_View.rst
Various minor precisions in the user's guide.
> [Skip CI] Various user's guide edits

- config_pkg_generator.py
It now also manages `` `define``s and `` `undef``s.
> feat: update config_pkg_generator.py

- Makefile
- core/mmu_sv32/cva6_mmu_sv32.sv
This PR is related with the #988 and also tries to solve the compilation issues that Questa has with the current RTL
> Adapt MMU to allow Questa compilation

- core/csr_regfile.sv
- core/include/riscv_pkg.sv
- docs/01_cva6_user/ip-xact/cva6_csr.md
- docs/01_cva6_user/ip-xact/cva6_csr.rst
- docs/01_cva6_user/ip-xact/cva6_csr.xml
- docs/01_cva6_user/ip-xact/cva6_csr.yaml
Fixing the issue that occured in MSTATUS by updating RTL: 
-riscv_pkg.sv: adding mstatus pkg and updating sstatus pkg 
-Updating the csr_regfile.sv to these changes.
Updating MSTATUS register specification in the ip-xact file , yaml , MarkDown and RST files by adding WPRI fields.
> Adding WPRI in register MSTATUS

- core/serdiv.sv
In the current version, the serdiv module takes between 1 and WIDTH+2 cycles from the incoming request (_in_vld_i_) until the assertion of the valid signal (_out_vld_o_).
The worst case scenario is a division by 0 or -1, as the counter gets set to WIDTH (see line 108).
By introducing fast paths for these two cases (similar to _div_res_zero_), the maximum latency can be reduced to WIDTH+1 and divisions by 0 or -1 only take a single cycle now.
We verified the functionality of both the original and proposed design with a set of formal properties.
We have not checked if these changes affect the critical path in any way.
- Added a new register _op_b_neg_one_q_ which indicates if b is -1. 
The _lzc_b_no_one_ signal is now used to determine if b is 0 or -1.
- Introduced a fast path for 0 and -1 …
> serdiv - Reduced worst-case latency 

- core/csr_regfile.sv
- core/mmu_sv32/cva6_tlb_sv32.sv
- core/pmp/src/pmp.sv
- core/pmp/src/pmp_entry.sv
[issue#1156](https://github.com/openhwgroup/cva6/issues/1156)
> Resolved latch lint warnings

- core/cvxif_example/cvxif_example_coprocessor.sv
[issue#1149](https://github.com/openhwgroup/cva6/issues/1149)
> Resolved ALWCOMBORDER lint warning

- README.md
Provide more information to CVA6 users.
> More information during the interfaces modification.

- docs/01_cva6_user/PMA.rst
That's a first draft on the PMA user guide section. Open to suggestions/improvements.
> Add first draft on PMA region

- core/acc_dispatcher.sv
- core/cva6.sv
This PR moves the data cache invalidation and fflag signals used when `ENABLE_ACCELERATOR = 1` from the top module into the `acc_dispatcher` module. This change is related to PR #1024.
Doing this, projects that do not use the invalidation interface or the fflag signals can just tie them off. This also means that the request and response structs can leave these signals out if they are not needed.
> Move Cache Invalidation and FFlag Signals into `acc_dispatcher`

- core/ex_stage.sv
It's Fix recommended by @t0251133
> HOTFIX : Add mode info in the CVA6 req to the Co-proce

- docs/01_cva6_user/ip-xact/cva6_csr.xml
- docs/01_cva6_user/ip-xact/cva6_csr.yaml
> [Skip CI] Fix the reset value of MISA in user manual (fix #1048)

- Bender.yml
- Flist.ariane
- core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
- corev_apu/src/ariane.sv
This PR includes configs for CVA6 to be used inside Polara project.
> Adding configs for Polara

- core/csr_regfile.sv
> Fix index calculation for locked PMP csr logic

- .gitlab-ci/expected_synth.yml
https://github.com/openhwgroup/cva6/pull/1333 seems to have slightly reduced area
> update expected gate count

- docs/01_cva6_user/CVX_Interface_Coprocessor.rst
I have performed minor editorial changes on @Gchauvon version.
Review guidelines:
- @Gchauvon: check I have not altered the meaning with my modifications.
- @JeanRochCoulon: check the accuracy of the technical content.
@MikeOpenHWGroup, would you like to be added as a reviewer?
> [Skip CI] CV-X-IF user guide: editorial changes.

- docs/01_cva6_user/Programmer_View.rst
Update the Programmer Views doc for the RISCV extensions and privileges.
> Programmer Views doc update

- core/cache_subsystem/std_cache_subsystem.sv
This PR fixes the propagation of the AXI `w_valid` signal in the `std_cache_subsystem` in the case that `aw_ready` is dependent on `w_valid`. The W-Channel fifo now also operates in fall through mode, removing a cycle of signal delay.
> Fix STD Cache AXI `w_valid` Propagation

- docs/01_cva6_user/Programmer_View.rst
- docs/01_cva6_user/RISCV_Instructions.rst
- docs/02_cva6_requirements/cva6_requirements_specification.rst
Closes https://github.com/openhwgroup/cva6/issues/1270 & https://github.com/openhwgroup/cva6/issues/1271
> [Docs] Adding Zicond in user and requirement specs

- core/branch_unit.sv
This patch fixes the issue [cva6#1466](https://github.com/openhwgroup/cva6/issues/1466): the branch unit incorrectly raises exception when target address is misaligned in regardless of the type of branch (can be unconditional or conditional).
According to RISC-V specificaiton p.11:
> An instruction address misaligned exception is generated on a taken
branch or unconditional jump if the target address is not four-byte aligned.
This patch fixes this by taking into account the type of branch and do a check on result (taken or not) when the branch is a conditional one.
> Branch unit: Fix incorrect raising of  misaligned exception

- verif/tests/custom/isacov/seq_hazard.S
- verif/tests/testlist_isacov.yaml
Add directed test to cover some sequential hazard instruction
> ISACOV : Add test for sequential hazard instruction

- verif/docs/VerifPlans/csr_access/VP_IP000.yml
- verif/docs/VerifPlans/csr_access/VP_IP001.yml
- verif/docs/VerifPlans/csr_access/VP_IP002.yml
- verif/docs/VerifPlans/csr_access/VP_IP003.yml
- verif/docs/VerifPlans/csr_access/VP_IP004.yml
- verif/docs/VerifPlans/csr_access/dvplan_csr-access.md
Hi All,
This PR adds the dvplan for CV32A6 CSR Access Verification. 
Let me know if any changes are required.
Thanks,
> CV32A6 CSR Access dvplan

- verif/sim/Makefile
To avoid fail during vcs-uvm simulation
> Wait for VCS license for vcs-uvm target

- .gitlab-ci/expected_synth.yml
#1483 has reduced the gate count.
> [HOTFIX] Ajust gate count following a light reduction

- core/cva6.sv
A bad operation lead to update directly master while the idea was to create a PR. The synthesis is broken. Try to fix it with this hot fix
> [HOT FIX] fix synthesis job

- README.md
Add information in the README.md to retrieve the supported Verilator version
> Supported Verilator version information

- .gitlab-ci/expected_synth.yml
- core/include/config_pkg.sv
Zicond increases slightly the gate count.
> expected_synth.yml due to Zicond activation

- verif/env/corev-dv/custom/riscv_custom_instr_enum.sv
- verif/env/corev-dv/custom/riscv_zcb_instr.sv
- verif/env/corev-dv/custom/rv32zcb_instr.sv
- verif/env/corev-dv/cva6_defines.svh
- verif/env/corev-dv/cva6_instr_gen_config.sv
- verif/env/corev-dv/cva6_instr_test_pkg.sv
Hello, This PR Add Zcb to the generator CVA6-DV
> CVA6-DV : Add Zcb extension instructions into cva6-dv

- core/mmu_sv39/mmu.sv
> Update mmu.sv for PMP violations tval value

- core/store_buffer.sv
Resolves [issue#1347](https://github.com/openhwgroup/cva6/issues/1347)
> Increased utilization of the speculative queue of store buffer

- verif/regress/dv-generated-tests.sh
- verif/regress/dv-generated-xif-tests.sh
- verif/regress/smoke-gen_tests.sh
This PR related to changing the target used for the generated tests.
> Change STEP1 target with the embedded target

- .gitlab-ci/expected_synth.yml
- .gitlab-ci/scripts/report_synth.py
* update expected synthesis result
* widen area validity window to ±500 gates
> Update area + widen valitidy window

- docs/01_cva6_user/Programmer_View.rst
- docs/01_cva6_user/RISCV_Instructions.rst
- docs/02_cva6_requirements/cva6_requirements_specification.rst
This PR (partially) resolves #1411
> [DOCS] Add Zcb Instructions in CVA6 user guide and requirement specification

- core/csr_regfile.sv
CSR_TSELECT, CSR_TDATA1, CSR_TDATA2, CSR_TDATA3 are not implemented yet. Gen exception when accessing these CSRs.
> Generate illegal exception when accessing CSR Trigger CSRs

- core/decoder.sv
https://github.com/openhwgroup/cva6/issues/1588
> removing zexth from RV64

- .gitlab-ci/expected_synth.yml
Code has been conditioned by configuration, that's why gate count decreased
> [hot fix] Update expected gate count

- .gitmodules
- verif/.gitignore
- verif/regress/install-riscv-dv.sh
This will make it possible to use Dependabot to keep it updated.
This also reduces the amount of scripts we need to manage.
> Convert DV into a submodule

- .gitlab-ci/scripts/report_benchmark.py
- util/config_pkg_generator.py
- verif/regress/coremark.sh
The embedded configuration is the one we want to verify.
> use embedded config to run coremark

- verif/env/corev-dv/cva6_unsupported_instr.sv
> HOTFIX : Add parenthesis to "inside" constraint

- .github/dependabot.yml
> dependabot: update verif/sim/dv

- core/compressed_decoder.sv
previously, some conditions were not covered
this code is strictly equivalent
> compressed_decoder.sv: reorganize conditions to improve code coverage

- ACKNOWLEDGEMENTS.md
- README.md
Following a meeting with @davideschiavone (TRISTAN) and Flo, for a solution common to all projects (and alignment with TRISTAN project).
> Organizing acknowledgements in the repo

- .gitlab-ci.yml
As this i test is not adpated to embedded configuration, remove it from CI.
> Remove csr test from CI

- verif/env/corev-dv/cva6_unsupported_instr.sv
to improve CC, I add more constraint to generate an illegal func7 of sfence.vma instruction
> Add constraint to generate illegal sfence.vma func7

- verif/regress/dv-generated-tests.sh
Increase random generated load/store tests to improve CC
> Add more load_store generated tests to improve CC

- core/cache_subsystem/cva6_icache.sv
- core/cache_subsystem/wt_axi_adapter.sv
- core/instr_realign.sv
- core/scoreboard.sv
- core/store_unit.sv
- corev_apu/tb/common/mock_uart.sv
- verilator_config.vlt
https://github.com/openhwgroup/cva6/issues/1377
> removing lint warnings..

- core/csr_regfile.sv
- core/decoder.sv
- core/issue_read_operands.sv
- core/load_unit.sv
- core/store_unit.sv
See GitHub PR [#1642](https://github.com/openhwgroup/cva6/pull/1642)
> Modify coding style to improve CC

- .github/workflows/ci.yml
- core/Flist.cva6
- core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
- core/include/cva6_hpdcache_default_config_pkg.sv
- Update reference of the HPDcache submodule and related packages
> Update version of the HPDcache submodule

- core/alu.sv
Missing reformatting in a previous PR
> alu.sv: verible format

- CONTRIBUTING.md
Warn contributors to use verible-verilog-format
> CONTRIBUTING.md: add verible-verilog-format

- .gitlab-ci/scripts/report_benchmark.py
It will be nice to have it in the Dashboard.
> ci: report embedded CoreMark/MHz score

- docs/01_cva6_user/RISCV_Instructions_RVZba.rst
- docs/01_cva6_user/RISCV_Instructions_RVZbb.rst
- docs/01_cva6_user/RISCV_Instructions_RVZbc.rst
- docs/01_cva6_user/RISCV_Instructions_RVZbs.rst
> Update Zb* docs

- verif/env/uvme/cov/uvme_cva6_config_covg.sv
- verif/env/uvme/reg/cva6_csr_reg_file.sv
- verif/sim/cva6.hvp
- verif/sim/modifier_embedded.hvp
Added covergroup read and write for each CSR.
> Added CSR covegroups for read and write operations, hvp updated accordantly

- core/csr_regfile.sv
> Fix inhibit impact on MCYCLE csr

- docs/csr-from-ip-xact/cv32a60x/csr.rst
- docs/csr-from-ip-xact/cv32a60x/cv32a60mx_csr.md
- docs/csr-from-ip-xact/cv32a60x/cv32a60mx_csr.yaml
Fix discrepancy between doc and RTL.
> doc: update MVENDORID CSR value (fix #1735)

- corev_apu/tb/ariane_tb.sv
- verif/tb/uvmt/cva6_tb_wrapper.sv
Fix some failing test on riscv-tests virtual due to memory not being correctly loaded in vcs.
Segment are weirdly defined and address were loaded two times with different values.
> Check that loaded elf segment do not overlap on already loaded address

- verif/regress/smoke-tests.sh
- verif/sim/Makefile
- verif/sim/cva6.py
- verif/sim/cva6.yaml
Add priv level to ` cva6.py` to pass it to Spike
Fix smoke tests to previously source `setup-env.sh`
> Add `priv` to Spike and fix smoke-tests

- verif/sim/Makefile
Update path init_testharness.do file which initialize verdi session
> Fix path for vcs init_testharness.do

- core/csr_regfile.sv
Hardwire MPP to M-mode when User mode is not present. Should fix #1756
> Check that User mode is enable to set MPP to U-mode (fix #1756)

- verif/regress/smoke-tests.sh
Smoke-tests.sh will test all configuration: 64bits, 32bits-step1, 32bits-embedded
> Run simulation for embedded configuration

- verif/regress/dv-csr-embedded-tests.sh
- verif/regress/dv-generated-tests.sh
- verif/regress/dv-generated-xif-tests.sh
- verif/regress/smoke-gen_tests.sh
This MR add --priv option for Spike to only support machine mode
> GEN_TESTS: Add --priv option to command generated tests

- core/cache_subsystem/cva6_hpdcache_if_adapter.sv
This PR fixes the processing of AMOs in 32-bits configurations
> fix: support of AMOs in cv32 configurations

- verif/regress/dv-generated-tests.sh
- verif/sim/cva6.hvp
- verif/tests/custom/isacov/branch_to_zero.S
- verif/tests/custom/isacov/isa_test.S
- verif/tests/custom/isacov/load_reg_hazard.S
- verif/tests/testlist_isacov.yaml
This MR related to ISA functional coverage : 
1. Add isa_test (to cover some corner cases)
2. update load_reg_test and branch_test
3. update Functional coverage report (HVP)
> ISA functional coverage : Add directed tests

- core/csr_regfile.sv
In ce7e30f6, mcountinhibit CSR has been introduced to offer
the possibility to inhibit some performance counters.
To reduce the area size when no performance counter,
this CSR is removed.
The CVA6 behaviour without performance counter becomes
as before ce7e30f6.
> csr_regfile.sv: mcountinhibit only when PERF_COUNTER_EN (fix #1844)

- .gitlab-ci/expected_synth.yml
- core/csr_regfile.sv
these CSRs do not exist when no user mode
> csr_regfile.sv: no MENVCFG[H], MCOUNTEREN when no User mode (fix #1843)

- core/frontend/bht.sv
- core/frontend/btb.sv
- core/frontend/ras.sv
> [HOTFIX] Fix ras.sv

- verif/docs/VerifPlans/ISA_RV32/VP_IP019.yml
- verif/docs/VerifPlans/ISA_RV32/VP_IP020.yml
- verif/docs/VerifPlans/ISA_RV32/VP_IP021.yml
- verif/docs/VerifPlans/ISA_RV32/VP_IP022.yml
- verif/docs/VerifPlans/source/dvplan_ISA_RV32.md
Hello,
This MR related to add bit-manipulation instructions
> ISA DVPLAN : Add bit-manipulation instructions (Zb*)

- verif/env/uvme/cov/uvme_exception_covg.sv
This MR add, functional coverage for RO CSRs raising an exception where trying to write from them
> Exceptions : Add bins for Read-only CSRs

- core/cva6_mmu/cva6_mmu.sv
- core/cva6_mmu/cva6_tlb.sv
Fix VCS simulation errors introduced in MMU PR https://github.com/openhwgroup/cva6/pull/1876
> fix vcs simulation errors regarding hypervisor extension code

- util/gcc-toolchain-builder/README.md
> [HOTFIX] Update README.md

- .gitlab-ci/scripts/report_simu.py
- verif/sim/cva6.py
remove space before colon in log messages
> cva6.py: fix typos in displayed messages

- core/commit_stage.sv
improve code coverage when Zcmp is disabled
> commit_stage.sv: add condition before Zcmp code

- docs/04_cv32a65x_design/source/parameters_cv32a65x.rst
- docs/04_cv32a65x_design/source/port_alu.rst
- docs/04_cv32a65x_design/source/port_bht.rst
- docs/04_cv32a65x_design/source/port_branch_unit.rst
- docs/04_cv32a65x_design/source/port_btb.rst
- docs/04_cv32a65x_design/source/port_commit_stage.rst
- docs/04_cv32a65x_design/source/port_compressed_decoder.rst
- docs/04_cv32a65x_design/source/port_csr_buffer.rst
- docs/04_cv32a65x_design/source/port_csr_regfile.rst
- docs/04_cv32a65x_design/source/port_cva6.rst
- docs/04_cv32a65x_design/source/port_cva6_hpdcache_subsystem.rst
- docs/04_cv32a65x_design/source/port_cvxif_fu.rst
- docs/04_cv32a65x_design/source/port_decoder.rst
- docs/04_cv32a65x_design/source/port_ex_stage.rst
- docs/04_cv32a65x_design/source/port_frontend.rst
- docs/04_cv32a65x_design/source/port_instr_queue.rst
- docs/04_cv32a65x_design/source/port_instr_realign.rst
- docs/04_cv32a65x_design/source/port_instr_scan.rst
- docs/04_cv32a65x_design/source/port_issue_read_operands.rst
- docs/04_cv32a65x_design/source/port_issue_stage.rst
- docs/04_cv32a65x_design/source/port_load_store_unit.rst
- docs/04_cv32a65x_design/source/port_load_unit.rst
- docs/04_cv32a65x_design/source/port_mult.rst
- docs/04_cv32a65x_design/source/port_multiplier.rst
- docs/04_cv32a65x_design/source/port_ras.rst
- docs/04_cv32a65x_design/source/port_scoreboard.rst
- docs/04_cv32a65x_design/source/port_serdiv.rst
- docs/04_cv32a65x_design/source/port_store_unit.rst
Generate docs after parametrization PRs
> Update doc after parametrization changes

- core/cva6_rvfi.sv
- core/include/rvfi_types.svh
fix some bad assignments and lint warning related to RVFI feature
> fix some bad assignments and lint warning related to RVFI feature

- core/decoder.sv
@AyoubJalali can you please double check if it ok now.
Thank you.
> Fix issue #1953

- verif/regress/smoke-tests.sh
Add debug_disable=1 to match default configuration of cva6.py
> Add debug_disable=1 to match default configuration of cva6.py

- core/csr_regfile.sv
> Fix PMP CSR locked behavior

- core/cva6.sv
- core/frontend/frontend.sv
- core/frontend/instr_queue.sv
- core/id_stage.sv
> superscalar: return 2 instructions from instruction queue

- verif/env/uvme/cov/uvme_cva6_config_covg.sv
- verif/env/uvme/uvme_cva6_env.sv
- verif/env/uvme/uvme_cva6_pkg.sv
- verif/tb/uvmt/uvmt_cva6_tb.sv
This MR fix issue #2018
The commentated coverpoint are related to parameters does not exist in cva6_cfg_t (are in user_cfg), is that intend to leave some parameters in user_cfg ?
> Fix issue #2018

- core/cache_subsystem/cache_ctrl.sv
- core/cache_subsystem/wt_dcache.sv
- core/cache_subsystem/wt_dcache_ctrl.sv
- core/csr_regfile.sv
- core/cva6.sv
- core/frontend/frontend.sv
- core/frontend/instr_queue.sv
- core/include/ariane_pkg.sv
- core/include/build_config_pkg.sv
- core/include/config_pkg.sv
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a65x_config_pkg.sv
- core/include/cv32a6_embedded_config_pkg.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdcv_sv39_config_pkg.sv
- core/load_store_unit.sv
- core/load_unit.sv
- core/store_unit.sv
> Define InstrTlbEntries, DataTlbEntries, cfg.NrLoadPipeRegs, NrStorePipeRegs, DcacheIdWidth as CVA6 parameters

- verif/tests/testlist_riscv-arch-test-cv32a65x.yaml
- verif/tests/testlist_riscv-compliance-cv32a65x.yaml
- verif/tests/testlist_riscv-csr-access-test-cv32a65x.yaml
- verif/tests/testlist_riscv-tests-cv32a65x-p.yaml
since the introduction of cv32a65x configuration, test suites are not
executed for this configuration
> testlists for cv32a65x: add files

- core/cva6_rvfi.sv
- corev_apu/tb/common/spike.sv
- verif/regress/coremark.sh
- verif/regress/smoke-tests.sh
- verif/sim/Makefile
Reduce the overhead of the CSRs by just getting the `_d`.
> [RVFI] Optimize CSRs

- .gitlab-ci.yml
- verif/docs/coverage_status/isacov_status.rst
- verif/tests/custom/isacov/illegal_isa.S
- verif/tests/custom/isacov/isa_test.S
- verif/tests/testlist_isacov.yaml
This MR add ISA coverage status
> ISA coverage status

- Makefile
- verif/sim/Makefile
Support TRACE_COMPACT export for vcs-testharness to generate fsdb.
> Add support for waveform in vcs-testharness

- verif/regress/smoke-tests.sh
Fix : Add UVM_VERBOSITY flag to DV_OPTS
> Fix DV_OPTS by adding UVM_VERBOSITY flag

- verif/env/uvme/reg/cva6_csr_reg_file.sv
This MR remove covering S-mode in MIP & MIE csrs in csr coverage model
> CSR coverage model : Remove covering S-mode fileds in MIP & MIE

- docs/06_cv32a65x_riscv/src/config.adoc
- docs/06_cv32a65x_riscv/src/machine.adoc
Customize the priv ISA doc to specify CV32A65X behaviour
> doc priv: tailor machine.adoc for CV32A65X

- docs/04_cv32a65x_design/source/index.rst
- docs/06_cv32a65x_riscv/Makefile
- docs/06_cv32a65x_riscv/index.rst
- docs/06_cv32a65x_riscv/priv-isa-cv32a65x.html
- docs/index.rst
> Provide RISC-V ISA priv in ReadTheDocs

- core/decoder.sv
Add supervisor condition under Interrupt control to condition Supervisor Timer Interrupt, Supervisor Software Interrupt and Supervisor external interrupt.
> Add supervisor condition under Interrupt control

- core/decoder.sv
- core/include/build_config_pkg.sv
- core/include/config_pkg.sv
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a65x_config_pkg.sv
- core/include/cv32a6_embedded_config_pkg.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdcv_sv39_config_pkg.sv
- verif/env/uvme/cov/uvme_cva6_config_covg.sv
- verif/sim/cva6.hvp
- verif/tb/core/uvma_cva6pkg_utils.sv
- verif/tests/testlist_hwconfig.yaml
Reminder: open Github issue to create dependency check between RVD and XLEN in riscv-config.
> Rename FpuEn into RVF

- core/include/cv32a65x_config_pkg.sv
This PR is part of the parametrization task
> Remove hpdcache localparam dependency in 65x config

- corev_apu/fpga/src/bootrom/Makefile
Fix issue https://github.com/openhwgroup/cva6/issues/2119
> keep march in bootrom generation without extensions - fix 2119

- verif/docs/VerifPlans/AXI/VP_IP005.yml
- verif/docs/VerifPlans/AXI/VP_IP006.yml
- verif/docs/VerifPlans/AXI/VP_IP007.yml
- verif/docs/VerifPlans/AXI/VP_IP008.yml
- verif/docs/VerifPlans/AXI/VP_IP009.yml
- verif/docs/VerifPlans/AXI/runme.sh
- verif/docs/VerifPlans/source/dvplan_AXI.md
Modify the DvPlan according to changes in the AXI user guide
> AXI: DvPlan modification

- .gitlab-ci.yml
- .gitlab-ci/scripts/report_functional_coverage.py
- verif/sim/cva6.hvp
Hello, this MR related to display functional coverage results for ISA, CSRs and TRAPs, another related MR while be open to report the results in dashbord
> Functional coverage report in CI

- verif/regress/dv-csr-embedded-tests.sh
This MR fix CSRs tests timeout
> [HOT FIX] Fix csr tests timeout

- verif/env/uvme/cov/uvme_cva6_config_covg.sv
This MR update config values in sanity functional coverage check
> Functional coverage : Fix config values in sanity check

- verif/tb/core/uvma_cva6pkg_utils.sv
> Fix issue #2027 Remove localparam

- verif/env/uvme/cov/uvme_cva6_config_covg.sv
- verif/env/uvme/uvme_cva6_cfg.sv
- verif/env/uvme/uvme_cva6_env.sv
Set env_cfg directly from the CVA6 configuration.
> Set env_cfg directly from the CVA6 configuration.

- .gitlab-ci/scripts/report_coverage.py
- verif/sim/cva6.hvp
This MR fixes an error seen in the last scheduled pipeline in the code coverage job : 
1. Update HVP
2. Update Code coverage report script after switching to HPDcache
> HOTFIX: update HVP & CC report script to solve an error in CC job

- verif/env/uvme/cov/uvme_cva6_config_covg.sv
- verif/env/uvme/uvme_cva6_cfg.sv
This complete the #2137, to fix the issue #2027
> Fix issue #2027

- core/csr_regfile.sv
Disable some bits when RVU or RVS not present
> [CSR] Fix bits when RVS and RVU not available

- verif/sim/Makefile
- verif/sim/cva6.py
- verif/sim/setup-env.sh
There are two minor simulation flow enhancements:
1. refactor: move env variables settings from cva6.py to setup-env.sh
2. Improve Makefile dependency management
> Two minor simulation flow enhancements 

- verif/tests/testlist_csr_embedded.yaml
- verif/tests/testlist_custom.yaml
- verif/tests/testlist_cvxif.yaml
- verif/tests/testlist_hwconfig.yaml
- verif/tests/testlist_isacov.yaml
- verif/tests/testlist_issues.yaml
- verif/tests/testlist_riscv-arch-test-cv32a60x.yaml
- verif/tests/testlist_riscv-arch-test-cv32a65x.yaml
- verif/tests/testlist_riscv-arch-test-cv32a6_embedded.yaml
- verif/tests/testlist_riscv-arch-test-cv64a6_imafdc_sv39.yaml
- verif/tests/testlist_riscv-compliance-cv32a65x.yaml
- verif/tests/testlist_riscv-compliance-cv32a6_embedded.yaml
- verif/tests/testlist_riscv-compliance-cv32a6_imac_sv0.yaml
- verif/tests/testlist_riscv-compliance-cv64a6_imafdc_sv39.yaml
- verif/tests/testlist_riscv-compliance-rv32ima.yaml
- verif/tests/testlist_riscv-csr-access-test-cv32a60x.yaml
- verif/tests/testlist_riscv-csr-access-test-cv32a65x.yaml
- verif/tests/testlist_riscv-csr-access-test-cv32a6_embedded.yaml
- verif/tests/testlist_riscv-mmu-sv32-arch-test-cv32a60x.yaml
- verif/tests/testlist_riscv-tests-cv32a60x-p.yaml
- verif/tests/testlist_riscv-tests-cv32a60x-v.yaml
- verif/tests/testlist_riscv-tests-cv32a65x-p.yaml
- verif/tests/testlist_riscv-tests-cv32a6_embedded-p.yaml
- verif/tests/testlist_riscv-tests-cv32a6_imac_sv0-p.yaml
- verif/tests/testlist_riscv-tests-cv32a6_imac_sv0-v.yaml
- verif/tests/testlist_riscv-tests-cv64a6_imafdc_sv39-p.yaml
- verif/tests/testlist_riscv-tests-cv64a6_imafdc_sv39-v.yaml
- verif/tests/testlist_riscv-tests-rv32ima-p.yaml
- verif/tests/testlist_riscv-tests-rv32ima-v.yaml
Update all verif/tests/testlist*.yaml files with #2073 enhancement, to make the testlist YAML file more compact and readable.
> Update testlist yaml with #2073 PR using yaml anchor/alias

- core/cva6_mmu/cva6_tlb.sv
Including PR https://github.com/openhwgroup/cva6/pull/1807
> Add the condition for updating the tlb only after a miss is incurred

- docs/01_cva6_user/AXI_Interface.rst
Modify AXI interface specification by adding constraint that are not supported by CVA6
> axi Specification: Modify the AXI memory interface specification

- docs/04_cv32a65x_design/source/parameters_cv32a65x.rst
- docs/04_cv32a65x_design/source/port_frontend.rst
- docs/04_cv32a65x_design/source/port_id_stage.rst
- docs/04_cv32a65x_design/source/port_instr_queue.rst
- docs/04_cv32a65x_design/source/port_issue_stage.rst
- docs/04_cv32a65x_design/source/port_scoreboard.rst
last commits: RVF, SUPERSCALAR,...
> Update the specification after the last commits

- core/cache_subsystem/wt_dcache.sv
- core/cache_subsystem/wt_dcache_mem.sv
- core/cache_subsystem/wt_dcache_wbuffer.sv
- core/include/ariane_pkg.sv
- core/include/cv32a65x_config_pkg.sv
- core/include/wt_cache_pkg.sv
Use CVA6Cfg.WtDcacheWbufDepth in place of DCACHE_WBUF_DEPTH
> Continue parametrization

- .github/workflows/ci.yml
- .gitlab-ci.yml
- Makefile
- core/cva6_rvfi.sv
- corev_apu/tb/ariane_testharness.sv
- corev_apu/tb/common/spike.sv
- corev_apu/tb/rvfi_tracer.sv
- verif/env/uvme/uvme_cva6_cfg.sv
- verif/env/uvme/uvme_cva6_env.sv
- verif/env/uvme/uvme_cva6_sb.sv
- verif/sim/Makefile
- verif/sim/cva6.py
- verif/tb/core/custom_uvm_macros.svh
- verif/tb/core/uvma_core_cntrl_pkg.sv
- verif/tb/core/uvma_cva6pkg_utils.sv
- verif/tb/core/uvma_cva6pkg_utils_pkg.sv
PR for the incoming changes to core-v-verif (not already merged)
> Bump verif/core-v-verif from f7bda8e to NOTMERGED

- core/cva6_mmu/cva6_mmu.sv
Use vaddr for tval instead of paddr when translation is enabled
> fix tval in mmu

- .gitlab-ci.yml
- .gitlab-ci/scripts/report_coverage.py
- verif/sim/cva6.hvp
Hello, this MR add the capability of adding functional coverage report in the DASHBOARD
> Add the capability to add functional coverage results into the dashboard

- verif/env/uvme/cov/uvme_axi_covg.sv
- verif/env/uvme/cov/uvme_axi_ext_covg.sv
- verif/env/uvme/uvme_cva6_cfg.sv
- verif/env/uvme/uvme_cva6_env.sv
- verif/tb/uvmt/uvmt_cva6_pkg.sv
- verif/tests/uvmt/base-tests/uvmt_cva6_base_test.sv
Integrate the new AXI agent into the CVA6 environment.
Modify the AXI coverage model and adapt it to the new transactions.
> Connect the new AXI agent with CVA6

- .gitlab-ci/scripts/report_coverage.py
This update coverage report script after excluding HPDcache module
> Update coverage script after exclude HPDcache module

- .gitlab-ci/scripts/report_benchmark.py
- .gitmodules
- core/Flist.cva6
- core/Flist.cva6_gate
- core/cache_subsystem/cache_ctrl.sv
- core/cache_subsystem/cva6_hpdcache_subsystem.sv
- core/cache_subsystem/cva6_icache.sv
- core/cache_subsystem/cva6_icache_axi_wrapper.sv
- core/cache_subsystem/std_cache_subsystem.sv
- core/cache_subsystem/wt_cache_subsystem.sv
- core/cva6.sv
- core/cva6_mmu/cva6_mmu.sv
- core/cva6_rvfi.sv
- core/ex_stage.sv
- core/frontend/frontend.sv
- core/include/build_config_pkg.sv
- core/include/config_pkg.sv
- core/load_store_unit.sv
- core/perf_counters.sv
Goals:
* Address translation request moved from icache to frontend
* OBI protocol between icache and frontend
Work in progress !!
* OBI compliance not verified
* No verification done
* impact on performance seen on coremark
> OBI protocol between Frontend to icache

- verif/regress/smoke-tests.sh
There was an extra '-v' in `verif/regress/smoke-tests.sh`.
> Remove extra -v in smoke-tests.sh

- core/branch_unit.sv
- core/cache_subsystem/cache_ctrl.sv
- core/cva6.sv
- core/cva6_rvfi.sv
- core/cva6_rvfi_probes.sv
- core/ex_stage.sv
- core/include/build_config_pkg.sv
- core/include/rvfi_types.svh
- core/issue_read_operands.sv
- core/issue_stage.sv
- core/scoreboard.sv
It is not superscalar as there is only one ALU yet.
There are other performance features to add before that, such as speculative scoreboard.
> superscalar: add a second issue port

- verif/env/uvme/uvme_cva6_sb.sv
This MR fix CSR instruction decode, and change verbosity messages' to UVM_DEBUG
> Fix Csr instruction decode and change the message verbosity

- core/cache_subsystem/cache_ctrl.sv
- core/csr_regfile.sv
- core/cva6_rvfi.sv
- core/include/build_config_pkg.sv
- core/include/config_pkg.sv
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a65x_config_pkg.sv
- core/include/cv32a6_embedded_config_pkg.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdcv_sv39_config_pkg.sv
- core/include/cv64a6_mmu_config_pkg.sv
> Define a new param to constraint mtvec to be in direct mode only

- core/acc_dispatcher.sv
- core/cache_subsystem/cache_ctrl.sv
- core/cache_subsystem/cva6_hpdcache_if_adapter.sv
- core/cache_subsystem/cva6_hpdcache_subsystem.sv
- core/cache_subsystem/cva6_icache.sv
- core/cache_subsystem/std_cache_subsystem.sv
- core/cache_subsystem/std_nbdcache.sv
- core/cache_subsystem/wt_cache_subsystem.sv
- core/cache_subsystem/wt_dcache.sv
- core/cache_subsystem/wt_dcache_ctrl.sv
- core/cache_subsystem/wt_dcache_wbuffer.sv
- core/cva6.sv
- core/cva6_mmu/cva6_mmu.sv
- core/cva6_mmu/cva6_ptw.sv
- core/ex_stage.sv
- core/frontend/frontend.sv
- core/load_store_unit.sv
- core/load_unit.sv
- core/perf_counters.sv
- core/store_buffer.sv
- core/store_unit.sv
Fetch:
- fix icache combi loop
LSU:
- Prepare OBI structure
> interconnect alpha2

- docs/04_cv32a65x/riscv/Makefile
> cv32a65x doc: fix RISC-V unpriv pdf generation

- .gitlab-ci/expected_synth.yml
- core/instr_realign.sv
Fix issue https://github.com/openhwgroup/cva6/issues/2240
> Fix instruction realign when C extension is not used 

- docs/04_cv32a65x/riscv/Makefile
- docs/04_cv32a65x/riscv/priv-isa-cv32a65x.html
- docs/04_cv32a65x/riscv/src/bfloat16.adoc
- docs/04_cv32a65x/riscv/src/colophon.adoc
- docs/04_cv32a65x/riscv/src/config.adoc
- docs/04_cv32a65x/riscv/src/machine.adoc
- docs/04_cv32a65x/riscv/src/priv-preface.adoc
- docs/04_cv32a65x/riscv/src/riscv-privileged.adoc
- docs/04_cv32a65x/riscv/src/riscv-unprivileged.adoc
- docs/04_cv32a65x/riscv/src/rv-32-64g.adoc
- docs/04_cv32a65x/riscv/src/smdbltrp.adoc
- docs/04_cv32a65x/riscv/src/ssdbltrp.adoc
- docs/04_cv32a65x/riscv/src/unpriv-cfi.adoc
- docs/04_cv32a65x/riscv/src/vector-crypto.adoc
- docs/04_cv32a65x/riscv/src/zabha.adoc
- docs/04_cv32a65x/riscv/unpriv-isa-cv32a65x.html
use latest riscv-isa-manual for CV32A65X
> update riscv-isa-manual to riscv-isa-release-c8c8075-2024-06-12

- corev_apu/tb/ariane_gate_tb.sv
> [HOT FIX] fix synthesis

- .gitlab-ci.yml
Lint check is only needed when RTL is modified
> Execute lint job when RTL is modified

- Makefile
1. Update UART to version 0.2.1
2. Replace VHDL UART as SystemVerilog UART, and then
3. Simplify VCS compile flow from 3-step flow to 2-step flow.
> Update VCS compile flow to 2-step flow in testharness and update UART to version 0.2.1

- .gitlab-ci/scripts/report_benchmark.py
- core/cache_subsystem/cva6_hpdcache_if_adapter.sv
- core/cache_subsystem/cva6_hpdcache_subsystem.sv
- core/cache_subsystem/cva6_hpdcache_wrapper.sv
This new version of the HPDcache includes multiple improvements in the write buffer microarchitecture to improve both area and performance
> Update submodule core/cache_subsystem/hpdcache

- docs/04_cv32a65x/riscv/priv-isa-cv32a65x.html
- docs/riscv-isa/src/machine.adoc
mtval is read-write register (MRW) even the only possible value is zero
> doc: clarify mtval register description when not enabled

- core/csr_regfile.sv
> Fix WARL behavior of MPP

- core/csr_regfile.sv
Fix typo on Bitmanip comment for MISA
> Fix typo on Bitmanip comment

- verif/env/uvme/uvme_cva6_cfg.sv
- verif/tb/core/uvma_cva6pkg_utils.sv
This related to CVV MR#110, so it need to merge it first then we can bump CVV with additional modification to fix the issue
> Bump CVV to fix issue 2484

- .gitlab-ci/scripts/report_spyglass_lint.py
Add lambda function to sort lint summary according to severity
Signed-off-by: Asmaa-Kassimi asmaa.kassimi@external.thalesgroup.com
> Add lambda function to sort lint summary according to severity

- verif/env/uvme/uvme_cva6_cfg.sv
- verif/tb/core/uvma_cva6pkg_utils.sv
it's a complimentary MR to fix cvv issue #2479 #2468
should merge the one on core-v-verif after we can merge this : https://gitlab-tss.gemalto.com/riscv/ohg-pr/core-v-verif/-/merge_requests/112
> Fix issue #2479 #2468

- core/cva6.sv
- core/cva6_rvfi.sv
- core/cva6_rvfi_probes.sv
- core/ex_stage.sv
- core/frontend/frontend.sv
- core/frontend/instr_queue.sv
- core/id_stage.sv
- core/include/ariane_pkg.sv
- core/include/build_config_pkg.sv
- core/include/config_pkg.sv
- core/include/cv32a65x_config_pkg.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdcv_sv39_config_pkg.sv
- core/include/cv64a6_mmu_config_pkg.sv
- core/include/rvfi_types.svh
- core/issue_read_operands.sv
- core/issue_stage.sv
- core/load_store_unit.sv
- core/scoreboard.sv
It changes the way CVA6 is configured to be conform with #1451
> superscalar: make SuperscalarEn a CVA6Cfg attribute

- core/alu.sv
- core/branch_unit.sv
> condition branch_unit and alu

- core/load_unit.sv
- core/store_unit.sv
This MR is intended to increase code coverage for load and store units
Signed-off-by: Asmaa-Kassimi <asmaa.kassimi@external.thalesgroup.com>
> condition load and store modules

- verif/tests/custom/isacov/load_reg_hazard.S
This MR related to increase isa functional coverage
> Add load hazard instructions

- core/ex_stage.sv
Fix synthesis of ex_stage after Superscalar was merged.
> fix ex_stage synthesis

- core/commit_stage.sv
- core/issue_read_operands.sv
- core/load_store_unit.sv
increase condition coverage for commit stage, load store unit and issue stage.
> increase condition coverage in lsu, issue and commit stages

- core/csr_regfile.sv
Merging in these changes fixes #2373
> Update csr_regfile.sv to fix #2373

- core/csr_regfile.sv
- spyglass/reference_summary.rpt
Add RVU condition to increase coverage
> Add RVU condition to increase coverage

- .gitlab-ci.yml
Add the ability to use a custom config to ./`gitlab-ci.yml`
> Add custom config in gitlab ci

- config/gen_from_riscv_config/README.md
- config/gen_from_riscv_config/scripts/libs/csr_updater.py
- config/gen_from_riscv_config/scripts/libs/utils.py
- config/gen_from_riscv_config/scripts/riscv_config_gen.py
- improve readme file to support debug spec generated from riscv-config
> [gen_from_riscv_config] improve readme file to support debug spec

- .gitlab-ci/scripts/report_spyglass_lint.py
This MR is intended to automate the lint check process in Thales CI when running spyglass job.
> automate lint check process

- verif/env/uvme/uvme_cva6_sb.sv
This MR add some checks to the UVM env, this related to checking MCYCLE[H]
> Add check CSR MCYCLE[H] in UVM scoreboard

- core/include/config_pkg.sv
> [HOT FIX] fix is_inside_execute

- core/cva6_rvfi.sv
- verif/regress/smoke-tests.sh
- verif/sim/Makefile
- verif/sim/cva6.py
- verif/tb/core/uvma_cva6pkg_utils.sv
* Disable yaml config for embedded configuration (it does not pass all the core params)
* Change RAM TANDEM setup
> TANDEM Configuration fixes

- core/csr_regfile.sv
- core/cva6.sv
- verif/env/uvme/uvme_cva6_env.sv
- verif/env/uvme/uvme_cva6_sb.sv
Thanks to @AyoubJalali who pointed out the issue!
> fix single-step which was x in cv32a65x config and fix mcycle for double commit 

- core/commit_stage.sv
> fix missing ZCMP condition in commit stage

- core/csr_regfile.sv
Exception is not generated when INHIBIT CSR is accessed
> fix #2464 by implementing Inhibit CSR as read only zero

- core/frontend/frontend.sv
This PR fixes NonImdempotenceEn=1 option
> Fix NonImdempotent and speculation management

- verif/sim/cva6.py
The cva6.py was buggy when using it for 65x
> fix hwconfig setup in cva6.py

- verif/env/uvme/uvme_cva6_env.sv
Remove cfg.CVA6Cfg from the env
> Fix vcs-uvm simulation flow

- .github/workflows/ci.yml
* Disabling CSR injection on trap
* Sign extension on CSR injection
> Bump verif/core-v-verif csr-injection 

- verif/tb/uvmt/cva6_tb_wrapper.sv
Drive the AXI interface slave signals with 'Z in the active mode
> Drive the AXI interface slave signals with 'Z in the active mode

- ci/install-prereq.sh
Update the phiwag/edatools gpg key to fix the CI.
> ci: Update phiwag/edatools gpg key

- docs/04_cv32a65x/riscv/priv-isa-cv32a65x.html
- docs/06_cv64a6_mmu/riscv/priv-isa-cv64a6_mmu.html
- docs/riscv-isa/src/machine.adoc
> doc PMP: rephrase PMP configuration description

- verif/regress/coremark.sh
- verif/regress/dhrystone.sh
- verif/regress/dv-riscv-arch-test.sh
- verif/regress/dv-riscv-compliance.sh
- verif/regress/dv-riscv-tests.sh
Fix for DV_OPTS in regression scripts
> Performance tb

- docs/riscv-isa/src/machine.adoc
> doc: pmp granularity equals to 8-byte

- .gitlab-ci.yml
The simu-gate ci job was broken since a while. This PR fixes it.
> [HOTFIX] Fix "simu-gate" CI job

- .gitlab-ci/scripts/report_tandem.py
* Add failures checks in \`.gitlab-ci/scripts/report_tandem.py\`:
* catch wrong or missing log directory
* catch wrong yaml reports
> Add failure checks in report_tandem script

- core/csr_regfile.sv
Additional fix to https://github.com/openhwgroup/cva6/issues/2392
> Fix issue when NrPMPEntries=0

- core/issue_read_operands.sv
- core/issue_stage.sv
- core/scoreboard.sv
- docs/design/design-manual/source/cva6_issue_stage.adoc
- docs/design/design-manual/source/design.adoc
- Fill `docs/design/design-manual/source/cva6_issue_stage.adoc`
- Add variables to `docs/design/design-manual/source/design.adoc`
- Update port doc comments in `core/issue_stage.sv`, `core/issue_read_operands.sv` and `core/scoreboard.sv`
> document issue stage

- .gitlab-ci/scripts/report_benchmark.py
- verif/env/uvme/uvme_cva6_cfg.sv
Accelerate the performance of the AXI agent by disabling all the randomization and sending responses with zero delay
> Accelerate the performance of the AXI agent

- verif/env/uvme/uvma_cva6_core_cntrl_agent.sv
- verif/env/uvme/uvma_cva6_core_cntrl_drv.sv
- verif/env/uvme/uvma_interrupt/uvma_interrupt_mon.sv
- verif/env/uvme/uvme_cva6_cfg.sv
- verif/env/uvme/uvme_cva6_core_cntrl_if.sv
- verif/env/uvme/uvme_cva6_env.sv
- verif/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv
This MR do some cleaning on the uvm env :
- fixing typo
- remove unused code
- printing in the right place
> UVM_ENV : Clean up CVA6 UVM env

- .gitlab-ci.yml
Show the config on the smoke gen dashboard report
> Show config for smoke-bench job

- docs/design/design-manual/source/cva6_frontend.adoc
> doc: fix build (cva6_frontend.adoc)

- verif/env/uvme/cvxif_vseq/uvme_cvxif_vseq.sv
> CVXIF VSEQ: RD equal x10 for CUS_ADD_RS3_RTYPE

- verif/sim/Makefile
> Code coverage : Add option to support coverage condition with arithmetic operations

- core/id_stage.sv
- core/pmp/src/pmp_entry.sv
Run verible verilog format to fix upstream formatting.
> id_stage/pmp_entry: Fix formatting

- docs/design/design-manual/source/CVX_Interface_Coprocessor.adoc
> Clean up table

- README.md
Related to issue https://github.com/openhwgroup/cva6/issues/2715
> update smoke tests file names

- verif/env/uvme/uvme_cva6_sb.sv
> Fx UVM scoreboard check VLEN bits only

- core/frontend/instr_scan.sv
as use in design document (automatically generated part)
> doc: fix description of signals in instr_scan.sv

- .github/workflows/verible.yml
As suggested by @niwis in https://github.com/openhwgroup/cva6/pull/2770
> ci: require correct formatting

- CONTRIBUTING.md
Writing some rules that were previously implicit.
> [Skip CI] Update to CONTRIBUTING.md

- core/cva6.sv
Hi! Some tools like morty struggle with this expression. I suggest this very simple rewrite. No need for fancy constructs here. Thanks @flaviens for this contribution
> Simplify the Verilog "inside" (from @flaviens)

- core/include/cv32a60x_config_pkg.sv
Not included in cv32a60x TRL-5
> Disable PMP for cv32a60x configuration

- core/include/build_config_pkg.sv
- core/include/config_pkg.sv
- core/include/cv32a60x_config_pkg.sv
- core/include/cv32a65x_config_pkg.sv
- core/include/cv32a6_embedded_config_pkg_deprecated.sv
- core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
- core/include/cv32a6_imac_sv0_config_pkg.sv
- core/include/cv32a6_imac_sv32_config_pkg.sv
- core/include/cv32a6_imafc_sv32_config_pkg.sv
- core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_hpdcache_wb_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
- core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_config_pkg.sv
- core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
- core/include/cv64a6_imafdcv_sv39_config_pkg.sv
- core/include/cv64a6_mmu_config_pkg.sv
- corev_apu/src/ariane.sv
Add parameter CoproType to select which coprocessor to instantiate when CvxifEn == 1
> Add parameter type to define which coprocessor is instantiated on CVXIF

- config/riscv-config/cv64a60ax/spec/custom_spec.yaml
- config/riscv-config/cv64a60ax/spec/debug_spec.yaml
- config/riscv-config/cv64a60ax/spec/isa_spec.yaml
- config/riscv-config/cv64a60ax/spec/platform_spec.yaml
- core/include/cv64a60ax_config_pkg.sv
- verif/env/corev-dv/target/rv64imafdc/riscv_core_setting.sv
A new configuration file and core v target is added to start working on a 64 bit CVA6 core.
> Adding a new configuration file for cv64a60ax and dv target RV64IMAFDC

- .gitlab-ci/scripts/report_spyglass_lint.py
this will avoid any regression in linting
> report_spyglass_lint.py: reject any increase in reported messages

- core/commit_stage.sv
- core/decoder.sv
This MR ralated to the effort done to condition RTL to improve code coverage
> Condition RTL to improve code coverage

- config/riscv-config/cv64a60ax/spec/isa_spec.yaml
Hello,
I have correcte the correct reset val for the MISA register. 
Thanks and Regards
Tanuj Khandelwal
> added correct reset val for misa register

- CODEOWNERS
Updating @Jbalkind and adding @cfuguet to CODEOWNERS
> Update CODEOWNERS with jbalkind and cfuguet

- core/decoder.sv
- core/issue_read_operands.sv
- core/store_buffer.sv
decoder improvement, removing of CVXIF RAW, store_buffer improvement
> Various improvement for code coverage

- core/csr_regfile.sv
improve code coverage by conditioning RTL
> csr_regfile : condition RTL to improve code coverage

- core/csr_regfile.sv
- core/cva6_pipeline.sv
Improve CC by solving for loop in csr_regfile.sv and conditioning drop signal by SpeculativeSb in cva6_pipeline.sv
> To improve CC

- core/issue_read_operands.sv
Fix issue_read_operand modification done in commit c87b3e6ad
> Fix c87b3e6ad

- core/csr_regfile.sv
> [HOTFIX] Fix 2855 PR

- verif/tb/uvmt/uvmt_cva6_tb.sv
bind cvxif assertion with cv32a60x parametres
> CVA6 Tb : bind cvxif assertion with cv32a60x parametres

- docs/riscv-isa/src/machine.adoc
according to latest CV32A60X configuration
> docs: fix TODOs in machine.adoc

- core/csr_regfile.sv
> Improve CC for MTVEC csr

- .gitlab-ci/scripts/merge_job_reports.py
- .gitlab-ci/scripts/source_branch_finder.py
avoid retrieving pull requests when running the scripts for gitlab pipelines
> fix merge report script in gitlab ci

- .gitlab-ci/scripts/merge_job_reports.py
- .gitlab-ci/scripts/source_branch_finder.py
This reverts commit 69e4e8d5c58c9de21501df45f6a6b7a54788429d.
> Revert "fix merge report script in gitlab ci (#2875)"

- core/csr_regfile.sv
Increase code coverage priv_lvl in csr_regfile
> Increase code coverage priv_lvl in csr_regfile

- Flist.ariane
- core/Flist.cva6
- core/Flist.cva6_gate
- core/frontend/btb.sv
- core/frontend/instr_queue.sv
Remove unread module and its instanciations
> Remove unread module and its instanciations

- .github/workflows/dashboard-done.yml
- .gitlab-ci/scripts/merge_job_reports.py
- .gitlab-ci/scripts/source_branch_finder.py
do not retrieve PR when running in gitlab
> fix merge report job in gitlab ci

- core/include/config_pkg.sv
> config_pkg.sv: fix typo (for doc rendering)

- core/cvxif_issue_register_commit_if_driver.sv
- core/decoder.sv
cvxif : Exec stage is non speculative
decode.sv TODO is code cleaning
> Clean up irrelevant FIXME/TODO

- core/branch_unit.sv
- core/commit_stage.sv
- core/csr_buffer.sv
- core/ex_stage.sv
- core/issue_stage.sv
- core/load_store_unit.sv
- core/load_unit.sv
- core/lsu_bypass.sv
- core/scoreboard.sv
- core/store_unit.sv
Add IO port description in RTL to have it in specification
> Fix IO port description

- .gitignore
- docs/07_cv32a60x/index.rst
This Pull-Request is the first of two PRs that will link the CV32A60X ISA chapter to the `cv32a60x` branch.
Please do not merge until we have had a chance to discuss.
> CV32A60X ISA

- core/load_unit.sv
Without this change the logic is ambiguous.
> Correct logic for sign bit in load_unit.sv

- core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
This PR fixes an issue when AxiDataWidth is greater than 64 bits but smaller than Icache linewidth on the cva6_hpdcache_cachesubsystem.
In such cases, when issuing uncacheable reads (e.g. read a ROM), the Icache expects the 8 bytes word to be right-aligned on the response interface.
It addresses issue #3075.
> Fix: right-align uncacheable reads from the Icache when AxiDataWidth > 64
