openhwgroup/cva6

ariane.core

This adds FuseSoC support for building and running the verilator model of Ariane (a.k.a. Saturn-V). Before this works, it needs FuseSoC support for the core dependencies (https://github.com/pulp-platform/axi_mem_if/pull/1 and https://github.com/pulp-platform/uvm-components/pull/1)
Once this is done, the FuseSoC support can be tested by first creating a workspace directory and register the libraries by running
fusesoc library add axi_mem_if https://github.com/pulp-platform/axi_mem_if
fusesoc library add uvm-components https://github.com/pulp-platform/uvm-components
fusesoc library add ariane https://github.com/pulp-platform/ariane
or, alternatively if the repos are already on disk and you want to use those instead, add
[library.axi_mem_if]
location = /path/to/repo
[library.uvm-components] …

Add FuseSoC support for building verilator model

---

src/alu.sv
src/ariane.sv
src/branch_unit.sv
src/ex_stage.sv

- Moved the branch resolve engine to ALU
- Updated conditions in the ALU code to account for different
type of branches as well
- Update the port definitions wherever required

:scissors: Changes for #1

---

Makefile
include/ariane_pkg.sv
src/csr_regfile.sv
src/util/instruction_trace_item.svh
travis.sh

Make ISA test path relative to $(RISCV). Add placeholder CSRs to prevent divergence when ISA tests initialise PMPs. Function needs fleshing out later. Path to fesvr/htif.h needs adding to verilator flags.

Add placeholders for PMP CSRs for memory protection.

---

src/cache_ctrl.sv
src/miss_handler.sv
src/nbdcache.sv

I discussed with Zaruba the reasons behind #54. 
The bug was triggered by a store followed by a load that triggered the eviction of the corresponding line (without saving its contents to memory).  To solve this, the store FSM checks whether its index matches the load index. If they match, the store is treated as if it has missed on the cache. 
I am unsure of the performance implications, or if the regression tests still pass.

WIP: Fix #54

---

Bender.yml
Makefile
include/ariane_pkg.sv
include/std_cache_pkg.sv
src/ariane.sv
src/ariane_wrapped.sv
src/cache_ctrl.sv
src/ex_stage.sv
src/fifo.sv
src/frontend.sv
src/icache.sv
src/if_stage.sv
src/load_unit.sv
src/lsu.sv
src/lsu_arbiter.sv
src/miss_handler.sv
src/mmu.sv
src/nbdcache.sv
src/ptw.sv
src/rrarbiter.sv
src/std_cache_subsystem.sv
src/store_buffer.sv
src/store_unit.sv
src/util/cluster_clock_gating.sv
src_files.yml

the uvm-components submodule needs to be fixed to point to 6bb81367a35bde8952217685dba9457183bc63ea
in order to account for the interface changes (see separate pull request)

cache hierarchy changes and LSU load path optimizations

---

src/lsu.sv
src/mmu.sv

- Instr/ld/st must only throw access faults when virtual memory translation is enabled
- Correct tested bit slice from [63:39] to [63:38]
- Fixes #136

Fix mismatches in virtual address checking logic (this fixes #136).

---

src/debug/dm_mem.sv
src/debug/dm_pkg.sv

The struct for `abstract_cs` was accidentally one bit too large.
This can lead to wrong conversions from DMI data when re-casted.
Furthermore register address checks during an abstract command were
potentially too loose when CSR would be accessed.

DM: Fix misaligned progbufsize and reg checks

---

fpga/constraints/genesys-2.xdc
fpga/src/ariane_peripherals_xilinx.sv

The correction to the 1000BaseT mode is ready for review and merge. The one remaining issue is why we do not see interrupts. A very similar arrangement in LowRISC with Rocket does show the expected interrupts. I am seeing a slow down with all the new kernel options being enabled. This needs reviewing as well to see if they are all necessary.

Correct mdio_oe naming, streamline to allow 1GHz capability

---

CODEOWNERS
fpga/src/ariane_xilinx.sv
src/fpu_wrap.sv
tb/ariane_soc_pkg.sv
tb/ariane_testharness.sv

Bump submodule of `riscv-exclusive` adapter which contains the fix to the Verilator issue. I can confirm that this actually solves our problem.
Furthermore this adds @stmach as `CODEOWNER` for the `fpu_wrap.sv` file. Please confirm that my changes there are correct. It seems that we decoded the cast and pack instruction incorrectly.
This also fixes the usual `valid_rule` problem with vivado (incorrect sizing of valid rules due to a known bug in Vivado).

Fix AMO problem in Verilator

---

CHANGELOG.md
include/riscv_pkg.sv
src/csr_regfile.sv
src/perf_counters.sv

The performance counters were accessible in user mode although
`mcounteren` or `scounteren` are not implemented. This commit moves the
writeable performance counters to machine mode. Access from
user/supervisor-space will trap as this is not implemented in Ariane.

Fix Performance Counter encoding

---

Makefile

It gives an error of undefined reference to multi-thread library when compiling Ariane with verilator. Add a library flag to solve this problem.

Fix the multi-thread library dependency error

---

src/util/instr_tracer.sv

Since the function spikeCommitLog in riscv_pkg.sv has // pragma translate_off/on around it, so must the corresponding code printInstr in instr_tracer.sv, in order to get through Vivado.

Add pragma around non-synthesisable code

---

src/commit_stage.sv
src/util/instr_tracer.sv

That should fix loads to floating point regs not dirtying the FP state (should fix #233). 
@jrrk I'd greatly appreciate if you could test the fix with your setup.

 fp_dirty: Dirty on fp register write

---

src/frontend/bht.sv

Currently the code in bht.sv overflows the bht_q array. Here is a suggested fix.

Prevent bht array overflow

---

fpga/src/ariane_peripherals_xilinx.sv
fpga/src/ariane_xilinx.sv
include/axi_intf.sv
src/util/axi_master_connect.sv
src/util/axi_master_connect_rev.sv
src/util/axi_slave_connect.sv
src/util/axi_slave_connect_rev.sv
tb/ariane_peripherals.sv

Continuation of #243
I've rebased on the latest changes (Travis Split). Lets wait for the CI now.

Remove duplicated interface aliases

---

Bender.yml
Flist.ariane
Makefile
src/cache_subsystem/wt_dcache_missunit.sv

Enabled the backoff module.
Changed to wait before sending AMO_LR instead of AMO_SC to guarantee someone could make progress.  
Added the exp_backoff module in Flist.ariane and Bender.

Enable exp_backoff for LR/SC 

---

include/ariane_pkg.sv
src/branch_unit.sv
src/frontend/bht.sv
src/frontend/frontend.sv
src/frontend/instr_queue.sv
tb/ariane_soc_pkg.sv

Add a gshare global history predictor to enhance the performance and fix #126  
By compare the mispredictions on benchmarks, a global history register with length = 4 performed best. Here is the comparison between the original and the new branch predictor result.
It doesn't perform well on qsort benchmark. My understanding is that in the insertion sort, the pattern between taken and untaken is not regular. It makes global history varies and make gshare harder to learn  the prediction. 
Synthesis test was run and passed.

Add global history predictor (Fix issue #126)

---

src/cache_subsystem/wt_axi_adapter.sv

Reset is missing in resettable flip-flop sensitivity list, this can lead to non-resettable FF with `rst_ni` on the data fanin of the FF.

:tshirt: Fix FF sensitivity list

---

src/cache_subsystem/miss_handler.sv

This resolves undefined behavior of `active_serving_o`

add default assignment for miss_handler.sv:active_serving_o

---

fpga/constraints/vc707.xdc
fpga/src/ariane_xilinx.sv

So we mapped `trst` to an active-high button on the VC707 -- I've changed the `ariane_xilinx.sv` portlist to reflect this.
I wasn't sure how you wanted to handle something like this, stylistically speaking. Let me know your thoughts.

Fixup `trst` in the ariane_xilinx.sv portlist

---

fpga/ariane.cfg

Enable the OpenOCD option to perform memory accesses according to the current privilege level as per https://github.com/riscv/riscv-openocd/pull/386.
i.e. when debug mode is entered from a context running on virtual memory, address translation is performed for memory reads and writes through the debugger.

ariane.cfg: enable address translation per default when debugging

---

fpga/src/bootrom/ariane.dts

The default clock frequency is 50MHz as also noted by the [device tree file](https://github.com/pulp-platform/ariane/blob/ad70ce1f30dad539e5a365ffe71a02aaf20b397e/fpga/src/bootrom/ariane.dts#L16).
The rtc is generated by 
https://github.com/pulp-platform/ariane/blob/ad70ce1f30dad539e5a365ffe71a02aaf20b397e/fpga/src/ariane_xilinx.sv#L441-L451
which, as noted, halves the clock frequency, i.e. to 25MHz.
The current device tree specifies the timebase-frequency to be 15MHz
https://github.com/pulp-platform/ariane/blob/ad70ce1f30dad539e5a365ffe71a02aaf20b397e/fpga/src/bootrom/ariane.dts#L14
Using a build of ariane-sdk and running e.g. `sleep 30` show that time based operations have about a 30 to 40% error to them, i.e. the sleep example will take only about 19 second.

Fix Linux RTC deviation

---

src/ariane.sv
src/commit_stage.sv
src/ex_stage.sv
src/load_store_unit.sv
src/load_unit.sv
src/scoreboard.sv
src/store_buffer.sv
src/store_unit.sv
tb/ariane_soc_pkg.sv

This is a tentative fix for #356. I would very much appreciate your feedback @jrrk as I don't have an isolated test case for it.
What the fix does is basically checking whether the write buffer is empty in case we are performing an uncached load. If the WB should not be empty the load is killed and retried once the WB gets empty.

load_unit: Fix #356 uncached loads served from WB

---

src/scoreboard.sv

If an instruction does not require a functional unit we want to commit it right away.

scoreboard.sv: support FU NONE

---

LICENSE.Berkeley
include/traced_instr_pkg.sv
src/ariane.sv

This is part of the broader work being done to integrate Ariane into Chipyard (see https://github.com/ucb-bar/chipyard/pull/448).
Add a trace port to the top-level Ariane IOs. This matches the format given by https://github.com/chipsalliance/rocket-chip/blob/5e506e3923c6935502b3d80afb57e329609cb326/src/main/scala/rocket/CSR.scala#L163-L172. This allows Ariane to hook up to FireSim's TracerV interface (https://docs.fires.im/en/dev/Advanced-Usage/Debugging-and-Profiling-on-FPGA/TracerV.html).
Any comments or feedback would be greatly appreciated!

Add conditional Rocket Chip traceport to top-level

---

src/compressed_decoder.sv

PR for issue #381 
If a compressed instruction fld rd, xxx(sp) use ft0 as rd, currently Ariane will generate an illegal instruction fault. However, the restriction that destination shouldn't be zero should only be applied to GPR; floating point register ft0 is not hard-wired to zero and can be used as destination.
This pull request removed the check in compressed decoder that causes this issue.

Removed the check in c.fldsp against ft0 destination

---

src/csr_regfile.sv

Wanted to address some interest in having `rdcycle` in S and U modes since the privileged spec allows this kind of delegation. Unfortunately I don't have a very minimal test case for this to check both modes, but I can see that the previous illegal access exceptions no longer appear when using `rdcycle` provided that `mcounteren`/`scounteren` have the right values.
Probably needs some further testing.
Also the changes I made are all in csr_regfile.sv. I don't know what changes need to be done to enable readtime to work properly, too.

Adding mcounteren and scounteren registers

---

Makefile

The Makefile was setup to allow setting "make verilator=..." however missed a usage so it didn't actually work.  This fixes it.
BTW thanks for using Verilator with your project!

Fix to enable verilator variable to point to Verilator

---

src/issue_read_operands.sv

🐛 issue read operands: Zimm is now zeroextended with 59 bits to 64 bits

issue read operands: fixed zimm zero extended

---

CHANGELOG.md

Among other things, this fixes VCS simulation issues for F2F casts.

fpu: Bump to release 0.6.2

---

.gitmodules
Flist.ariane
Makefile
README.md
bootrom/dromajo_bootrom.sv
src/ariane.sv
src/csr_regfile.sv
src/dromajo_ram.sv
src/util/sram.sv
tb/ariane_tb.cpp
tb/ariane_testharness.sv
tb/dpi/dromajo_cosim.cc
tb/dpi/dromajo_cosim_dpi.cc

Hi 👋 
If short, with this change you can run co-simulation with the following:
```
make verilate DROMAJO=1
make run-dromajo-verilator BIN=/path/to/bin
```
As we had been discussing via email, this patch implements [dromajo](https://github.com/chipsalliance/dromajo) co-simulation flow that is depicted in the figure below.
1. Load the binary of interest into Dromajo.
2. Run Dromajo stand alone and let a couple of instructions to complete.
3. Dump the checkpoint. This is the whole architectural state of the reference model. Dromajo dumps the main and boot memories. In addition, it generates a boot code. If you were to run that code it will restore the whole architectural state. This means that you can bring any two or more cores into complete synced architectural state by running this piece …

co-simulation with dromajo

---

include/ariane_pkg.sv
src/cache_subsystem/wt_icache.sv

Hello, I have reviewed the code in wt_cache_subsystem.
It seems that a few mistakes are here.
* A word misspelling
* The address is align to 64bit, but not 32bit. Seems the comment was copied from the other case.

Tiny mistakes in wt_cache_subsystem

---

Makefile
tb/ariane_tb.sv

Fix the Modelsim simulation flow after the Dromajo integration (https://github.com/openhwgroup/cva6/commit/2d814452094b3e20897e2362771d70024a610651).

Modelsim: Fix simulation flow

---

docs/README.md

Because original README.md in docs folder is copied from https://github.com/aksakalli/jekyll-doc-theme. If we follow the command will build an example site provided by https://github.com/aksakalli/jekyll-doc-theme not ariane document sites.

docs: fix document build misleading instructions

---

src/mmu.sv
src/pmp/src/pmp.sv
src/pmp/src/pmp_entry.sv
src/ptw.sv

Currently, the PMP module works with 64-bit instead of 56-bit physical addresses. This results in undriven signals.

pmp.sv: change XLEN (64 bits) to PLEN (56 bits)

---

src/frontend/instr_queue.sv

This prevents an INSTR_ACCESS_FAULT to retire as an INSTR_PAGE_FAULT if `idx_ds_q=2'b01`.

instr_queue.sv: propagate INSTR_ACCESS_FAULT

---

Bender.yml
Makefile
fpga/src/ariane_regfile_fpga.sv

Add a register file, optimized for synthesis on FPGAs supporting
distributed RAM.
Principle:
The baseline implementation implements the register file as an array of
flip-flops and implements large multiplexers for read- and write-
accesses. On FPGAs, we have a more efficient implementation for data
storage: By using distributed RAM for memory storage, we can store up
to 64 bits in just one LUT (depending on the memory layout and FPGA
device). In addition, distributed RAM comes with integrated address
decoders. The register file features one distributed RAM block per
implemented sync write port, each with the parametrized number of
async read ports. The read access is arbitrated depending on which
block was last written to. For this purpose an additional array of
*NUM_WORDS* registers is …

Add FPGA Optimized Register File Version

---

src/frontend/frontend.sv
src/frontend/instr_queue.sv

Fixed wrong tval for instruction page fault exception when fetching the second half of a 4-byte instruction split across two pages.
This PR fixes issue #470

Fixed tval of misaligned 32-bit instr's page fault

---

tb/tb_wt_dcache/hdl/tb.sv
tb/tb_wt_dcache/hdl/tb_mem.sv
tb/tb_wt_dcache/wave.do

- update signal names in wave.do
- fix local imports
- do not invalidate memory while there is an outgoing read reply

tb_wb_dcache: small bugfixes

---

fpga/src/ariane_peripherals_xilinx.sv
fpga/src/ariane_xilinx.sv

Sorry for closing #510 by mistake.
I would like to fix these tiny bugs.
* the wire definition timer_irq is mis-spelling in ariane_xilinx.sv
* the s_axi_gpio_wlast from AXI master is not an input, but an output.
-

cva6: tiny bugs fixed

---

src/cache_subsystem/cache_ctrl.sv

This PR resolves two bugs within the write-back data cache controller. Specifically:
If we already issued a miss request and are waiting for the critical word to arrive when receiving a kill request, we want to wait for the miss handler to complete before returning to the `IDLE` state. Hence, when a miss request might be in-flight (we are in `WAIT_REFILL_GNT` or `WAIT_CRITICAL_WORD`, do not abort immediately but remember that the request was killed, and discard the critical word after it arrives.
The load unit can send the tag only after it has translated the virtual address. Depending on the state of the TLB and the time it takes to walk the page table, the tag may be available many cycles after the load request was issued to the cache. Therefore, the cache needs to wait for the …

cache_ctrl.sv: fix two bugs in WB data cache controller

---

src/cache_subsystem/wt_icache.sv

Remove redundant `TLB_MISS` state from icache FSM to
- reduce code size,
- decrease ITLB miss penalty by at least one cycle.

wt_icache: simplify FSM

---

src/cache_subsystem/wt_icache.sv

Oversaw one occurrence of `TLB_MISS` in https://github.com/openhwgroup/cva6/pull/531...

wt_icache: remove leftover from previous simplification

---

src/mmu.sv

`exception_t.tval` is `XLEN`, while `*_paddr` is only `PLEN` wide. This results in an overflow of `cause` into `tval` and wrong exception information. Therefore, zero-extend physical addresses when assigned to `lsu_exception_o.tval`.

mmu: zero-extend paddr to match tval width

---

src/csr_regfile.sv

This PR fixes the incorrect length of PMP csrs and enables 32bit compatibility for `pmpcfg` (see https://github.com/openhwgroup/cva6/pull/524#issuecomment-691944602).

Pmp 32 bit fixes

---

src/mmu.sv

Fix width of `pmpaddr_i`. Note that PMP address registers only encode bits `2` - `PLEN-1` of the physical address.

mmu: fix port width mismatch

---

fpga/scripts/write_cfgmem.tcl

write_cfgmem.tcl misses the creation of the mcs file if the kc705 board is selected. This patch adds this functionality.

Add mcs file generation for kc705 board

---

Makefile

With this modification, spike can be located in any directory.
By default, it is still located in RISCV directory.

Makefile: support spike not located in RISCV directory

---

src/ariane.sv
src/csr_regfile.sv
src/ex_stage.sv
src/frontend/frontend.sv
src/load_store_unit.sv
src/mmu.sv
src/ptw.sv

Hello @zarubaf, 
The Synopsys dc_shell LINT creates errors when reading the code, modifications have been done on the following nets:
- rs1_forwarding
- rs2_forwarding
- pmp_addr
- boot_addr
- icache_vaddr
- vaddr_to_be_flushed
- dtlb_ppn
- vaddr_vpn2_match
Kind regards

Fix the lint warnings which create errors in ASIC synthesis tool

---

tb/ariane_testharness.sv

Static casts cause a compilation error with `Verilator 4.109`

Fixed an issue: Installation of cva6 #567

---

README.md
src/util/sram.sv
tb/ariane_tb.cpp

Theoretically fixes #583, but I can't bring the simulation to run for both `verilator-4.106` and `verilator-4.108/9`. I've noted this in the `README.md`. At this stage, I believe this is a problem with Verilator and I would prefer to wait for a couple more releases until investigating for a fix in the RTL. 
@TarekIbnZiad I can confirm successful compilation and simulation with `verilator-4.104`, does that work for you?

Verilator: Dot reference compilation issue (fix #583)

---

src/frontend/instr_queue.sv

Using CVA6 as an IP in Vivado 2018.2, a latch was inferred durring OOC synthesis.
Signed-off-by: Luca Zulberti <zulberti.luca@gmail.com>

instr_queue: Prevent latch inference in always_comb

---

src/axi_adapter.sv
src/axi_shim.sv

The AXI transactions can be _regular_ as stated in AXI specification section A3.4.3.
It seems there is no need to perform FIXED transactions, am I wrong?
This patch makes the CPU compliant also with _AXI Regular Transactions_. For example, now it is compatible with the AXI SmartConnect IP of Vivado.
I have created a draft PR since I have not tested this patch a lot. Do you have any concerns about this change?

axi_adapter/shim: no need to have the fixed burst type

---

src/cache_subsystem/cache_ctrl.sv

DesignCompiler 2019.12 reports it as a possible error in future versions.

cache_ctrl: remove forward reference

---

fpga/Makefile
fpga/scripts/run.tcl
fpga/xilinx/common.mk

Since Vivado 2020.2 one can not relocate the `xci` files.

fpga: Fix IP synthesis for Vivado 2020.2

---

src/util/instr_tracer.sv

This PR ensures that while the CPU reset is asserted, the simulation instruction tracer flushes its internal state, so that it can resume tracing correctly once reset is deasserted. Otherwise the trace logging becomes inconsistent with the actual CPU state if the CPU is ever reset externally and then resumes execution.

Flush all state when reset is not deasserted

---

.travis.yml
Makefile

This PR primarily fixed the following problems in the verilator target:
1.  The verilator version test did not work correctly on our
System (Ubuntu 18.04). The verilator model was always
single-threaded before the change.
2.  From our experiments, 4 threads is a better pick than 2 threads.
On our workstation with i7-7700, running verilator model with
4 threads use about 60% of wall time of the case in 2 threads, and
more threads are having diminishing returns. On our server,
8 threads are slower than 4 threads.
3.  The original Makefile did not add optimization flags to verilator
output. Adding the optimization flag makes building the verilator
target significantly slower (>=10 mins) but makes the simulation
significantly faster.
4.  The VL_DEBUG macro is added to the CFLAGS of the …

Fixed multithreading and optimization options for verilator target

---

Bender.yml
Flist.ariane
Makefile
tb/ariane_axi_soc_pkg.sv
tb/ariane_testharness.sv
tb/tb_wb_dcache/tb.list

With my work, I had the necessity to remove the dependency of ariane_soc package from the CVA6 core.
It was straightforward because *_slv_t types are needed only in ariane_testharness.
I'm not familiar with your build system (Bender, etc..) and I'm not sure this is the best solution to be maintained.
If you are interested in isolating better the code of CVA6 from the SoC where it is instantiated, this patch aims to obtain this result.
Draft until interested and improved.

Remove unnecessary ariane_soc_pkg dependency

---

include/ariane_pkg.sv
include/riscv_pkg.sv
src/csr_regfile.sv
src/pmp/src/pmp.sv

**List of Error Fixed for xrun command:**
* In `ariane_pkg.sv` and `riscv_pkg.sv` the slicing of an enumeration constant is illegal for xcelium. The size of `MODE_SV` has been fixed to the size of `vm_mode_t` which removes the need for slicing;
* In `pmp.sv` assigning the port `conf_addr_prev_i ` of `pmp_entry` with a ternary operator caused an error. The assignment has been done outside the `pmp_entry` module.
**Warnings:**
* In `ariane_pkg.sv` removed extra semicolons at the end of endfunctions.
Signed-off-by: Gianmarco Ottavi <gianmarco@openhwgroup.org>

Added fixes for Errors/Warnings for compiling with xcelium on CVA6

---

fpga/src/ariane_peripherals_xilinx.sv
tb/ariane_peripherals.sv

Otherwise, the PLIC registers will be poisoned.

peripherals: assign default value to unused interrupts

---

include/riscv_pkg.sv
src/csr_regfile.sv
tb/ariane_testharness.sv

fixes issues with the modelsim flow introduced by recent commits.
* `riscv_pkg`, `csr_regfile`: explicit typecast of `satp.mode` to `vm_mode_t`
* `ariane_testharness`: `axi_adapter.type_i` is of type `ariane_axi::ad_req_t`

fix modelsim flow

---

.gitignore
Makefile

Added rules for compiling and running tests on xcelium following similar pattern to Questasim rules.
Signed-off-by: Gianmarco Ottavi <gianmarco@openhwgroup.org>

Added rules for compiling and running tests on xcelium

---

include/riscv_pkg.sv
src/pmp/src/pmp.sv
src/scoreboard.sv
src/util/instr_tracer.sv

- The PMP generation was causing troubles.
- The UVM tracer information isn't really needed
- Make `mem_q` in the scoreboard a proper type

vcs: Compatibility improvements

---

Makefile

Remove the static `vsim -do` argument for target `sim`. This argument takes precedence over `questa-cmd` (which defines the desired `-do` sequence) and seems to be an artifact from https://github.com/openhwgroup/cva6/commit/296ce392113003533af863518b29114b9953d836. It results in a batch-like behavior for questasim simulations in GUI mode - in particular closing QuestaSim immediately after terminating the simulation.

Makefile: Remove excess questa cmd for target sim

---

Makefile

There was a typo in https://github.com/openhwgroup/cva6/commit/4abae602c57045a2c89147a2c9c2cc47eab8fc14 which indents the Makefile with spaces instead of tabs. Sorry for the spam.

Makefile: Fix whitespace

---

src/ptw.sv

Instead of waiting for the dcache request to complete and then to discard the result, kill it and directly return to the `IDLE` state.
This prevents pollution of the data cache and makes the ptw (and dcache) faster ready for new requests.

ptw: Kill pending dcache request when flushed #2

---

include/riscv_pkg.sv

Some tools such as sv2v have some difficulties to deal with these redundant prefixes `riscv::` in the _include/riscv_ package. For instance,sv2v treats these as circular package dependency. Since they bring nothing, it may be useful to remove them.

:wastebasket: Remove redundant prefix in riscv_pkg

---

src/ariane.sv

The string in this block is restrained to one letter. Using a byte (also displayable using `%s`) instead makes some tools' life easier, and makes it arguably more readable.

src/ariane.sv: Verilator: change single-letter string to byte

---

src/cache_subsystem/wt_cache_subsystem.sv

If the tag request is being killed it might be the case that the
cache's SRAM macros return an unkown value. As the value will never be
saved anywhere the assertion triggering just produces noise.

wt_cache: Fix unknown assertion condition

---

src/cache_subsystem/cva6_icache.sv

@suehtamacv encountered this unexpected behavior. The current implementation resets the icache FSM to `IDLE`, where the icache checks if it was just enabled (rising edge of `en_i`), and flushes (initialises) itself if so. This assumes that `en_i` is deasserted during reset, which is not necessarily the case (e.g. hardwired `en_i`), possibly leaving the cache uninitialised. Hence, reset to `FLUSH` directly.

icache: Reset FSM to FLUSH

---

Makefile
README.md

This PR updates the Makefile so that the `make verilate` target compiles the apu and the core.

Compile corev_apu

---

src/load_store_unit.sv

The lsu_bypass module interface has inappropriate name.
**lus:load unit store???** 
**lus_req_valid_i** >>> **lsu_req_valid_i**

:pencil2: load_store_unit: Modify interface name

---

Bender.yml
Makefile
include/ariane_pkg.sv
include/wt_cache_pkg.sv
src/cache_subsystem/cva6_icache.sv
src/cache_subsystem/wt_axi_adapter.sv
src/cache_subsystem/wt_dcache_missunit.sv

The current replacement policy prevented to have a configurable cache size and associativity. Instead, I replaced it with the Galois LFSR present in common_cells.

Make the cache size and assoc configurable

---

ci/build-riscv-tests.sh
ci/riscv-benchmarks.list
src/csr_regfile.sv

- Add proper granularity (G=1)
- Disallow NA4
- Fix read of pmpaddr
- Bump riscv-tests to support pmp benchmark that detects granularity (https://github.com/riscv/riscv-tests/pull/295)
- Add PMP benchmark to CI
Fixes #538 
Fixes #697

pmp: Fix csr

---

src/csr_regfile.sv

- PMPCFG.A=NA4 not allowed
- access allowed in S/U mode when no PMP is configured (from the specs: if no PMP entry matches an S-mode or U-mode access, but at least one PMP entry is implemented, the access fails)
Note: the new signal between the commit_stage and the csr_registers is necessary to remove the combinatorial loop
update_access_exception → csr_regfile_i/csr_exception_o → csr_exception_csr_commit → commit_stage_i/csr_exception_i → commit_stage_i/exception_o → commit_stage_i/csr_wdata_o[4] → csr_wdata_commit_csr[4] → csr_regfile_i/csr_wdata_i[4] → update_access_exception

PMP improvement

---

src/decoder.sv

As stated in the issue https://github.com/openhwgroup/cva6/issues/719 the immediate field should be ignored for FENCE.I which isn't in the master (the spec also states that standard software should zero out those fields so that's probably why it went unnoticed) (line 234,235).
For issue https://github.com/openhwgroup/cva6/issues/720 I just added the else on the default case which will result into an illegal instruction if no match in the cases are found (line 163, 164).
Signed-off-by: Gianmarco Ottavi <gianmarco@openhwgroup.org>

Fixes for issues #719, #720

---

corev_apu/tb/ariane_testharness.sv

Update the port list of ariane's instantiation according to its definition:
https://github.com/openhwgroup/cva6/blob/3ddf797e95923fd11113c8e443046105dfbf8843/core/ariane.sv#L45-L49

ariane_testharness: Fix ariane port list

---

core/Flist.cv32a6_imac_sv0
core/Flist.cv64a6_imafdc_sv39

Fix Flist.cv64a6_imafdc_sv39 by removing files related to mmu as they are now in another place.
Without this fix, any build based on such flist fails.

Fix build after mmu reorg

---

README.md
ci/install-riscvpk.sh
ci/setup.sh

This PR aims to simplify the installation process by extending the documentation and by adding additional installation scripts (as discussed with @niwis, @bluewww, @micprog):
- add tutorial on how to use the already existing ci scripts to install the required tools for verilator software simulation
- add RISC-V proxy kernel and bootloader installation script
- removal of $ signs in commands: allows to copy and paste commands from the `README.md` file to the command line

Add detailed simulation flow installation info & helper scripts

---

Makefile
core/include/riscv_pkg.sv

Fix the VCS flow for 64-bit CVA6 by guarding incompatible MMU implementations. For instance, `mmu_sv32` assumes `PLEN` > `VLEN`, which is not the case for RV64.
Example:
https://github.com/openhwgroup/cva6/blob/720b59e2ca6e002b9b3a2c47ed4ad85b847978a3/src/mmu_sv32/cva6_mmu_sv32.sv#L212
causes for 64-bit CVA6:
```
(vlog-8607) Negative replication multiplier (-8)
```

mmu: Prevent elaboration of incompatible MMU version

---

core/cache_subsystem/wt_dcache_ctrl.sv
core/cache_subsystem/wt_dcache_mem.sv
core/cache_subsystem/wt_dcache_wbuffer.sv
core/include/wt_cache_pkg.sv

width of wtag in wbuffer_t should be PLEN-3, or DCACHE_TAG_WIDTH+DCACHE_INDEX_WIDTH-3.
width of wbuffer_cmp_addr should be PLEN.
width of the second param of is_inside_*_regions should be 64bits.
'cause of the reorgnizaiton of cva6, I can't fix conflicts of last pr #728, so I open a new pr.

Fixes some width in wt_dcache.

---

corev_apu/tb/ariane_tb.sv
corev_apu/tb/dpi/elfloader.cc

As read_section does not return any value, return type is void.
VCS generates segmentation fault when preloading elf without this fix. Related to issue #514.

elfloader.cc: change read_section prototype

---

core/csr_regfile.sv

This PR addresses issue #321.
The current revision of the RISC-V Priviliged ISA specification states:
> The operation of WFI must be unaffected by the global interrupt bits in mstatus (MIE and SIE) [...], but should honor the individual interrupt enables (e.g, MTIE) (i.e., implementations should avoid resuming the hart if the interrupt is pending but
not individually enabled).
This behaviour is not mandatory but it is suggested (could we say also intuitive?).
Furthermore it would have positive implications on power.
Suppose the core is stalled on a WFI. Suppose timer interrupts are disabled, as we are expecting a SW interrupt to resume the hart. By specification, a timer interrupt will eventually become pending, and if this condition occurs before the SW interrupt arrives, the hart will …

Mask non-enabled interrupts in WFI control

---

Makefile

Makefile: Fix Verilator random bugs by setting verilator thread to one thread

---

corev_apu/tb/ariane_tb.sv

It is related to #767 pullreq. The prototype of 'read_section' function should return explicitly void in SV side.
What is more issue #514 should be closed.

Explicit void type should be used for read_section function.

---

Makefile
core/cache_subsystem/miss_handler.sv

Hello,
I added some support for vcs :
- moved vcs work files to a work directory.
- added debug options to vcs compilation to use VERDI.
- enable preloading for vcs and disable debug because it was reloading memory.
- made explicit the connection for critical_word in miss_handler, it was raising an error for vcs when using 32bit configuration.
Memory preloading makes simulation faster.

Add Verdi option and memory preloading for VCS simulator

---

core/Flist.cv64a6_imafdc_sv39_gate

Move Flist dedicated to the gate simulation from core-v-verif to cva6 repository.
LIB_VERILOG need to point to the verilog foundry library

Flist.cv64a6_imafdc_sv39_gate: Flist dedicated to gate simulation

---

Makefile
README.md
core/Flist.cv32a6_imac_sv32
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv64a6_imacfd_sv39_config_pkg.sv
core/include/riscv_pkg.sv

Following @nathpranay issue, I updated release 4.3 to ease cv32a6 release.

update make fpga variant=32 to support linux 32b

---

core/cache_subsystem/cache_ctrl.sv
core/cache_subsystem/std_cache_subsystem.sv
core/cache_subsystem/std_nbdcache.sv
core/cache_subsystem/std_no_dcache.sv

Check the cacheable region's length and support multiple cached regions in Ariane's write-back cache.
Based on https://github.com/pulp-platform/snitch/commit/0f10b4b2fbbf2233cb113e6fe8054bf85ab2d40e

wb: Check cacheable region length

---

Makefile

The `make clean` target of the root `Makefile` does not always properly clean the `make fpga` target (i.e. to rebuild the fpga image, `make clean && make fpga` sometimes (depending on the files existing from the previous build) does not rebuild the image.
This PR calls the `make clean` of the `corev_apu/fpga/Makefile` to ensure proper cleanup.
Log
```
andreas@dev-pc:~/cva6$ make clean                                                                                                                                                                                                                                                                                                    │·······························
Makefile:153: XCELIUM_HOME not set which is necessary for compiling DPIs when using …
```

Add fpga cleanup to make clean target

---

corev_apu/fpga/src/ariane_xilinx.sv

**Issue**
On FPGA, Ariane deadlocks immediately after loading the bitstream while attempting to fetch from bootrom.
**Methodology**
Hundreds of ILA probes in and around the crossbar.
**Solution**
Fix the name of the clock net provided to the crossbar.

ariane_xilinx: Fix xbar clock

---

core/Flist.cv64a6_imafdc_sv39_gate

Modification on the flist gate "Flist.cv64a6_imafdc_sv39_gate" to clean post synthesis simulation jobs.
Most of the time the tech files are in a fixed path on the server and not relative to the project. With the current prefix this forced us to do a workaround.

Flist.cv64a6_imafdc_sv39_gate, update LIB_VERILOG path

---

core/scoreboard.sv

The scoreboard issue counter `issue_cnt_q` and `issue_cnt_n` have length equal to `log2(NUM_ENTRIES) - 1` where `NUM_ENTRIES` is the number of scoreboard entries. In the standard case where `NUM_ENTRIES = 8` the counters are 3 bits long meaning that they can count from 0 to 7 making it impossible to use the full scoreboard (always leaving one spot free).

Fixed issue counter in order to leverage the full scoreboad length.

---

.gitlab-ci.yml
.gitlab-ci/cva6.yml

new CI for gitlab massively generic to allow each group to be able to use it directly without modifications in the CI source code regardless of their runtime environment.
Adaptations to the environment are done only in the settings of the projects. (paths of tools, version of tools, urls of repositories to use...)
The CI launch 2 downstream pipelines:
CVA6 : the CI previously describes in .gitlab-ci.yml (not used anymore I understand?)
CORE-V-VERIF: a new CI based on core-v-verif environment
**trial in test branch "feature/gitlab-ci" see : #797**

Add continuous integration for gitlab-ci

---

Makefile

Simulating the current master with Questasim leads to errors due to `cvxif_example` being enabled, but the sources are missing in the Makefile. This PR fixes that.

Add missing sources for questa simulation

---

core/include/ariane_pkg.sv
corev_apu/tb/tb_cva6_icache/tb.list
corev_apu/tb/tb_wb_dcache/Makefile
corev_apu/tb/tb_wb_dcache/hdl/tb.sv
corev_apu/tb/tb_wt_dcache/Makefile

Due to recent changes, the modular cache test benches are unable to run. Fix them by
- updating the parameter interface of `std_nbdcache`,
- updating the dependencies and include directories,
- preventing an overflow during `range_check`.

tb/cache: Fix regressions

---

core/csr_regfile.sv

Fix illegal write to PMPCFG. Reported by Flavien Solt (@flaviens)
Supersedes #820 
I also found a way to simplify and clarify the code for the CSR read and write of PMPADDR. Should be functionally the same as before.

Fix reserved CSR write

---

Makefile

Add `register_interface/include` to vcs `incir` due to PR #819 @JeanRochCoulon

Makefile: Add register_interface/include directory to vcs compile option (fix #819)

---

pd/synth/cva6_synth.tcl

Added missing hierarchy (`i_cva6`) in cva6_synth.tcl to fix synthesis script.
Signed-off-by: Guillaume Chauvon <guillaume.chauvon@thalesgroup.com>
@JeanRochCoulon can you review this ?

cva6_synth.tcl: add missing hierarchy in synthesis script.

---

Bender.yml
Makefile
core/axi_adapter.sv
core/cache_subsystem/miss_handler.sv
core/include/std_cache_pkg.sv
corev_apu/fpga/src/ariane_xilinx.sv
corev_apu/tb/ariane_testharness.sv
corev_apu/tb/tb_wb_dcache/hdl/tb.sv
corev_apu/tb/tb_wb_dcache/hdl/tb_amoport.sv
corev_apu/tb/tb_wb_dcache/tb.list

This PR removes handling of atomic operations inside the WB cache. It forwards them instead on the AXI bypass interface, to be handled closer to memory. 
_Swap_, _fetch-and-op_ and _op_ type atomics are presented on the interface as AXI5 "Atomic Transactions".
_Load-reserved_ and _store-conditional_ are presented on the interface as AXI4 "Exclusive accesses".
This is aligned to how atomics are expected in the [_riscv_axi_atomics_](https://github.com/pulp-platform/axi_riscv_atomics) module.
Miss-hander FSM updated. AXI adapter extended to present AXI5 "Atomic transactions" requests and handle respective responses. 
A _riscv_axi_atomics_ module is instantiated and connected between the DUT and the TB memory to handle atomics. The ensemble of the two modules should equal the previous DUT in …

wb_dcache: Forward "atomic transactions" to AXI

---

core/include/ariane_pkg.sv

Hello,
A simple fix for `ariane_pkg::LOG2_INSTR_PER_FETCH`. It should equal 1 not 0 when RVC is disable.
@JeanRochCoulon  can you review that ?
Guillaume

FIX : LOG2_INSTR_PER_FETCH when RVC is disable

---

config_pkg_generator.py

Hello,
I have written a python script to generate custom configuration from one of the existing four ( cv32_...._config_pkg, etc...).
This script allows us at Thales to run regression on specific configuration to make sure new commits do not break features which are not in our four configuration. 
Examples: Check that we can still disable X-interface or FPU in 64 bits, activate user bits etc... 
Each parameter can be modified ( in the limit of possible values ) except for the `xlen` parameter.
A mandatory `--isa` parameter is required to make sure code is compiled with the right ISA. If FPU is disable, the CVA6 should not run a code with F or D extension. 
**Note**: --isa is not used to create new configuration but is returned by the script to be used to compile code. It is necessary to …

Add script to generate custom configuration

---

core/cva6.sv

Change the rvfi_exception signal from `commit_instr_id_commit` to `ex_commit` to detect and report CSR exception.

cva6.sv: rvfi change exception signal

---

corev_apu/fpga/Makefile
corev_apu/fpga/scripts/check_fpga_boot.sh
corev_apu/fpga/scripts/linux_boot.py
corev_apu/fpga/scripts/program_genesys2.tcl

Add 3 scripts to check linux boot on FPGA using Vivado. 
- `check_fpga_boot.sh`: Top script, check that `VIVADO_CMD` is set and `BITSTREAM `exist before programming and checking linux boot.
- `program_genesys2.tcl`: Vivado tcl script to program fpga connected to an `HW_SERVER`
- `linux_boot.py`: python script that reads `UART_SERIAL` and check that linux boot successfully.
All those scripts are used by an incoming PR in core-v-verif that creates a job in Thales-CI and is integrated to Thales Dashboard
@JeanRochCoulon @yanicasa Can you look at this ?

FPGA: Add scripts to check linux boot linux on fpga

---

core/include/cv32a60x_config_pkg.sv
core/re_name.sv

Enable X-interface in cv32a60x package
Enable renaming for cvxif when using 3 operands
@JeanRochCoulon can you look at this ?

Enable CVXIF for target cv32a60X and add renaming for cvxif when using 3 operands

---

core/decoder.sv

from https://github.com/openhwgroup/cva6/issues/900, this patch passed the testcase in the report.
As specification suggests: `For forward compatibility, base implementations shall ignore these fields, and standard software shall zero these fields`, remove the check on related fields.

fix fence(.i) decoder

---

core/decoder.sv

from https://github.com/openhwgroup/cva6/issues/899, this patch passed the testcase in the report.
debug mode check reset the illegal_instr signal, use its previous value instead of 0.

fix dret decoder

---

core/decoder.sv

from https://github.com/openhwgroup/cva6/issues/876, this patch passed the testcase in the report.
The original design reset the illegal_instr during privilege check, use the previous value instead 0.

fix sfence.vma decoder

---

core/mmu_sv39/mmu.sv

Fixes #906
According to the spec:
> If accessing pte violates a PMA or PMP check, raise an access-fault
> exception corresponding to the original access type.
Found by @Phantom1003 and @ProjectDimlight
Signed-off-by: Moritz Schneider <moritz.schneider@inf.ethz.ch>

Fix exception type on PMP check during PTW

---

core/decoder.sv

Hello,
Related to  PR #921 and issue #876. @Phantom1003 you might want to check this. 
Unlike other instructions with minor opcode == PRIV (000), SFENCE.VMA do not check for rs1 != 0.
Illegal instruction happens if  : 
- rd !=0
-  privilege mode not in S or M.
The solution I propose check for rd != 0 which should solved the issue raised in #876. 
It also reset the illegal instruction flag to 0 in case it has been raised in the if case below :
https://github.com/openhwgroup/cva6/blob/56ccf8089e80e5c7950038cad5796e50c64aa0c2/core/decoder.sv#L99-L103

decoder.sv: fix sfence.vma when rs1 != 0

---

core/multiplier.sv

Hey @zarubaf, @JeanRochCoulon 
As mentioned in [issue#863](https://github.com/openhwgroup/cva6/issues/863), the following two lines are not being used in the entire module, so they seem to be redundant:
```
logic [riscv::XLEN*2-1:0] mult_result;
assign mult_result   = $signed({operand_a_i[riscv::XLEN-1] & sign_a, operand_a_i}) * 
$signed({operand_b_i[riscv::XLEN-1] & sign_b, operand_b_i});
```
Moreover, the RTL of the line [number#49](https://github.com/openhwgroup/cva6/blob/2c3d0f741d5d7ce55b06181a417280bfae499583/core/multiplier.sv#L49) is similar to the one in line [number#72](https://github.com/openhwgroup/cva6/blob/2c3d0f741d5d7ce55b06181a417280bfae499583/core/multiplier.sv#L72), as shown below:
```
assign mult_result_d   = $signed({operand_a_i[riscv::XLEN-1] & sign_a, operand_a_i}) …
```

Remove redundant RTL from multiplier file

---

core/decoder.sv

Default case is missing for unique-case when BITMANIP is enable.

decoder: add missing default case for BITMANIP

---

core/cvxif_fu.sv

Hello,
We encountered an issue when illegal instruction were offloaded to CVXIF the same cycle CVXIF sent back result from a previous custom instruction. Illegal instruction was prioritized over the result instruction. The CVA6 would then stall infinitely waiting for this custom instruction result which would never come.
The solution I propose add a register to hold illegal instruction information so we raise the illegal instruction once the CVXIF's result interface is not valid anymore.
Guillaume.

cvxif_fu.sv: add register to hold illegal instruction information

---

core/perf_counters.sv

see The RISC-V Instruction Set Manual Volume II: Privileged Architecture
Version 20211203
3.1.1 Hardware Performance Monitor
All counters should be implemented, but a legal implementation is to make
both the counter and its corresponding event selector be read-only 0.

perf_counters.sv: unimplemented mhpmcounters shall be read-only 0

---

core/Flist.cv32a60x_gate
pd/synth/Makefile
pd/synth/cva6_synth.tcl
pd/synth/scripts/dc_setup.tcl
pd/synth/scripts/dc_setup_filenames.tcl
pd/synth/tc_sram_wrapper_256_64_00000008_00000001_00000001_none_0.sv

core/Flist.cv32a60x: [NEW] Add Flist for gate simulation with cv32a60x configuration
core/Flist.cv64a6_imafdc_sv39: Update to support uvm testbench
match $DESIGN_NAME variable in Makefile
pd/synth/Makefile: Add $TARGET variable to chose which config to synthetise
Change DESIGN_NAME to cva6 module so it is the top module
pd/synth/cva6_synth.tcl: Update to match new topmodule
pd/synth/dc_setup.tcl;dc_setup_filenames.tcl: Uptade to match new path with $TARGET
pd/synth/tc_sram_wrapper_...sv: Add a copy of tc_sram with specific parameters to replace tc_sram in netlist
@JeanRochCoulon @yanicasa can you look at that ?

Update to synthesis and simulation gate flow

---

core/perf_counters.sv

Comparing a logic vector to an enum causes some tools (e.g. Questasim) to throw a mismatch error. Fix this by explicitly typecasting.

perf_counters: Explicit typecast for comparison

---

core/compressed_decoder.sv
core/include/riscv_pkg.sv

This PR provides a proposed fix to issue #956.  It adds RV32-specific decompression of compressed L/S instructions that have different meaning on RV32C and RV64C.
Files changed:
* core/compressed_decoder.sv: Use word L/S patterns in FLW/FSW/FLWSP/FSWSP expansions on RV32C.
Signed-off-by: Zbigniew Chamski <zbigniew.chamski@thalesgroup.com>

compressed_decoder.sv: Fix FP word L/S decompression as per ISA spec v2.2.

---

Makefile
corev_apu/tb/ariane_tb.cpp

This PR supports `core-v-verif` PR https://github.com/openhwgroup/core-v-verif/pull/1427 which unifies the control of waveform generation between VCS and Verilator simulation targets.  It supersedes PR #954 and PR #963 in order to reduce the change set and simplify history.
For VCS configurations, the control of trace generation is handled entirely at the level of VCS and `vsim` invocations in `core-v-verif/cva6/sim/Makefile` (see PR https://github.com/openhwgroup/core-v-verif/pull/1427).
For Verilator, the control of trace generation is partially implemented in the C++ simulation wrapper (cf. file `corev_apu/tb/ariane_tb.cpp`) according to the settings of two C++ macros: `VM_TRACE` and `VM_TRACE_FST`.  Due to current limitations of Verilator, the VCD and FST waveform formats cannot be …

[tracing] Uniformize VCS and Verilator support of waveform dumps.

---

docs/specifications/cva6_requirement_specification.rst

To ease the implementation. As we'll target FPGA and ASIC (not ASSP), we do not need a "one size fits all" solution.

Scratchpad can also be separate from caches

---

core/Flist.cv32a60x

Needed by core-v-verif  uvm  testbenchdue to ariane.sv depedencies

Flist.cv32a60x: add example coprocessor to Flist

---

Makefile

Modification has been verified for VCS (Synopsys) simulation, Verilator simulation and FPGA build.
Modifications have been also done for XRUN and Questa, but without verification because I do not own this type of licence. @MikeOpenHWGroup do you know someone able to try to simulate with such tools ?

Use unique Flist for testharness and UVM

---

core/Flist.cva6
core/frontend/btb.sv
core/frontend/frontend.sv
core/include/ariane_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv

Hello @JeanRochCoulon @zarubaf 
- BTB module adapted for FPGA targets, predictable adresses are stored in BRAM for FPGA and in D flip-flops for ASIC Targets.
- Flushing is not supported for FPGA.
I re-submit a PR to resolve conflicts due to latest modifications these last days.
Can this PR be merged quickly to avoid possible conflicts?

add btb optimized for FPGA targets

---

config_pkg_generator.py

Add graceful handling of config parameters which have no matching command line arg yet.  Adapt script operation to handle the simplified Flist structure.
Signed-off-by: Zbigniew Chamski <zbigniew.chamski@thalesgroup.com>

[config _pkg_generator.py] Gracefully handle new config parameters.

---

.gitmodules
corev_apu/fpga/scripts/run.tcl

Some submodules were vendored in #1015. Remove those submodules, as they are no longer used.

Remove unused submodules

---

Makefile
corev_apu/tb/ariane_testharness.sv

This PR contains the following two fixes from #988:
1. Fix width mismatch in `ariane_testharness` by propagating the `AXI_USER_WIDTH` from `ariane_testharness` to `ariane_peripherals`
2. Fix the compilation order for Questasim (#1008).

tb: Fix port width mismatch and compile order

---

Makefile

Propagate the CFLAGS and CXXFLAGS specified in the environment executing the Makefile for DPI compilation. By default, the current CFLAGS are extended by the CFLAGS from the environment.

Makefile: Propagate CFLAGS from env

---

config_pkg_generator.py

It was printing "setting xxx to yyy" but not modifying the line in the file for some values. Now it works properly.
I reworked the code until I found the issue, so it is possible to reduce the "diff to fix" if needed. Also I do not really understand why it was working for some lines but not all.

fix: improve stability of config_pkg_generator

---

core/include/ariane_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv

Required by #1024.
With this change, different CVA6 configurations can define different cache layouts in their respective `cva6_config_pkg`.

ariane_pkg: Parametrise cache layout

---

corev_apu/bootrom/gen_rom.py
corev_apu/fpga/src/bootrom/Makefile

The makefile target to generate the bootrom system verilog assumes a python2 binary behind the python environment call. Python2 is not the default anymore on many systems.
This solves issue #1086.

Bootrom.sv : upgraded to python 3

---

core/ariane.sv

Required by #1024.
(Optionally) expose the AXI parameters of `cva6` from the `ariane` wrapper.

ariane.sv: Propagate AXI parameters

---

core/include/ariane_pkg.sv

Required by #1024 
In the current implementation, `AXI_USER_WIDTH` equals 2 (`FETCH_USER_WIDTH*2`) if `AXI_USER_EN` is false. This causes unexpected port width mismatches when the user signal is disabled.

ariane_pkg: Set AXI_USER_WIDTH to 1 if disabled

---

core/csr_regfile.sv
docs/01_cva6_user/PMP.rst

As requested here is the PMP section for the user guide, plus a fix for the CSRs for CV64A6 which should trap on PMP access `CSR_PMPCFG1` and `CSR_PMPCFG3`. 
Fixes #1095

Add PMP section and fix addressing CV64A6

---

pd/synth/Makefile

This PR enables the synthesis of RVFI_MEM support which was missing in gate synthesis configuration.  As a consequence, the RVFI tracer module could not see memory-related events when attached to gate-level models.

pd/synth/Makefile: Enable RVFI_MEM support at gate level.

---

core/axi_shim.sv
corev_apu/tb/axi_adapter.sv

The `modifiable` bit of `ax.cache` indicates whether an AXI transaction can be changed downstream (e.g. split, merged, etc.). This is needed by several AXI IPs.
Based on https://github.com/pulp-platform/snitch/pull/96 and https://github.com/pulp-platform/snitch/pull/231.

Make AXI transactions modifiable

---

corev_apu/tb/rvfi_tracer.sv

Fix the width of `tohost` address representation in `rvfi_tracer.sv` to match the width of the RVFI `mem_paddr` field:
* in 64b mode physical addresses are 56 bits wide (PLEN == 56);
* in 32b mode physical addresses are 34 bits wide (PLEN == 34), meaning that they are wider than XLEN.
This modification is intended to resolve the failures in gate simulations seen with the original test termination PR (#1075) in both 32 and 64 bit configurations.
To keep the code clean, this PR makes `TOHOST_ADDRESS` always `PLEN` bits wide, forcing the correct bit width in the conversion of the corresponding *plusarg*.

rvfi_tracer.sv: Use correct width for 'tohost' address.

---

.github/workflows/ci.yml
.gitlab-ci/cva6.yml
Bender.yml
Makefile
README.md
core/Flist.cva6
core/cache_subsystem/axi_adapter.sv
core/cache_subsystem/wt_cache_subsystem.sv
core/controller.sv
core/cva6.sv
core/include/ariane_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
corev_apu/fpga/src/genesysii.svh
corev_apu/fpga/src/kc705.svh
corev_apu/fpga/src/vc707.svh
pd/synth/Makefile

Cache WT or WB was configured by a define.
#603 requests more description of it
#483 tells to not use define
#1122 reports a bug: WB is never used/verified
To solve these issues, WT_DCACHE define has been replaced by CVA6ConfigCacheType localparam
In GitHub Actions CI, cv32a6_imafc_sv32 has been added, this configuration implements WB.

Replace WT_DCACHE define by CVA6ConfigCacheType localparam

---

corev_apu/tb/ariane_tb.cpp
corev_apu/tb/ariane_testharness.sv
corev_apu/tb/rvfi_tracer.sv

This PR replaces explicit use of `$finish()` in RVFI tracer with proper propagation of end-of-test information to the verification testbench:
* Instread of executing a `$finish()` statement the RFVI tracer now outputs the end-of-test event and the test exit code on new output `end_of_test_o`.
* The Verilator and VCS C++ testbenches were modified to detect the end-of-test event (write of `1'b1` into bit 0 of memory variable `tohost`) and to report the exit code of the test (bits [31:1] of the word written into `tohost` upon end-of-test).  The Verilator testbench end-of-test messages were aligned on those of the VCS testbench.
* The UVM handling of the end-of-test is implemented in the companion core-v-verif PR https://github.com/openhwgroup/core-v-verif/pull/1729.
Once the end-of-test …

Test termination: Delegate decision to testbench instead of using explicit $finish.

---

core/cache_subsystem/cva6_icache.sv
core/include/ariane_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/wt_cache_pkg.sv

This new parameter in the CVA6 configuration packages defines the width of the transaction ID between the I/Dcaches and the interconnection interface.
It should be defined in global CVA6 packages and not in any specific implementation of a cache to ease the integration of different cache subsystems.
Current default value (before this PR) is 2 bits. I kept this value, then no increase in the area is expected.
@JeanRochCoulon, can you review these changes?
Thank you

Add parameter on config file to define the width of the memory transaction ID

---

core/include/ariane_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/riscv_pkg.sv
core/load_store_unit.sv

Make MMU configurable from config pkg. 
Today no configuration disables the MMU, but a new configuration dedicated to embedded applications will be defined in next PR.

Make MMU optional

---

Makefile
corev_apu/tb/ariane_tb.cpp

This PR provides transparent support for Verilator v4 and v5 at the Verilator C++ testbench level.
Appropriate headers and data structure accesses are selected depending on the value of C++ macro `VERILATOR_VERSION_INTEGER`:
* In Verilator v4 this macro is not defined and therefore, evaluates to 0 if used in arithmetic context.
* In Verilator v5 it takes a value that is greater or equal to 5 million (the formula is "major_version * 1000000 + minor_version * 1000 + patch_level".)
There is no need to force the `--no-timing` option to Verilator in the CVA6 Makefile.  Instead, an appropriate definition of the Makefile variable `verilator` can be provided by the `core-v-verif` infrastructure depending on the Verilator version used.

Transparently support Verilator v4 and v5.

---

core/cache_subsystem/cva6_icache_axi_wrapper.sv

Some tools struggle with the `$size` macro. Since we anyways have the `AxiIdWidth` parameter, it's cleaner to use that one directly.

icache_axi_wrapper: Use AxiIdWidth parameter

---

core/cache_subsystem/cva6_icache_axi_wrapper.sv

Fixes a port width mismatch for `AxiAddrWidth != 64`

icache_axi_wrapper: Use AxiAddrWidth parameter

---

core/include/ariane_axi_pkg.sv
core/include/ariane_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
corev_apu/tb/ariane_axi_soc_pkg.sv
corev_apu/tb/ariane_testharness.sv

The axi stuctures were declared twice in the RTL. This PR declare master structures in ariane_axi package and slave structures in ariane_axi_soc package. In parallel, the Ariane AXI configuration is done thanks to parameters declared in cva6 config.

Add AXI parameter in cva6 config, keep AXI master structs in ariane and slave in SOC

---

core/axi_shim.sv
core/csr_regfile.sv
core/issue_read_operands.sv
core/load_unit.sv
core/scoreboard.sv
core/store_buffer.sv

Goal: remove all `ifndef VERILATOR` directives that disabled Verilog assertions when using Verilator v4 and below (cf. issue https://github.com/openhwgroup/cva6/issues/1180).

Enable assertions in Verilator after migrating to Verilator v5, part 1: core/*.sv

---

Bender.yml

Hi there!
It looks like Bender.yml references the wrong path to ariane.sv.
EDIT: Maybe you want to move it to the (commented) test section.
Thanks!
Flavien

Fix reference to ariane.sv in Bender.yml

---

Bender.yml

Hi there!
This PR intends to fix 2 things
a) Fix the path to the rvfi package sv file.
b) Enforce the correct dependency order between packages.
Thanks!
Flavien

Bender.yml: Correct path and location of rvfi_pkg

---

CONTRIBUTING.md

This update follows the CVA6 meeting on 2023-04-18. We thought the emoji tagging was deprecated and labels should be emphasized.

[SkipCI] CONTRIBUTING.md: replace emoji with GitHub labels

---

docs/01_cva6_user/Programmer_View.rst

Fix satp spelling in documentation

---

.github/workflows/bender-up-to-date.yml

To check if `Bender.yml` is up-to-date.
As expected, the workflow fails due to
```
bender-up-to-date: /home/runner/work/cva6/cva6/core/include/ariane_rvfi_pkg.sv not found.
bender-up-to-date: /home/runner/work/cva6/cva6/core/ariane.sv not found.
```
This will be resolved in #1189 and #1190, after which I will rebase and this job should pass.

ci: Add bender-up-to-date action

---

docs/04_cv32a6_design/source/cv32a6_glossary.rst

I added a few acronyms and fixed a couple typos. Here is the full changes list:
* Moved `VLEN` and `XLEN` so the list is now fully alphabetical
* Changed all occurrences of "lengh" to "length"
* Added
* APU
* AXI
* BHT
* BTB
* CVA6
* D$
* DPI
* EX
* I$
* MMU
* NC
* OoO
* PMP
* PTW
* RAS
* S-Mode
* TLB
* U-Mode

Improved Acronym List in Glossary

---

.github/workflows/ci.yml

The value of the `target` matrix is currently not used by the CI. However, it launches a job for each entry (without using it), unnecessarily consuming CI runtime.

ci: Remove unused `target` matrix

---

.github/workflows/ci.yml

The `defines` parameter is no longer used in the CVA6 Makefile. Therefore, remove it.

ci: Remove unused `defines` parameter

---

docs/01_cva6_user/ip-xact/cva6_csr.md
docs/01_cva6_user/ip-xact/cva6_csr.xml

Previously, specification was describing the information useful for user, which was not useful to verify the mscratch CSR. User information was replaced by information useful for verification.
Enumerated values has been added and address offset has been converted into hex format in md file
@mike, @ASintzoff, @spidugu444  Can you approve the updated information ?

Update mscratch description in CSR specification

---

Makefile

Fixes `vopt` stage crashing for newer questasim (2021.3 and newer) versions.
Without this patch, `vopt` fails with an internal error.

Makefile: Fix vopt stage by forcing net compatible types for ports

---

core/issue_read_operands.sv

This PR modifies a restriction in the issue stage. The role of the restriction is to avoids contentions in the `flu` result bus (functional unit -> scoreboard) as MULT duration is 2 cycles and other `flu` operations are 1 cycle-long (except div which has a stall signal and is not actually fixed latency).
While not all functional units use this same result bus, the issue stage was inserting a bubble after each MULT (except if the subsequent instruction is a MULT too) even when not needed. This PR fixes this too restrictive behavior.
LOAD uses another result bus so there are no contentions with MULT. A bubble was inserted in a `MULT -> LOAD` sequence even if it was not needed.

perf: fix too strict restriction on FLU write-back

---

docs/02_cva6_requirements/cva6_requirements_specification.rst

Even if bitmanip was not in the initial plans, it proves useful for performance and it's time to back-annotate the requirements.
"Should" reflects the fact that it was not in the initial plans.
@fatimasaleem, in addition, can you specifically check the version number? Thanks.

Add bit manip in the requirement specification.

---

Makefile
ariane.core

This PR uniformizes the handling of command line options that select the C++ standard used for compiling C++ code of the testbench.  With the upcoming upgrade of Spike (vendorization + update to latest upstream), the systematic use of C++ 2017 standard throughout the CVA6 project becomes mandatory. 
* Makefile (CFLAGS): Use C++ 2017 standard.  Fix whitespace.
* (src): Fix whitespace.
* ($(dpi-library)/%.o): Do not add another (potentially conflicting) C++ standard option.
* ariane.core (verilator_options): Use C++ 2017 standard.

[C++ TB code] Upgrade C++ standard used.  Clean up Makefile layout.

---

core/cache_subsystem/wt_axi_adapter.sv

This fixes an issue relating to non-8-byte-aligned SC operations.
I noticed this issue on an older version of cva6 in use by the [openesp project](https://github.com/sld-columbia/esp), and from reading the code here, I believe it probably applies to the current version as well. However, I have not managed to get any testbench set up with the master branch here, so I'm not 100% certain. The fix appears to be working fine with the openesp setup that I have, and I would be interested to know whether it helps here also.
The problem is demonstrated with the following example code:
```c
inline int load_reserve(volatile int * ptr) {
volatile int rc;
__asm__ volatile (
"lr.w %0, (%1)\n\t"
: "=r" (rc)
: "r" (ptr)
);
return rc;
}
inline int store_conditional(volatile int * ptr, int val) {
volatile …
```

Fix amo offset forgetfulness with write-through caches

---

core/serdiv.sv

The formal tool OneSpin 360 DV does not correctly handle the unsigned vs. signed comparison in `op_a_i == -$signed(1)`, as it expects a `$signed` keyword for `op_a_i`.
The commit fc2967c added this extra check to correct a bug that occurs when `op_a_i == -1`.
However, I then realized that this expression can be simplified.
Instead of appending `1'b1` if `op_a_i == -1` and `0'b0` else, the functionality remains the same if `1'b1` is always added.
The reason for this is that the last bit does not matter in the count leading zero operation whenever `op_a_i != -1`.
I also added `[$high(op_a_i)-1:0]` to avoid the implicit truncation.
Assume a WIDTH of 8:
If  `op_a_i == -1` (`8'b11111111`) then `lzc_a_input == 8'b00000001` and thus `lzc_a_result == 7`.
If  `op_a_i == -2` (`8'b11111110`) then …

Fixed and simplified expression for lzc_a_input in serdiv

---

corev_apu/openpiton/riscv_peripherals.sv

The current bootrom in riscv_peripherals.sv has an AXI-lite bridge that assumes 64b alignment, regardless of the request size. This is incompatible with requests of 32b i.e. I$ fetches which do not fill the full bus width. The erroneous behavior is that the 32b request will not be duplicated in the returning P-Mesh request, which violates the protocol.
This PR fixes this parameter to 0, which informs the bridge to consider the request size when packing the bus on request returns.

Fix bytewidth parameter in OpenPiton bootrom AXI-lite bridge

---

Makefile

`elf-bin` is propagated to fesvr via the plusplus arg. Since #1240, running
```
make sim elf-bin=path/to/elf
```
returns
```
terminate called after throwing an instance of 'std::runtime_error'
what():  could not open
+PRELOAD=path/to/elf (did you misspell it? If VCS, did you forget +permissive/+permissive-off?)
```
As per the README, if preloading is needed, `make sim preload=path/to/elf` should be used instead (https://github.com/openhwgroup/cva6/tree/master#memory-preloading), which sets `+PRELOAD=path/to/elf`:
https://github.com/openhwgroup/cva6/blob/6c89fda0da14e188c43c818be3af15123c82fc69/Makefile#L249-L253.

Makefile/questa: Pass elf-bin to fesvr

---

core/cache_subsystem/cva6_icache_axi_wrapper.sv

Prevents a negative repetition multiplier if `paddr` width > `AxiAddrWidth`.

icache_axi_wrapper: Cast paddr to AxiAddr

---

Makefile

`cva6_config_pkg` is currently listed in `tbs` and `src`. Elaborating it twice causes some tools to throw a warning (e.g. verilator) and others to error (e.g. questa). Fix this by removing `cva6_config_pkg` from the testbench file list (it is anyways used by the design and thus a design source).

Makefile: Remove duplicate cva6_config_pkg

---

core/cache_subsystem/cva6_icache.sv
core/cache_subsystem/wt_dcache_mem.sv
core/cache_subsystem/wt_dcache_missunit.sv
core/include/wt_cache_pkg.sv

from wt_cache_pkg to dedicated modules.
This will help for the parametrization

Move wt_cache_pkg functions which depend on cva6 input paramaters

---

Makefile

This reverts commit ae97ddb66023b14ddb6e26126d4386c027af2b13.
@niwis. This commit fails CI in target=vcs-testharness configuration. That's why it is an HOT FIX. Let's investigate the fail after fixing the CI.

[HOT FIX] Revert "Makefile: Remove duplicate cva6_config_pkg (#1273)"

---

core/alu.sv
core/decoder.sv
core/multiplier.sv

To increase the code coverage of CVA6, pragmas are inserted to disable some code lines. Pragmas are related to VCS tool, that is not so nice, but other solutions have been studied wihtout any success (macro approach is complex,  function is not supported by all tools)

Add coverage pragmas to exclude BITMANIP code

---

core/include/riscv_pkg.sv
docs/01_cva6_user/ip-xact/cva6_csr.md
docs/01_cva6_user/ip-xact/cva6_csr.rst
docs/01_cva6_user/ip-xact/cva6_csr.xml
docs/01_cva6_user/ip-xact/cva6_csr.yaml

ICACHE and DCACHE have an address in 0x700-0x77F which is a Standard read/write in M-mode. But ICACHE and DCACHE are Custom registers so they need to be Custom read/write. In fact there is two possibilities 0x7C0-0x7FF and 0xBC0-0xBFF. I chose the first one 0x7C0-0x7FF. 
ICACHE: 0x700==>0x7C0. 
DCACHE: 0X701==>0x7C1.  
RTL and Spec are changed to solve #1202 issue.

Changing Addresses of custom registers ICACHE and DCACHE.

---

core/include/std_cache_pkg.sv

Use `int unsigned` for loop variable `i` to avoid wrapping before loop exit condition is met.
Resolves bug https://github.com/openhwgroup/cva6/issues/1301

Fix infinite loop in std_cache_pkg::one_hot_to_bin (resolves #1301)

---

CODEOWNERS

I just figured out that apparently `CODEOWNERS` need to have write permissions to the repository. There are a couple of feature requests on Github to also enable the `triage` group to be listed but that hasn't been implemented yet.
I suggest starting populating it so that we are ready once that feature is implemented. And for all committers @JeanRochCoulon, @jquevremont, and @zarubaf it would already take effect.

Start populating more CODEOWNERS

---

.gitlab-ci/expected_synth.yml

The value is out-of-date, making CI show a failure.

test: update expected synth result

---

core/cva6.sv
core/include/ariane_pkg.sv
corev_apu/fpga/src/ariane_xilinx.sv
corev_apu/src/ariane.sv
corev_apu/tb/ariane_tb.sv
corev_apu/tb/ariane_testharness.sv
corev_apu/tb/common/spike.sv
corev_apu/tb/rvfi_tracer.sv

CVA6Cfg is now a input parameter of CVA6 to gather all the different configuration variables in the same structure.

Use CVA6Cfg as cva6 parameter

---

core/include/cv32a60x_config_pkg.sv

A extension was not enabled so far on cv32a60x. With A extension, Linux can run on cv32a60x.

Enable A extension

---

Makefile

Files changed:
* Makefile (verilate_command): Use correct paths to VL trace support files.

[Verilator] Fix trace generation after upgrading VL build process.

---

core/cva6.sv

Since the performance counters are implemented as an optional feature, this commit takes into consideration the case when the performance counters are disabled i.e in that case the output data from the performance counter module should read as 0 (which was reading as X's previously **#1237**)

Update for #1237

---

core/cva6.sv
core/frontend/frontend.sv

To be able to issue two instructions in the same cycle, fetching 64 bits each cycle is required to feed the instruction queue (there are not enough compressed instructions in usual code).
With compressed instructions, fetching 64 bits might return up to 4 instructions, which requires a change in the BTB and BHT shapes.  
4 columns means an index of two bits.
There is a mechanism to shift predictions when the access is not aligned.  
For the first item of the result, **the index was using a hardcoded number of one bit, so the returned prediction was not the good one**. This PR fixes that.  
For the subsequent items the result was good.
Without C extension and a 32-bits fetch, `INSTR_PER_FETCH = 1` so `(INSTR_PER_FETCH) = 0` which would cause an issue so the `if`/`else` block is used to …

fix prediction shift for BHT and BTB

---

Makefile
README.md

This pull request is an answer to my issue described at https://github.com/openhwgroup/cva6/issues/1340
Quick comments:
- I've removed the `-j${NUM_JOBS}` in Verilator generation as it basically shut down my VM (8 cores...).
- Modifications in Readme: I've tested with Verilator v4.110. I assume it should be compatible with other versions as well.

Fix VCD generation from Verilator model

---

core/decoder.sv

LWU was decoded in 32 and 64 bits. As it is a 64 bit instruction, this modification generates an illegal opcode when configuration is 32bit.

Generate illegal opcode when execute LWU with XLEN=32

---

core/decoder.sv

Decode AMOXOR_D (and similar instructions) only when XLEN=64bits 

---

.gitlab-ci/expected_synth.yml
core/cache_subsystem/cache_ctrl.sv
core/cache_subsystem/wt_dcache_ctrl.sv
core/cva6.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
core/load_unit.sv
util/config_pkg_generator.py

This modification introduces a pending load table that tracks outstanding load operations to the Dcache. The depth of this table is a parameter in the target configuration package.
The ID in the request from the load/store unit must be mirrored by the Dcache in the response. This allows to match a given response to its corresponding request. Responses can be given (by the Dcache) in a different order that the one of requests.
To be able to send one load request per cycle, the pending load table shall have at least 2 entries. This is to avoid a combinational path between the request and the response interfaces. This has a minor impact in the area anyway because each entry of the buffer has roughly 10 bits (FFs).

Support multiple outstanding load operations to the Dcache

---

core/acc_dispatcher.sv
core/cache_subsystem/miss_handler.sv
core/cache_subsystem/std_cache_subsystem.sv
core/cache_subsystem/std_nbdcache.sv
core/cache_subsystem/wt_cache_subsystem.sv
core/cache_subsystem/wt_dcache.sv
core/cache_subsystem/wt_dcache_missunit.sv
core/cva6.sv

This PR adds D$ access to the `acc_dispatcher`. For this, both caches (WT and STD) are adapted to handle a fourth D$ request port. This fourth port is used for issuing loads. Stores will go over the existing store request port. It is shared with the `store_buffer`, though the `store_buffer` always has priority access over the `acc_dispatcher`.
This fourth port is useful for accelerators, that want to access the D$ directly. Eventually it is also needed for the correct implementation of the CV-X-IF, which also has an interface into the memory. So this PR is a precursor to the future work needed for the correct CV-X-IF implementation.

Add Direct D$ Access to `acc_dipsatcher`

---

.gitignore

The `tools/` folder is generated hence it shall not be under version control.

add tools to gitignore

---

.gitlab-ci/expected_synth.yml

Previous merge has reduced the gate count, this commit fixes it.

HOT FIX, update expected_synth.yml

---

.gitlab-ci.yml

The "merge reports" job does not use submodules.
Not cloning/fetching submodules saves bandwidth.

dont use submodules to merge reports

---

verif/regress/coremark.sh
verif/regress/dhrystone.sh

There was an issue with paths, and as there is no `set -e`, bash ignores them.

fix cleaning in coremark and dhrystone

---

Makefile

This PR fixes issues that were preventing verilator from producing waves.

fix verilator wavedump

---

.gitignore
README.md
util/gcc-toolchain-builder/README.md
util/gcc-toolchain-builder/build-toolchain.sh
util/gcc-toolchain-builder/config/gcc-13.1.0-baremetal.sh
util/gcc-toolchain-builder/config/gcc-master-baremetal.sh
util/gcc-toolchain-builder/get-toolchain.sh

* .gitignore: Ignore source and build subdirectories of the toolchain
builder.
* README.md (Prerequisites): Update toolchain build instructions.
* util/gcc-toolchain-builder/README.md: New.
* util/gcc-toolchain-builder/build-toolchain.sh: Ditto.
* util/gcc-toolchain-builder/config/gcc-13.1.0-baremetal.sh: Ditto.
* util/gcc-toolchain-builder/config/gcc-master-baremetal.sh: Ditto.
* util/gcc-toolchain-builder/get-toolchain.sh: Ditto.

Add GCC toolchain builder.  Update README and .gitignore accordingly.

---

README.md

readme: use bash instead of sh

---

.github/dependabot.yml

The goal is that dependabot opens a PR just before the Dashboard runs.
This way the results will be available on Tuesday mornings, CET.

dependabot: run at 19:30 CET

---

verif/sim/Makefile
verif/tb/uvmt/cva6_tb_wrapper.sv
verif/tb/uvmt/uvmt_cva6_dut_wrap.sv
verif/tb/uvmt/uvmt_cva6_pkg.sv
verif/tb/uvmt/uvmt_cva6_tb.sv
verif/tb/uvmt/uvmt_default_inputs_intf.sv

We modify the VCS coverage parameters to disable coverage of assertion , FSM, internal signal toggle and constants.
The default input interface is created to prevent CVA6 inputs from being excluded from coverage.

Code_Coverage: Exclude coverage of assertions, FSM, toggle of internal signals and constants

---

.gitlab-ci/expected_synth.yml
core/commit_stage.sv
core/csr_regfile.sv
core/cva6.sv
core/include/ariane_pkg.sv
core/issue_read_operands.sv
core/load_unit.sv
core/scoreboard.sv

Condition RTL with FPU parameters to identify the dead code and remove the dead gates from netlist.

Code_coverage: Add conditions for the FPU

---

.gitlab-ci/expected_synth.yml
core/load_store_unit.sv

Resolves https://github.com/openhwgroup/cva6/issues/1456

Bypass misaligned address exception info in case of no MMU

---

.gitlab-ci.yml

- In the previous CI PR I forgot to keep running the Dashboard on master branch pushes in regress mode. It was set to run only on schedule (verif mode). This PR enables "regress" Dashboard runs on pushes on master branch
- There was an issue with the check-env: as it was not checking out a repository, it was keeping the files from previous runs in the same runner. These files were matched as artifacts, which was making the `merge reports` job fail.

[Hotfix] dashboard

---

core/alu.sv
core/decoder.sv
core/multiplier.sv

Remove VCS coverage pragma for BitManip and let only if(ariane_pkg::BITMANIP) in RTL to identify the code related to the BitManip.

Code_ coverage: Remove VCS coverage pragma for BitManip

---

verif/env/corev-dv/custom/cvxif_custom_instr.sv
verif/env/corev-dv/custom/riscv_zicond_instr.sv
verif/env/corev-dv/custom/rv32zicond_instr.sv
verif/env/corev-dv/cva6_defines.svh
verif/env/corev-dv/cva6_instr_gen_config.sv
verif/env/corev-dv/cva6_instr_test_pkg.sv
verif/env/corev-dv/user_extension/user_define.h
verif/env/uvme/cov/uvme_cva6_cov_model.sv
verif/env/uvme/cov/uvme_isa_covg.sv
verif/env/uvme/uvme_cva6_cfg.sv
verif/env/uvme/uvme_cva6_env.sv
verif/env/uvme/uvme_cva6_pkg.sv

This PR related to adding the new ZIcond extension in CVA6-DV (to generate zicond random instructions), and also add coverage in the cva6 env for this extension

Add Zicond extension in CVA6-DV & cva6 env

---

verif/sim/Makefile

When license is not available, the CI fails. This PR fixes the issue for VCS.

Add option to wait for VCS license

---

core/compressed_decoder.sv
core/cva6.sv
core/include/ariane_pkg.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
core/include/riscv_pkg.sv
util/config_pkg_generator.py

This PR resolves #1366 
This PR adds the support `zcb` extension which is one of the sub-extension recently ratified [Code Size Reduction (Zce)](https://github.com/riscv/riscv-code-size-reduction/releases/download/v1.0.4-1/Zc.1.0.4-1.pdf) extension.
This extension adds compressed ops for following instructions. All the `zcb` instructions require the support of at least standard C extension as a pre-requisite in addition to base (I-type) Instructions:
`c.lbu`, `c.lh`, `c.lhu`, `c.sb`, `c.sh`
`c.mul` (M extension is pre-requisite)
`c.zext.b` 
`c.sext.b` (Bitmanip is pre-requisite)
`c.zext.h` (Bitmanip is pre-requisite)
`c.sext.h` (Bitmanip is pre-requisite)
`c.zext.w` (Bitmanip is pre-requisite)
`c.not` 
1. The Compressed Decoder is updated to produce the corresponding 32-bit instructions. …

ADD SUPPORT FOR `Zcb` EXTENSION (from Code Size Reduction, Zce)

---

.gitlab-ci.yml
Makefile
README.md
verif/README.md
verif/regress/install-cva6.sh
verif/regress/install-riscv-dv.sh
verif/regress/install-spike.sh
verif/sim/Makefile
verif/sim/cva6.py

List of changes:
[Spike] Phase out SPIKE_ROOT in Spike installation script.
* verif/regress/install-spike.sh: Replace occurrences of SPIKE_ROOT with SPIKE_INSTALL_DIR.  Add coments.
Streamline installation process.
* README.md (Prerequisites): Update.
* verif/regress/install-cva6.sh (CV_SW_PREFIX): Add comment on value auto-detection.<br>
(RISCV_GCC): Ditto.<br>
(RISCV_OBJCOPY): Ditto.<br>
(SPIKE_ROOT): Replace with SPIKE_INSTALL_DIR.<br>
* verif/regress/install-riscv-dv.sh (SPIKE_ROOT): Ditto.
* verif/regress/install-spike.sh (ROOT_PROJECT): Set automatically from script path at all times.<br>
(SPIKE_ROOT): Phase out.<br>
(build+install procedure): Update log messages.<br>
* verif/sim/cva6.py (main): Replace SPIKE_ROOT with SPIKE_INSTALL_DIR.
Phase out SPIKE_ROOT as *installation …

Streamline installation process (Spike and toolchain variables, README file).

---

verif/env/corev-dv/cva6_asm_program_gen.sv
verif/env/corev-dv/cva6_instr_base_test.sv
verif/env/corev-dv/cva6_instr_gen_config.sv
verif/env/corev-dv/cva6_instr_sequence.sv
verif/env/corev-dv/cva6_instr_test_pkg.sv
verif/env/corev-dv/cva6_reg_hazard_stream.sv
verif/env/corev-dv/cva6_unsupported_instr.sv

This PR add unsupported extension instructions (like F extension or RV64 instruction) for the embedded config, to be sure that the core treat it as illegal instruction also.
Also I fix the handlers to support adding +2 if the instruction that raise an exception is compressed.

CVA6-DV : Add unsupported extension instruction for the embedded config

---

verif/env/corev-dv/custom/cvxif_custom_instr.sv

This a Fix for the cvxif generation tests

HOTFIX : Add CUS_ADD custom instruction under the switch cfg

---

core/csr_regfile.sv
core/include/riscv_pkg.sv

In version 1.12 of Machine ISA module (RISC-V privileged architecture
version 20211203), the mandatory CSR mconfigptr is defined.

Add mconfigptr CSR (fix #1480)

---

verif/regress/install-riscv-dv.sh

With newest Python versions (Python 3.9), cva6.py cannot find `dv.scripts` module.
This PR adds an empty `__init__.py` in dv so that the modules inside it can be found by Python 3.9.

fix dv for recent python versions

---

README.md

README.md how to run a simulation by executing Makefile commands, for instance 'make verilate'. This way does not work because additional variables need to be setup before executing these commands, for instance TARGET=cv64a6_imafdc_sv39. Many GitHub issues request support as #1489. This PR removes the getting start related to these commands to keep the way which is support that is to say using cva6.py command.
@MikeOpenHWGroup @zarubaf can you approve ?

Provide only one way to run simulation

---

core/csr_regfile.sv
core/load_store_unit.sv
core/load_unit.sv
core/store_unit.sv

Condition RTL with MMU parameters to identify the dead code and remove the dead gates from netlist.

Code_coverage: Add conditions for the MMU

---

.gitlab-ci/expected_synth.yml

The area has changed recently.
This PR also removes other expected areas as they are not asserted anymore.

ci: update expected area

---

.gitlab-ci.yml
.gitlab-ci/scripts/report_benchmark.py
.gitlab-ci/scripts/report_simu.py
verif/tests/testlist_riscv-arch-test-cv32a6_embedded.yaml
verif/tests/testlist_riscv-compliance-cv32a6_embedded.yaml
verif/tests/testlist_riscv-csr-access-test-cv32a6_embedded.yaml
verif/tests/testlist_riscv-tests-cv32a6_embedded-p.yaml

This PR reduces the number of jobs run in a CI pipeline, focusing on the `cv32a6_embedded` configuration.
It reorganizes jobs in categories and in stages to not run the whole pipeline when a smoke test fails.

ci: reorganize jobs

---

.github/workflows/ci.yml
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv

Add a WB CVA6 configuration and corresponding regression tests to the CI.

ci: Add regression tests for WB cache

---

.gitlab-ci.yml
.gitlab-ci/scripts/report_coverage.py
verif/sim/Makefile

We add the "-format" option to the URG command to generate the coverage report in TXT format.
The source file allows you to search from the TXT coverage report and display the coverage score for each desired module.

Code_Coverage: Display the coverage score at the end of the code coverage job

---

.gitlab-ci.yml

To reduce the CI execution time on servers

Do not execute "regress" CI on PR

---

.gitlab-ci.yml

Spike is being moved back to core-v-verif. So now fetching core-v-verif is needed to build spike in CI.
This PR additionally enables VCS environment to build spike, to prepare the CI for the tandem feature.

ci: use spike from core-v-verif

---

verif/env/uvme/uvme_cva6_cfg.sv

As you know the zicond is now disabled from the embedded config

Disable Zicond extension in the CVA6 UVM env

---

core/cva6.sv

When having multiple CVA6s this was problematic. Legacy code since an early version of verilator had problems with the string manipulation.
This shouldn't have any impact on the existing project since the tracer isn't used anywhere else afaik.
/cc @domenicw

tracer: Use `hart_id` for trace file format

---

.gitlab-ci.yml

This will make "dev" pipelines (used for PRs) shorter when none of `core/` or `corev_apu/` are changed, as only frontend smoke tests will be run.

ci(dev): run synthesis tests only when RTL has changed

---

.gitlab-ci.yml

"dev" pipeline was initially designed to be reviewed directly in GitLab
where job failures are already reported. Since it is now used to build
the Dashboard, the "check gitlab jobs status" job should be enabled in
this pipeline.

ci: enable job status checker in "dev" pipeline

---

core/perf_counters.sv

`events[i]` can be `'0` when there is nothing to count but that shouldn't reset the current count.
Fixes https://github.com/openhwgroup/cva6/issues/1542

perf_counters: Fix counter resetting to zero

---

core/cache_subsystem/axi_adapter.sv
core/cache_subsystem/cache_ctrl.sv
core/cache_subsystem/miss_handler.sv
core/cva6.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
corev_apu/fpga/src/ariane_xilinx.sv

This PR implements support for multiple outstanding store transactions bypassing the cache. It improves memory parallelism of write requests to non-cached memory regions, e.g. involved in configuring a peripheral.

Support multiple outstanding stores

---

.gitlab-ci/expected_synth.yml
core/cache_subsystem/wt_axi_adapter.sv
core/cache_subsystem/wt_dcache_missunit.sv
core/commit_stage.sv
core/controller.sv
core/store_unit.sv

Condition RTL with AMO parameters to identify the dead code and remove the dead gates from netlist.

Code_coverage: Add conditions for the AMO Extension

---

corev_apu/fpga/src/bootrom/src/LICENSE
corev_apu/fpga/src/bootrom/src/gpt.c
corev_apu/fpga/src/bootrom/src/gpt.h
corev_apu/fpga/src/bootrom/src/main.c
corev_apu/fpga/src/bootrom/src/sd.c
corev_apu/fpga/src/bootrom/src/sd.h
corev_apu/fpga/src/bootrom/src/smp.h
corev_apu/fpga/src/bootrom/src/spi.c
corev_apu/fpga/src/bootrom/src/spi.h
corev_apu/fpga/src/bootrom/src/uart.c
corev_apu/fpga/src/bootrom/src/uart.h

Re-release bootrom under Apache 2.0 license. The`smp.h` was already under Apache 2.0 from SiFive, so I think everything should be okay there.
@Moschn  okay?
Fixes #1551

[license] Fix license headers in FPGA bootrom

---

Makefile
ci/install-verilator.sh
ci/setup.sh
verif/regress/install-riscv-arch-test.sh
verif/sim/cva6.py
verif/tests/testlist_riscv-arch-test-cv32a60x.yaml
verif/tests/testlist_riscv-arch-test-cv32a6_embedded.yaml
verif/tests/testlist_riscv-arch-test-cv64a6_imafdc_sv39.yaml

This PR updates the Verilator version to v5.008 in the CI #1558.

[CI] Update Verilator version to v5.008

---

core/cache_subsystem/wt_dcache.sv

When MMU is not present ldst does not request address translation, that's why related dcache_ctrl is not useful. Condition it to MMU_PRESENT to increase code coverage and decrease the gate count.

Condition dcache_ctrl to MMU_PRESENT

---

.gitlab-ci/expected_synth.yml
core/csr_regfile.sv
core/cva6.sv
core/decoder.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
corev_apu/fpga/src/ariane_xilinx.sv

Add Supervisor Mode parameter to the CVA6 configuration and set it to 0 in the embedded config.
Condition RTL with Supervisor Mode parameter to identify the dead code and remove the dead gates from netlist.

Code_coverage: condition RTL with the S-MODE parameter

---

verif/regress/dv-generated-xif-tests.sh

As the execution of this job is longer than other jobs, reduce the number of executed jobs.

Reduce the number of executed tests

---

core/csr_regfile.sv
core/cva6.sv
core/decoder.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
corev_apu/fpga/src/ariane_xilinx.sv

Add User Mode parameter to the CVA6 configuration and set it to 0 in the embedded config.
Condition RTL with User Mode parameter to identify the dead code and remove the dead gates from netlist.

Code_coverage: condition RTL with the U-MODE parameter

---

.gitlab-ci/expected_synth.yml
core/cache_subsystem/wt_dcache_wbuffer.sv
core/controller.sv
core/csr_regfile.sv
core/cva6.sv
core/decoder.sv
core/frontend/frontend.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
core/scoreboard.sv
corev_apu/fpga/src/ariane_xilinx.sv

Add parameter for debug to the CVA6 configuration and set it to 0 in the embedded config.
Condition RTL with Debug Mode parameter to identify the dead code and remove the dead gates from netlist.

Code_coverage: condition RTL with the debug parameter

---

core/alu.sv
core/compressed_decoder.sv
core/decoder.sv

https://github.com/openhwgroup/cva6/issues/1565
https://github.com/openhwgroup/cva6/issues/1578

conditioned RTL with XLEN parameter

---

.gitlab-ci/expected_synth.yml
core/cache_subsystem/wt_dcache.sv

During ACCELERATE_PORT integration, NumPorts has been upgraded from 3 to 4 in wt_dcache.sv. This has implemented 3 times dcache_ctrl.sv in place of 2 times. @zarubaf Do you confirm/approve ?

Implement only 1 dcache_ctrl instances when ACC and MMU_PRESENT are disabled

---

core/decoder.sv

When debug mode is disable, DRET instruction is not supported.

Do not support DRET when DebugEn = 0

---

core/decoder.sv

Add the generation of illegal instruction in case of SRET decoding and supervisor mode disable.
@AEzzejjari can you confirm ?

[HOT FIX] Add else to SRET instruction decode

---

core/commit_stage.sv
core/controller.sv
core/ex_stage.sv
core/issue_read_operands.sv

Condition the sfence_vma instruction with User Mode parameter to identify the dead code and remove the dead gates from netlist.

Code coverage: Add SMODE parameter to the sfence_vma instruction

---

verif/env/corev-dv/cva6_ecall_instr_stream.sv
verif/env/corev-dv/cva6_instr_test_pkg.sv
verif/sim/cva6_base_testlist.yaml

This related to adding tests for improving CC, this about the ecall instruction that never been executed in the generated tests, so I create a class to inject ecall instruction.

CVA6-DV : Add ecall instruction into generate tests

---

core/compressed_decoder.sv

Condition FPU instruction in the compressed decoder with FpPresent parameter to remove the dead gates from netlist.

Condition the compressed decoder with the FpPresent parameter

---

.gitlab-ci.yml
verif/env/corev-dv/cva6_illegal_instr.sv
verif/env/corev-dv/cva6_instr_base_test.sv
verif/env/corev-dv/cva6_instr_sequence.sv
verif/env/corev-dv/cva6_instr_test_pkg.sv
verif/env/corev-dv/cva6_unsupported_instr.sv
verif/regress/dv-generated-tests.sh
verif/sim/cva6_base_testlist.yaml

Hello, this Mr related to adding more tests to the CI to improve code & functional coverage: 
1. Add unsupported instruction like RV64, RV32FDQ
2. Enable zcb extension to avoid falling tests in the CI

Add unmapped Instructions tests to improve code coverage

---

core/load_unit.sv

Modify coding style to improve Code Coverage.

Modify coding style to improve CC

---

verif/docs/VerifPlans/ISA_RV32/RISCV_Instructions.rst
verif/docs/VerifPlans/ISA_RV32/VP_IP016.yml
verif/docs/VerifPlans/ISA_RV32/VP_IP017.yml
verif/docs/VerifPlans/ISA_RV32/VP_IP018.yml
verif/docs/VerifPlans/ISA_RV32/runme.sh
verif/docs/VerifPlans/source/dvplan_ISA_RV32.md

I add dvplan for embedded version base on STEP1 dvplan :
1. I change the dvplan's STEP1 name to ISA_CV32A60X
2. Add cva6 embedded under name ISA_CV326_EMBEDDED That I add Zcb instructions & remove Atomic instructions

ISA DVPLAN for embedded config

---

docs/03_cva6_design/issue_stage.md

Multiplication takes two cycles (1 cycle latency) and ALU takes one
cycle (no latency). They share the same writeback port so it is not
possible to issue an ALU instruction just after a MUL.  So the example
is wrong, but it is okay if we replace MUL by LOAD as it uses another
write-back port.
Fix #1106

docs: fix example of OoO write-back to scoreboard

---

verif/env/corev-dv/custom/riscv_zcb_instr.sv
verif/regress/dv-generated-tests.sh
verif/regress/dv-generated-xif-tests.sh
verif/regress/smoke-gen_tests.sh
verif/sim/cva6_base_testlist.yaml

Hello, this MR related to generate Zcb instruction in the CI tests, so to workaroud the problem of the gcc-13 that doesn't support zcb extension, I change in every Job generate zcb instruction the RISCV variable to point to the right gcc.

Generate Zcb extension instructions

---

core/csr_regfile.sv

csr_regfile.sv: force mstatus.UBE to 0 (see #1417)

---

verif/env/corev-dv/cva6_illegal_instr.sv
verif/env/corev-dv/cva6_instr_sequence.sv
verif/env/corev-dv/cva6_unsupported_instr.sv

Adding constraint to generate illegal RV32Zcb instruction (illegal func3 & func2), also generate RV64zcb instruction, to improve CC

Add more constraints to cover corner cases in CC

---

verif/env/corev-dv/custom/riscv_zcb_instr.sv

Using the get_instr_name() of the origin class

Fix TODO, using get_instr_name() of origin riscv_instr class

---

.github/dependabot.yml

Adds hpdcache to the list of submodules kept up-to-date by dependabot.
Also removes the `Component:Verif` label from Dependabot PRs because:
- hpdcache submodule is an RTL feature and not a verification tool
- CVA6 PRs are usually unlabelled

dependabot: update hpdcache

---

core/compressed_decoder.sv

Only compressed illegal instructions are identified in this module.
Therefore is_compressed_o is always equal to 1.
This modification improves condition coverage.

compressed_decoder.sv: remove useless condition

---

.gitlab-ci.yml

Because of directed_isacov-tests failures, coverage report generation is
not run on scheduled pipelines the week-end; it is run only when the job
is manually started from a regress pipeline because in this case, the
job is allowed to fail.
Allowing failures on verif jobs will let report coverage running.

report coverage even when a verif job fails

---

docs/02_cva6_requirements/cva6_requirements_specification.rst

During the CVA6 Verification meeting today (2023-11-09) it was pointed out that we have not defined the version of the Zc* ISA extension we support.  This is a recently ratified spec. and it is not easy to find, so this PR (attempts to) resolve that.
Since I was already editing the `cva6_requirements_specification.rst` doc, I took the liberty of adding the CV32A60B, although I am not sure if the configuration information I added is correct.

Add the Zc* ISA to "Applicable Specifications"

---

core/cache_subsystem/cva6_icache.sv
core/cache_subsystem/wt_dcache_wbuffer.sv
core/cva6.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
core/load_unit.sv
corev_apu/fpga/src/ariane_xilinx.sv

Condition RTL with NonIdemPotence parameters to identify the dead code and remove the dead gates from netlist.

Code coverage: Add NonIdemPotence parameter

---

verif/regress/benchmark.sh
verif/regress/coremark.sh
verif/regress/dhrystone.sh
verif/regress/smoke-tests.sh
verif/sim/cva6.py
verif/sim/cva6_base_testlist.yaml

Currently, some GCC compilation parameters are hard-coded in CVA6.py whereas the same parameters are given in the yaml files of most tests, meaning they are given twice.
This also allows removing them easily in cases where they are not required.

No hard coded gcc param

---

Bender.yml

The files already exist but somehow, the `cv64a6_imafdc_sv39_wb` bender target was lost.
This adds support for the `cv64a6_imafdc_sv39` configuration with write-back cache.
/cc @zarubaf

bender: Add writeback cache configuration

---

core/csr_regfile.sv

This PR fixes a privilege violation check when accessing the counter CSR from U-mode.
According to the spec:
> ...U-mode may only access a counter if the corresponding bits in scounteren and mcounteren are both set.
Before this fix, the violation only happens if both are set.
Tested on Linux 5.19 while using `rdcycle` from U-mode.

[csr/scounteren] fix privilege violation logic

---

.gitlab-ci/expected_synth.yml
core/include/cv32a6_embedded_config_pkg.sv

Technology permitting, load can be done in wait state zero, which increases performance.

Configure load to be wait state zero in embedded configuration

---

.gitlab-ci/expected_synth.yml
.gitlab-ci/scripts/report_benchmark.py
core/include/cv32a6_embedded_config_pkg.sv

16 entry BHT is not so costy in term of gate count, and will increase performance

Add 16 entry BHT in embedded configuration 

---

core/csr_regfile.sv

Hello,
TO begin the verification on the interrupt, should have this fix, because always the cva6 check interrupts in signal step, even if it doesn't support it, so this MR should fix the problem

CSR_REGFILE : No need to check single step if we don't support debug mode

---

verif/tests/custom/csr_embedded/csrcs_test.S
verif/tests/custom/csr_embedded/csrcsi_test.S
verif/tests/custom/csr_embedded/csrrw_test.S
verif/tests/custom/csr_embedded/csrrwi_test.S

This fix the falling csr tests, after the last commit.
we should always clear MIP after write into it, to avoid raising an interrupt.
We can't add exception handler to resolve this because we write into mtvec also.

[Verif] Clear MIP CSR to avoid trapping in CSR tests

---

verif/tests/custom/csr_embedded/csrrw_ro_test.S

I forgot to clean the MIP, in csrrw_ro_test.S

[Verif] Clear MIP CSR to avoid trapping in CSR tests (resume #1660)

---

core/cache_subsystem/cva6_hpdcache_if_adapter.sv
core/include/std_cache_pkg.sv

using verible-v0.0-3422-g520ca4b9/bin/verible-verilog-format
with default configuration

verible-verilog-format: update to bypass verible limitations

---

core/axi_shim.sv
core/cva6.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
corev_apu/fpga/src/ariane_xilinx.sv

Add AxiBurstWriteEn parameter to the CVA6 configuration and set it to 0 as the CVA6 does not support bursts with a length greater than 0.
Condition RTL with AxiBurstWriteEn parameter to identify the dead code and remove the dead gates from netlist.
Based on if() directives, VCS is able to identify the unused code, this will allow to improve code coverage

Code_coverage: condition RTL with the AxiBurstWriteEn parameter

---

core/alu.sv
core/cache_subsystem/wt_axi_adapter.sv
core/decoder.sv
core/load_store_unit.sv
core/mult.sv
core/multiplier.sv

Condition RTL with IS_XLEN64 parameter to identify the dead code and remove the dead gates from netlist.
Based on if() directives, VCS is able to identify the unused code, this will allow to improuve code coverage.

Code_coverage: condition RTL with the IS_XLEN64 parameter

---

Bender.yml
vendor/pulp-platform/tech_cells_generic/CHANGELOG.md
vendor/pulp-platform/tech_cells_generic/README.md
vendor/pulp-platform/tech_cells_generic/src/fpga/tc_clk_xilinx.sv
vendor/pulp-platform/tech_cells_generic/src/fpga/tc_sram_xilinx.sv
vendor/pulp-platform/tech_cells_generic/src/rtl/tc_clk.sv
vendor/pulp-platform/tech_cells_generic/src/rtl/tc_sram.sv
vendor/pulp-platform_tech_cells_generic.lock.hjson
vendor/pulp-platform_tech_cells_generic.vendor.hjson

Upgrade `tech_cells_generic` to `v0.2.13`. See the [tech cells generic changelog](https://github.com/pulp-platform/tech_cells_generic/blob/master/CHANGELOG.md) for details.

tech_cells_generic: Upgrade to v0.2.13

---

core/perf_counters.sv

With two (or more) commit ports, the `for (int unsigned j = 0; j < NR_COMMIT_PORTS; j++) if (commit_ack_i[j]) events[i] = commit_instr_i[j].fu == LOAD;//Load accesses` does not set `events[i]=1'b1` if there are two committed instructions (`commit_ack_i=2'b11`) and only one of them is a load, while it should.
The same is true for the other events.
This commit explicitly checks on each commit port and then checks that at least one committed the event being monitored.

Fix event tracing on more commit ports.

---

core/cache_subsystem/cache_ctrl.sv

WB cache: do not accept a new request when there is a flush in progress.

cache_ctrl: Do not accept new request during flush

---

ACKNOWLEDGEMENTS.md

We've just received the "official" notification that KDT JU has become Chips JU. Hence, acknowledgements need an update.

Replacing KDT with Chips JU logo

---

README.md
util/gcc-toolchain-builder/README.md

Related to : https://github.com/openhwgroup/cva6/issues/1453
Made the Quickstart section of the README more straightforward and enticing people to use the scripts to build the toolchain and the tools, to avoid potential issues like these ones : https://github.com/openhwgroup/cva6/issues/1631 https://github.com/openhwgroup/cva6/issues/1410 https://github.com/openhwgroup/cva6/issues/1489
Removed the table of content since it is now integrated into Github README viewer.
Moved the contributing and publication section at the bottom.
Removed references to some docs images that are not present in the repo anymore.

Make the readme quickstart more user-friendly

---

Makefile

Related to https://github.com/openhwgroup/cva6/issues/1572 and https://github.com/openhwgroup/cva6/issues/1569 .
Setting `VERILATOR_INSTALL_DIR` in the `./Makefile` is not relevant anymore since it now has to be set before running CVA.py to simulate which will then use the Makefile.
On top of that, the path is wrong (should be `./tools` not `./tmp`).

remove wrong and now useless variable declaration in Makefile

---

ci/install-verilator.sh
verif/regress/install-cva6.sh
verif/regress/install-verilator.sh

- Removed an hardcoded `NUM_JOBS` value in `verif/regress/install-cva6.py` which defeated the purpose of setting `NUM_JOBS` and could have potentially resulted in issues on some system configurations, since it was set quite high.
- Set the default `NUM_JOBS` value to 1 in all scripts.
An unset `NUM_JOBS` environment variable should now results in a sequential execution of make jobs in all scripts, as described in the `README`'s Quickstart

Set default NUM_JOBS value to be the same accross all scripts

---

.gitlab-ci/expected_synth.yml
.gitlab-ci/scripts/report_benchmark.py
core/include/cv32a6_embedded_config_pkg.sv

Based on Coremark study, three parameters are fine tuned: BHT, RAS, and load buffer.

Update embedded config to improve trade-off performance gate count

---

.gitlab-ci.yml
Makefile
corev_apu/tb/common/spike.sv
verif/tb/core/rvfi_pkg.sv

Bump core-v-verif
- Sync with the changes made to the `rvfi_utils.sv`
- Get newer changes on Spike to support verilator

Verilator Tandem Support

---

.gitlab-ci/expected_synth.yml
core/axi_shim.sv
core/csr_regfile.sv
core/decoder.sv
core/frontend/bht.sv
core/frontend/frontend.sv
core/issue_read_operands.sv
core/load_unit.sv
core/mult.sv
core/scoreboard.sv
core/store_unit.sv

Condition RTL with parameters to remove dead code.

Code coverage: condition RTL With parameters

---

docs/01_cva6_user/AXI_Interface.rst
docs/01_cva6_user/CSR_Cache_Control.rst
docs/01_cva6_user/CVA6_user_guide.rst
docs/01_cva6_user/CVX_Interface_Coprocessor.rst
docs/01_cva6_user/Compiler_Command_Lines.rst
docs/01_cva6_user/Core_Integration.rst
docs/01_cva6_user/Custom_Instructions.rst
docs/01_cva6_user/Interfaces.rst
docs/01_cva6_user/Introduction.rst
docs/01_cva6_user/PMA.rst
docs/01_cva6_user/Programmer_View.rst

This is a first pass to update the CVA6 user manual addressing configurations.
@fatimasaleem, can you especially review the ISA extensions supported by CV32A60X in Introduction.rst?
@JeanRochCoulon, can you especially review the ISA extensions supported by CV32E6?X in Introduction.rst?
@AEzzejjari, I took the liberty of updating AXI_Interface.rst to align its style with other chapters (fewer indents). Tell me if it is acceptable or if I have to revert the changes.
Complete reviews are of course welcome.
What will need updates in next passes:
- CSR_Performance_Counters.rst (when Zicount in CV32A60X is confirmed)
- PMP.rst (when their presence/absence in CV32E6?X is confirmed)
- RISCV_Instructions (when the ISA extensions supported by CV32A60X and CV32E6?X are confirmed)
- …

Updated user manual to address several configuration (first pass)

---

core/decoder.sv

The indexing expression was really complex.  It is constant so is is
possible to directly use an "unsized" localparam.  The values are less
than 32 so it is equivalent to previous code.  This coding style is the
one used in the CSR regfile.
It will simplify future modifications, including completing
parametrization.

refactor(decoder): simplify interrupt indexing

---

docs/02_cva6_requirements/cva6_requirements_specification.rst

After further investigation, the feature is not needed for security application.
For safety applications, variable-time division is only one of several sources of unpredictability and it does not make real sense to address it.

Remove fixed-time division (ISA-110)

---

core/branch_unit.sv

The bit at index 1 must be 0 if the RVC extension is disabled.
Fix #1300
Replace PR #1690

fix: exception on misaligned branch if no RVC

---

docs/01_cva6_user/index.rst

index.rst needs an update too so that the Zb* extension appear in ReadTheDoc.

[Skip CI] Integrated Zb* in user manual (index.rst)

---

README.md

This will lead to an error, because the space separates one file path into 2 paths.

fix: extra space in command

---

docs/01_cva6_user/AXI_Interface.rst
docs/01_cva6_user/CSR_Performance_Counters.rst
docs/01_cva6_user/CVX_Interface_Coprocessor.rst
docs/01_cva6_user/Interfaces.rst
docs/01_cva6_user/Introduction.rst
docs/01_cva6_user/Programmer_View.rst
docs/01_cva6_user/RISCV_Instructions.rst
docs/01_cva6_user/RISCV_Instructions_RV32A.rst
docs/01_cva6_user/RISCV_Instructions_RV32C.rst
docs/01_cva6_user/RISCV_Instructions_RV32I.rst
docs/01_cva6_user/RISCV_Instructions_RV32M.rst
docs/01_cva6_user/RISCV_Instructions_RV32ZCb.rst
docs/01_cva6_user/RISCV_Instructions_RVZba.rst
docs/01_cva6_user/RISCV_Instructions_RVZbb.rst
docs/01_cva6_user/RISCV_Instructions_RVZbc.rst
docs/01_cva6_user/RISCV_Instructions_RVZbs.rst
docs/01_cva6_user/RISCV_Instructions_RVZicond.rst
docs/02_cva6_requirements/cva6_requirements_specification.rst

In the user manual:
- Updated part numbers: CV32A60X (embedded configuration), CV32A60AX (application configuration)
- In the Zb* extensions, grouped RV32+RV64 instructions on one side and RV64-specific instructions on the other side, to ease the upcoming templating.
The upcoming templating will allow to generate documentation that are specific to a given configuration.

UM: Part number + reshuffled Zb* RV32/RV64 instructions

---

README.md
util/gcc-toolchain-builder/README.md

Fixed a broken link to `util/gcc-toolchain-builder/README.md` leading to https://github.com/openhwgroup/cva6/issues/1693.
Added a section regarding Spike and Verilator install preriquisites (see https://github.com/openhwgroup/cva6/issues/1700)

Quickstart fix

---

verif/tests/custom/csr_embedded/csr_counters_overflow.S
verif/tests/custom/csr_embedded/csrrw_fields_test.S
verif/tests/custom/csr_embedded/csrrw_ro_test.S
verif/tests/custom/csr_embedded/csrrw_test.S
verif/tests/testlist_csr_embedded.yaml

This MR add overflow counters test for, m[cycle]h , m[instret]h, also fixing reset value for misa & mvendorid

Add overflow counter test & fix reset value

---

verif/env/uvme/cov/uvme_cva6_config_covg.sv
verif/env/uvme/reg/cva6_csr_reg_file.sv
verif/sim/Makefile
verif/sim/cva6.hvp

This MR related to fix some CSRs values in the coverage model, also update hvp

Fix CSR coverage model & HVP

---

CONTRIBUTING.md

One addional condition has been added to contributing.md. A PR can be merged only if it does not impact the code coverage to guaranty the RTL maturity level.

Update contibuting.md: contribution shall not impact code coverage

---

core/alu.sv
core/compressed_decoder.sv
core/csr_regfile.sv
core/cva6.sv
core/decoder.sv
core/include/ariane_pkg.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
core/multiplier.sv
corev_apu/fpga/src/ariane_xilinx.sv

To have similar for RVB as for other extensions in csr_regfile.sv, replace ariane_pkg::BITMANIP by CVA6Cfg.RVB

csr_regfile.sv: add RVB field for MISA (fix #1734)

---

core/cache_subsystem/miss_handler.sv

There exists a timing loop in the WB cache caused by the `axi_adapter_arbiter` module. This PR fixes it by breaking the connection between the `rsp_i.gnt` and `rsp_o[sel_q].gnt` signals. At the same time, this PR also removes an unnecessary cycle delay between two requests on the same port.

Break Timing Loop in Axi Adapter Arbiter of WB Cache

---

.gitlab-ci/expected_synth.yml
Makefile
core/Flist.cva6
core/cva6.sv
core/cva6_rvfi.sv
core/cva6_rvfi_probes.sv
core/decoder.sv
core/ex_stage.sv
core/id_stage.sv
core/include/ariane_pkg.sv
core/issue_stage.sv
core/load_store_unit.sv
core/scoreboard.sv
core/store_buffer.sv
core/store_unit.sv
corev_apu/fpga/src/ariane_xilinx.sv
corev_apu/src/ariane.sv
corev_apu/tb/ariane_tb.sv
corev_apu/tb/ariane_testharness.sv
verif/tb/core/Flist.cva6_tb
verif/tb/uvmt/cva6_tb_wrapper.sv

Support for post-synthesis RVFI tracer without impacting the number of gates
- remove logic in the scoreboard, in the lsu and at the top
- creation of a module to build rvfi_probes structure with all the internal signals used to build the rvfi_instr structure, This module is instantiated at top cva6
- creation of a module which builds rvfi_instr. This module is instantiated in all supported testbenches
Breaking change: rvfi_o port removed, rvfi_probes_o added. Can be left open as before if you don't need tracer_rvfi

Remove all logic and sequential related to RVFI in CORE cva6

---

verif/regress/install-spike.sh

Fix two bugs in `verif/regress/install-spike.sh`.
Related to #1757.
In short,
1. In line 26, change `-n` to `-z`.
2. In line 49, add `sudo`.

Fix bug in `install-spike.sh`

---

verif/sim/cov-exclude-mod.lst

Exclude the cva6_rvfi_probes module from code coverage report

Exclude cva6_rvfi_probes module from Code coverage

---

verif/env/uvme/uvme_cva6_cfg.sv

This PR enable zcb extension in the CVA6 uvm env (should be merge after the MR https://gitlab-tss.gemalto.com/riscv/ohg-pr/core-v-verif/-/merge_requests/86)

Enable zcb extension into cva6 UVM Env

---

.gitlab-ci/expected_synth.yml
core/branch_unit.sv
core/csr_regfile.sv
core/cva6.sv
core/cva6_rvfi.sv
core/cvxif_fu.sv
core/decoder.sv
core/fpu_wrap.sv
core/frontend/instr_queue.sv
core/id_stage.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
core/issue_read_operands.sv
core/issue_stage.sv
core/load_store_unit.sv
core/mmu_sv32/cva6_mmu_sv32.sv
core/mmu_sv39/mmu.sv
core/scoreboard.sv
corev_apu/fpga/src/ariane_xilinx.sv

Add a parameter TvalEn to remove tval gates in embedded configuration.
Behaviour when software is trying to write to MTVAL or STVAL should be determined. 
In this PR, it is forbidden and access to MTVAL or STVAL when TvalEn is disabled will raise an illegal instruction exception.

Parameterize TVAL to reduce size in embedded

---

.gitlab-ci/scripts/report_benchmark.py

This MR Fix detecting "Mcycle" sting by the benchmark script, if there no CSR pseudo-code

Fix: Detecting "mcycle" without CSR pseudo-code

---

verif/tests/custom/isacov/seq_hazard.S
verif/tests/testlist_isacov.yaml

This MR update sequential directed test and remove failing test from regression (need to Fix a bug)

ISACOV : Update seq Directed test, and remove failing tests from regression

---

verif/env/uvme/reg/cva6_csr_reg_file.sv
verif/env/uvme/uvme_cva6_cfg.sv
verif/tests/custom/csr_embedded/csrcs_test.S
verif/tests/custom/csr_embedded/csrcsi_test.S
verif/tests/custom/csr_embedded/csrrw_fields_test.S
verif/tests/custom/csr_embedded/csrrw_test.S
verif/tests/custom/csr_embedded/csrrwi_test.S

This MR removes MTVAL from CSR embedded tests and only updates the coverpoint related to this CSR because MTVAL isn't supported in embedded configuration

MTVAL : Remove MTVAL CSR from CVA6 UVM environment

---

core/include/cv32a65x_config_pkg.sv

Configure icache with 2 ways in cv32a65x

---

core/cache_subsystem/cva6_hpdcache_subsystem.sv
core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
core/cva6.sv

Suggested fixes for _HDPcache_ integration in CVA6.
_HPDCache_ is **defining again the typedef for AXI protocol**, with exactly the sames names than the ones in _package ariane_axi_. Using Cadence Xcelium simulator, the usage of several typedef with identical names is forbidden.
This fix suggests to **propagate the AXI typedef** given to cva6 top (through parameter types) to hdpcache. As a consequence, local definition of AXI typedef are removed.
@cfuguet , could you give me your opinion about it?
NB: Feedbacks are welcome, since this is the first PR from Bosch!

[Bugfix hpdcache] axi struct usage

---

verif/sim/cva6.hvp

This MR related to update HVP (Code & functional Coverage report) : 
1. Map ZCB instructions
2. Remove DRET instruction (don't supported)

CVA6 HVP : Map ZCB instructions & remove DRET instruction

---

verif/env/uvme/cov/uvme_cva6_cov_model.sv
verif/env/uvme/cov/uvme_exception_covg.sv
verif/env/uvme/cov/uvme_illegal_instr_covg.sv
verif/env/uvme/uvme_cva6_env.sv
verif/env/uvme/uvme_cva6_pkg.sv

This PR used the rvfi.cause (that I add in the PR#2354 core-v-verif), to detect the exception cause, using this I create 2 covarege models :
1. Unmapped instruction : trying to to cover illegal opcode of various extension also illegal funct3 & funct7, the Covergroup sample only if instr.cause == 2 (illegal instruction exception code) 
2. Exceptions : cover the values of instr.cause but only if instr.trap == 1 (there's a trap), also I add some switch, as example ENV_CALL_UMODE is ignore because user_mode isn't supported, finally I add a coverpoint that cover the transaction from NO_EXCEPTION -> EXCEPTION -> EXCEPTION.
N.B : this is just a first version, we can add more and of course remove things

Functional coverage : Create Unmapped instruction and exceptions coverage models

---

docs/01_cva6_user/CSR_CV32A60AX.rst
docs/01_cva6_user/CSR_CV32A60AX_list.rst
docs/01_cva6_user/CSR_CV32A60X.rst
docs/01_cva6_user/CSR_CV32A60X_list.rst
docs/01_cva6_user/Programmer_View.rst
docs/01_cva6_user/RISCV_Instructions.rst
docs/01_cva6_user/RISCV_Instructions_RVZbs.rst
docs/01_cva6_user/index.rst

First attempt to add configuration-specific CSR lists and descriptions in the user manual.
First attempt to point to a file in another subdirectory (common between user manual and design document). I think we need to PR to test if it creates the expected result in ReadTheDocs.

Adding configuration-specific CSR doc

---

verif/sim/cva6.hvp

This MR update the HVP by adding Illegal & exception functional coverage

Map Illegal and exception covergroup

---

core/cache_subsystem/miss_handler.sv

In #1361, the default number of MSHR ports was increasesed by one. This mapped AXI IDs for bypassed stores from previously `4'b1010` to `4'b1011`, colliding with the AXI IDs for AMOs. Apart from performance implications, this may conflict with A7.4.4 of the AMBA AXI protocol spec K ("ID use for Atomic transactions").
Fix this by assigning AMOs the next free AXI ID.

miss_handler: Fix AMO AXI ID mapping

---

verif/env/uvme/cov/uvme_illegal_instr_covg.sv

Thsi MR is a Fix related to illegal cg sampling

Functional coverage : Fix illegal cover_group sampling

---

README.md
verif/sim/Makefile

Update user-level instructions.  Re-introduce waveform generation in vcs-uvm mode.
* README.md: Add section on waveform generation.  Improve readability.
* verif/sim/Makefile (vcs-testharness): Add comment and TODO.
(veri-testharness): Save waveforms prior to disassembling the hex log.
(questa-testharness): Add TODO comment.
(vcs-uvm): Save waveforms prior to disassembling the hex log.

Fix waveform generation using vcs-uvm.  Add waveforms section to README.

---

core/include/cva6_hpdcache_default_config_pkg.sv

Changelog:
- Add support to OpenPiton in the HPDcache
- Add new parameter to choose the depth of the REFILL fifo in the HPDcache
- Improvements and bugfixes

hpdcache: bump new version of the submodule

---

verif/regress/install-spike.sh
verif/regress/install-verilator.sh
verif/regress/linux.sh
verif/regress/smoke-tests.sh
verif/sim/setup-env.sh

Related to : https://github.com/openhwgroup/cva6/issues/1795.
* The detection of the tools should now work as expected. 
* Also moved the `setup-env.sh` execution in the smoke-tests since it is intended to be ran when tools are installed. 
* Added a failsafe in `install-verilator.sh` in case several verilator directories are installed in the `tools` directory (the first one returned by `grep` is picked). 
* Use `setup-env.sh` instead of `install-cva6.sh` and `install-riscv-dv.sh` in `linux.sh` test since they no longer exist in the repo

Fix Verilator detection by tests

---

core/perf_counters.sv

The privilege check is already in place in the `csr_regfile.sv`, but a read to `CSR_HPM_COUNTERx` should not return 0s.

Enable reads on `CSR_HPM_COUNTERx`

---

verif/sim/cva6.hvp

This MR update our HVP, by mapping the AXI5 functional coverage

Map AXI functional coverage to the HVP

---

.gitlab-ci.yml

Sourcing the scripts was preventing the CI from collecting the logs

Get logs in Gitlab CI for smoke-tests when failed

---

core/decoder.sv

add a condition to raise exception when S mode is not supported

decoder.sv: sfence.vma valid only if S mode supported (fix #1866)

---

verif/env/corev-dv/cva6-files.f
verif/env/corev-dv/cva6_instr_gen_tb_top.sv

This PR aims to resolve issue #1816 
The chosen solution is the same one than the other cores: adapting the riscv_instr_gen_tb_top to cva6.
That module could not be extended as suggested, since it is not a class.
This has been check with VCS 2021.09: the behavior is the same than previous on our side.

Add cva6 specific riscv_instr_gen_tb_top 

---

docs/01_cva6_user/Programmer_View.rst

Update the “RISC-V Virtual Memory” section in the CVA6 user manual with Sv32, Sv39 and Sv39x4 information after MMU merge

Mmu user manual

---

verif/regress/install-verilator.sh
verif/sim/setup-env.sh

* verif/sim/setup-env.sh: Double-quote variable values.  Install Verilator
in 'tools/verilator' by default.  Add SPIKE_PATH to PATH.
* verif/regress/install-verilator.sh: By default use per-version dirs to
build and install Verilator.  Add and improve configuration messages.

Improve environment setup.  Fix Verilator installation process.

---

.gitlab-ci/scripts/report_simu.py

Jobs in dashboard were marked as passing even though the simulators build were failing.
The job will now be marked as failed when a build error happens during the CI Job execution.

Mark jobs as failed when build fails

---

.gitlab-ci.yml
verif/sim/Makefile
verif/sim/cva6.py

* verif/sim/Makefile (veri-testharness): Don't add target name to waveform
file name.<br>
(vcs-uvm): Ditto.
* verif/sim/cva6.py (run_assembly): Add target name to log file name.<br>
(run_elf): Ditto.<br>
(run_c): Ditto.<br>
(iss_sim): Ditto.<br>
(iss_cmp): Ditto.

Generate separate per-target logs when simulating.

---

core/cache_subsystem/cva6_hpdcache_subsystem.sv
core/include/cva6_hpdcache_default_config_pkg.sv

- Updates the interface of the HPDcache to match the latest version
- Adds a parameter allowing to select the replacement policy in the HPDcache. By default, the package uses the (pseudo)  random victim selection policy.
- By default, the HPDcache uses a fully-associative MSHR. The number of entries depends on the maximum number of loads that the CVA6 can have in-flight.

hpdcache: update submodule, interface and parameters

---

core/Flist.cva6
core/Flist.cva6_gate
core/cva6.sv
core/include/build_config_pkg.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a65x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
corev_apu/fpga/src/ariane_xilinx.sv
corev_apu/tb/ariane_tb.sv
corev_apu/tb/ariane_testharness.sv
verif/env/uvme/cov/uvme_cva6_config_covg.sv
verif/tb/core/uvma_cva6pkg_utils.sv
verif/tb/uvmt/uvmt_cva6_tb.sv

This PR splits the configuration structure so that the user configuration does not contain dummy values.
This is the first step for #1451
It partially replaces PR #1704
See also [the announcement on Mattermost](https://mattermost.openhwgroup.org/all-users/pl/mr3aereappdt58f8ag8p11r9nr)

Parametrization step 1

---

core/cva6_rvfi.sv
core/cva6_rvfi_probes.sv
core/include/ariane_pkg.sv
corev_apu/fpga/src/ariane_xilinx.sv
corev_apu/tb/ariane_tb.sv
corev_apu/tb/ariane_testharness.sv

This PR makes sure that no instances of parametrized types go outside of CVA6, except RVFI-related types.
It will ease parametrization as types such as `scoreboard_entry_t` does not have to be transformed into a macro.
It additionally removes unused `IsRVFI` parameters.

modify rvfi probes for param

---

.gitlab-ci.yml

The Smoke-gate test is broken in CI because of https://github.com/openhwgroup/cva6/pull/1899 .
The Spike version check is failing because it cannot get the appropriate hash version of spike files in core-v-verif.
Fixed it by unshallowing core-v-verif in the smoke-gate job.

Fix CI smoke-gate test

---

verif/sim/cov-exclude-mod.lst

This MR, remove **unread ** module from Code coverage (unread is only used for connection no need to compute it in CC)

Code coverage : Exclude unread module form CC (fix issue #1903)

---

verif/sim/cva6.py

Old and 'vanilla' versions of Spike do not have a `-v` args leading to a non explicit error message when verif/sim/`cva6.py` checks Spike version.
This fixes it.

[cva6.py] Detect old versions of Spike

---

docs/03_cva6_design/index.rst

GitHub Issues report 03 doc limitations. As it is not the main design document, we would like to notify that it is deprecated.

03 doc is deprecated

---

core/acc_dispatcher.sv
core/cva6.sv

This PR gives the accelerator dispatcher the ability to single-step the commit stage, which avoids retiring instructions on another commit port than port 0. This is needed if the acc dispatcher cannot keep up with simultaneous commits on both commit ports, as well as for precise timing of pipeline flushes.

Allow single-stepping of commit stage from acc dispatcher

---

docs/01_cva6_user/Programmer_View.rst
docs/01_cva6_user/RISCV_Instructions.rst
docs/01_cva6_user/RISCV_Instructions_RVZcmp.rst
docs/02_cva6_requirements/cva6_requirements_specification.rst

This PR updates the user guide and requirement specifications to add Zcmp extension Instructions.

[Docs] Add Zcmp Instructions in CVA6 user guide and requirement specifications

---

.gitlab-ci.yml

Fixed a typo in the fpga build job (introduced by fd12ee596c6cdec887a464dc9c8e2ad0125687ea) which was making the job fail.
Removed the output of the fpga build to avoid polluting the CI Job output.

Fix FPGA build report in Gitlab CI

---

verif/tests/custom/isacov/jump_test.S
verif/tests/testlist_isacov.yaml

This Mr add directed test to cover some corner cases in jump instructions, the test falied vs spike , because of lack of documentation in the memory mapping for the CVA6

Add directed Tests for jump instructions

---

verif/regress/smoke-tests.sh

this will prevent overwriting of first test log file to avoid
lost of Verilator build warning messages as this build is only
done once per configuration

smoke-tests.sh: run first I-ADD-01 test for cv64a6_imafdc_sv39

---

verif/sim/cva6.py

to avoid invalid escape sequence SyntaxWarning
since Python 3.12

cva6.py: use raw strings

---

core/csr_regfile.sv

DO NOT MERGE IN MASTER
This is a PR for fix release 5.0.0 (backport PR #1951)
Please create a branch from release 5.0.0 and change target of this PR to this new branch

csr_regfile.sv: use CVA6Cfg.ASID_WIDTH instead of AsidWidth (fix cv64a6)

---

core/cva6_rvfi.sv
corev_apu/tb/ariane_testharness.sv
corev_apu/tb/common/spike.sv
verif/sim/setup-env.sh
verif/tests/uvmt/base-tests/uvmt_cva6_base_test.sv

- Change RVFI implementation to get the `_d` and `_q` CSRs values
- Support ZSH shell in `setup-env.sh`
- Fix `UVM_VERBOSITY` in `veri-testharness`

[RVFI] Change CSR implementation

---

core/include/config_pkg.sv
docs/04_cv32a65x_design/source/parameters_cv32a65x.rst

Modify the params order inside the cva6_user_cfg_t to gather extension params in top of structure and micro-architecture params in the bottom

Modify the params order inside the cva6_user_cfg_t

---

verif/sim/Makefile
verif/sim/cva6.py
verif/sim/cva6.yaml
verif/tests/custom/spike_params/misa_csr_we.S

Add support for Spike cmd line parameters, bump core-v-verif to https://github.com/openhwgroup/core-v-verif/pull/2387. 
Add a test to test if misa_we Spike parameters is taken into account.

Support Spike Parameters in cva6.py and bump core-v-verif

---

.gitlab-ci.yml

65x gate simulation does not work due to WT cache in small configuration (this statement need to be confirmed). Lastest commits changed the DV_TARGET of CI to be 65x, gate simulation included. This makes the CI fail. This PR revert it for gate simulation.

[HOT FIX] Use cva6_embedded for gate simulation

---

.gitlab-ci.yml
.gitlab-ci/scripts/report_simu.py
verif/sim/cva6.py

* Adds more information on simulation job report
* Fixes issue https://github.com/openhwgroup/cva6/issues/1964 by using test name instead of source file name
* Avoid displaying the whole fpga synthesis on Gitlab job stdout

Logfile naming fix up and dashboard improvements

---

verif/docs/VerifPlans/AXI/runme.sh
verif/docs/VerifPlans/CVXIF/runme.sh
verif/docs/VerifPlans/FENCEI/runme.sh
verif/docs/VerifPlans/FRONTEND/runme.sh
verif/docs/VerifPlans/MMU_SV32/runme.sh
verif/docs/VerifPlans/csr_access/runme.sh

Fix incorrect paths to VPTOOL that prevented correct operation of `runme.sh` scripts in:
- verif/docs/VerifPlans/AXI
- verif/docs/VerifPlans/CVXIF
- verif/docs/VerifPlans/FENCEI
- verif/docs/VerifPlans/FRONTEND
- verif/docs/VerifPlans/MMU_SV32
- verif/docs/VerifPlans/csr_access

[DVplans] Fix broken paths to VPTOOL.

---

README.md

As th ebig change due to parametrization is over, I propose to remove the warning.

Remove parametrization Warning in README.md

---

core/cache_subsystem/cva6_icache.sv
core/frontend/frontend.sv
core/frontend/instr_queue.sv
core/include/ariane_pkg.sv
core/include/build_config_pkg.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a65x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdch_sv39_config_pkg.sv
core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
core/instr_realign.sv

This is the very first step of the integration of my superscalar feature.
1. It creates a new parameter to enable the feature. It will be added to the configuration structure later on. To ease the incremental rebase, it is kept as a localparam for now.
2. It makes instruction fetch generic so that it can fetch 32 or 64 bits of instructions.
See #1385

superscalar: fetch 64 bits

---

verif/sim/cva6.py

Avoid giving an empty spike cmd line param when none provided (introduced with https://github.com/openhwgroup/cva6/pull/2001)

Do not add spike cmd line param arg if no spike param provided

---

.gitlab-ci.yml

Synthesis of cv32a65x is not interesting *yet* and uses synthesis licenses.

ci: perform synthesis on cv32a6_embedded only

---

core/csr_regfile.sv

Change PMPCFG write behavior to support individual WARL fields. 
Fixes #1996, #1740
Note: I did not test this patch. Ideally, one of the reporters of #1996 and #1740 would check this before merging. Also, I never tested the PMP read-only feature, and I hope I did not break anything there (@michael-platzer).

Fix PMPCFG WARL behavior

---

Bender.yml
core/cache_subsystem/wt_cache_subsystem.sv
core/commit_stage.sv
core/controller.sv
core/cva6.sv
core/include/ariane_pkg.sv
core/include/build_config_pkg.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a65x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdch_sv39_config_pkg.sv
core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv

As discussed on Mattermost, this moves the DCacheType into the new parameterization. I am also sneaking in some other Bender changes that should not make troubles for other users.
A general note: We are maintaining quite a lot of different configurations, wondering whether that makes sense.
/cc @domenicw

Move `DCacheType` to config struct

---

util/user_config.py

https://github.com/openhwgroup/cva6/pull/2025 introduces a new case which was not tested yet.
This modifications makes the script able to handle this case.
By the way, for debugging purpose, the script can now be run with a single argument (the configuration) to print the configuration interpreted as Python variables.

fix util/user_config.py for DCacheType

---

core/cva6_rvfi_probes.sv
core/include/cv32a65x_config_pkg.sv

The goal is to remove all the localparams of config_pkg.sv. The work is not finished, to be continued

Clean-up 65x config_pkg.sv file by removing the localparams

---

core/decoder.sv

- add missing ZEXT.H for RV64
- fix ZEXT.H for RV32: bit[24:20] shall be 0

decoder.sv: fix ZEXT.H instruction (fix #1758, #1975, #2010)

---

core/csr_regfile.sv

Fix CSR behavior of MPP field in MSTATUS and SSTATUS. If the hypervisor extension is not enabled, MPP value 2'b10 must be reserved.
Fixes #1988

Fix reserved value in MPP

---

.gitignore
vendor/riscv/riscv-isa-manual/build/.gitignore
vendor/riscv/riscv-isa-manual/build/Makefile

- `.gitignore`: Enable Git visibility of the `build` subdir in vendorized ISA docs
- `vendor/riscv/riscv-isa-manual`: Add contents of the directory (contains a.o. a Makefile.)

[HOTFIX] Add missing 'build' directory belonging in vendorized ISA docs.

---

verif/env/corev-dv/cva6_illegal_instr.sv
verif/env/corev-dv/cva6_instr_test_pkg.sv

Those fixes are suggested in the context of supporting Cadence Xcelium simulator for cva6 verification.
The usage of keyword `inside` should be used as followed: **_variable_ inside {_values or range_}**. The `{}` brackets are mandatory.
See https://www.chipverify.com/systemverilog/systemverilog-constraint-inside
Concerning packages, the keyword **endpackage** should not be followed by `;`.
This has been check with VCS 2021.09.

[UVM] Few LRM compliance fixes

---

ci/build-hyp-riscv-tests.sh

The previous ref `920c137` does not seem to exist anymore. Update to the latest commit hash of `cva6-dev` (@ninolomata)

ci/hyp: Fix reference to riscv-hyp-tests

---

verif/env/uvme/cov/uvme_cvxif_covg.sv

This fix is suggested in the context of supporting Cadence Xcelium simulator for cva6 verification.
There is a VCS bug which does not support correctly the difference between `with` and `iff` keywords. A missing define needs to be added in order to allow xcelium to compile.
This has been check with VCS 2021.09.

Add ifdef for VCS fix (UNSUPPORTED_WITH)

---

core/cva6_accel_first_pass_decoder_stub.sv
core/decoder.sv
core/frontend/instr_queue.sv

The unused `SuperScalar` config had `SELRANGE` issues with `verilator`. Since `[1]` is not available in `SuperScalar = 0`.

Fix `SuperScalar` config and add `CVA6Cfg` to first pass decoder

---

verif/regress/install-spike.sh

This allows to pass a custom location for the Boost library when compiling Spike.
In some cases, it is not possible to install libraries in standard locations using package managers (apt, yum, etc). For example, when you do not have administrator rights on the host machine.

Allow to pass custom location for the Boost library for Spike

---

verif/tests/custom/isacov/illegal_isa.S

Add an illegal zext instruction to cover a line in Code coverage

ISA : Cover zext with instr[24:20] != 0

---

.gitlab-ci.yml
verif/regress/smoke-tests.sh
verif/sim/Makefile
verif/spike_configs/cv32a65x.yaml

Extend verif infrastructure to pick up YAML Spike configuration files if available.
The configuration files are expected to reside in verif/spike_configs/<target>.yaml.
Currently, only an example file for CV32A65X is provided  For other targets the "historical" approach is used.

Set up infrastructure for Spike YAML parameter tests

---

verif/sim/cva6.py

This PR fixes the issue where --iss_timeout was not being correctly passed to run_c, run_assembly, and run_elf functions. 
The default timeout value is set to 900 seconds (15 minutes) for EDA simulators (e.g., VCS).
Additionally, 
the Spike timeout value is now set to 1/10 of the --iss_timeout value. 
Similarly, the Verilator timeout value is set to --iss_timeout value multiplied by 35, maintaining the original ratio of 35.

Fixing --iss_timeout Passing and Setting Default Timeout Values for EDA Simulators

---

verif/sim/cva6.py

Running Spike first greatly aids in detecting any potential issues with ISG (e.g., RISCV-DV) generation, particularly following modifications to ISG that may still lack stability.

Running spike first to expedite error detection, especially on ISG

---

core/include/cv32a65x_config_pkg.sv
verif/tb/uvmt/uvmt_cva6_axi_assert.sv

Integrating HPDCache, this can help verifying the HPDCache modification: HPDCache parametrization for instance.
HPDCache gets a default configuration of WbufDirEntries and MshrWaysMshrSets parameters which constraints the MemTidWidth by:
MemTidWidth = max(log2(WbufDirEntries),log2(MshrWaysMshrSets)) + 1
As MemTidWidth must be equal or less than AxiIdWidth, MemTidWidth has been set to 4 waiting for the fine tuning of HPDCache parameters.
4 assertions have been disabled in AXI agent. They are impacted and need to be revisited to be adapted to HPDCache configuration (Github Issue #2076).

Switch from WT to HPDCache

---

verif/env/uvme/cov/uvme_axi_covg.sv
verif/env/uvme/uvme_cva6_cfg.sv
verif/tb/uvmt/uvmt_axi_assert.sv
verif/tb/uvmt/uvmt_cva6_axi_assert.sv
verif/tb/uvmt/uvmt_cva6_tb.sv

Parametrize AXI assertion module to disable invalid assertions with HPDCache.
Implementation of the HPDCache parameter in env_cfg to configure the AXI coverage model.

Configure AXI assertion and coverage model for easy utilization of WT and HPDcache

---

verif/sim/cva6.py

Correctly determine CVV hash when checking the expected checksum in verif/sim/cva6.py.
Calling "git log -1 -- PATH" will return the most recent commit that affected files in PATH.  In particular, "cd PATH ; git log" and "cd PATH ; git log -- ." may produce two distinct values if current commit is a merge point.
To avoid ambiguities, this change forces the use of project-level hashes on the CVA6 side, matching the behavior of core-v-verif PR #2442 (merged as commit 6af3cc55d).

[CI] Fix spike version checks on the CVA6

---

.github/workflows/ci.yml
verif/regress/cv32a6_tests.sh
verif/regress/cv64a6_imafdc_tests.sh
verif/regress/dv-riscv-arch-test.sh
verif/sim/cva6.py

This PR adds to the Github's CI a tests with the cv64a6_imafdc_sv39_hpdcache configuration.
This configuration uses 64-bit variant of the CVA6 with "deep" structures related to the data cache:
- Up to 8 inflight loads to the cache (and thus up to 8 miss requests to the memory)
- Up to 8 inflight write requests to the memory
It also restores the testing of the WB cache into the CI.
FIXME: In addition, this PR comments out some coverpoints in the AXI agent because of illegal bins that are not compatible with the HPDcache. These coverpoints expect that the cache uses a very small subset of IDs in AXI transactions, however the HPDcache is able to use a larger subset as it can issue multiple inflight requests to the memory (both reads and writes).
I pushed a first proposal for the Github's CI. …

Add in Github's CI a 64-bit configuration of the CVA6 using the HPDcache and restore WB cache test

---

core/include/cv32a65x_config_pkg.sv

The UVM configuration has been modified to remove the dependency to localparams from cva6_config package. This PR removes teh unused localparams.

Continue parametrization: as two localparams are not more used by UVM, remove them

---

verif/sim/Makefile

This is a temporary workaround, we have a lot of warning in the CC Job,so until investigating the cause of the warnings i'll disable them for now !!

Disable warnings in Code coverage Job

---

core/cache_subsystem/cache_ctrl.sv

This PR fixes a bug that could happen when a WB cache request gets killed while the _cache_ctrl_ is in the **WAIT_REFILL_VALID** state. When receiving the kill request, the _cache_ctrl_ went immediately back to the **IDLE** state. However,  the AXI request was already issued and could be associated to the following cache request, effectively sending back the wrong data to the CPU. By not going immediately back to **IDLE**, the cache waits for the AXI response to arrive before going back to **IDLE**. Since this case is quite rare, the bottleneck introduced by not going immediately back to **IDLE** is minimal. The bug was found while running the WB TB. In this screenshot, the first request for addresss 0x10D1C gets killed and the cache_ctrl starts working on the next requets. 
Later, the …

Fix bug when killing WB cache request

---

docs/06_cv32a65x_riscv/src/machine.adoc

Following the #2074 PR, the specification is update to give information on some mstatus bits.

Add SPP, SIE, SPIE, MXR and SUM description when S-mode is not implemented.

---

core/cva6_mmu/cva6_mmu.sv
core/cva6_mmu/cva6_ptw.sv
core/cva6_mmu/cva6_shared_tlb.sv

Add reserved bits to PTE structure be used in sv39 and sv39x4 only
Check that they are 0, otherwise the PTE is considered invalid

Invalid pte reserved

---

verif/env/uvme/reg/cva6_csr_reg_predictor.sv

After some modification on the rvfi agent, now the package is sent when trap = 0 only !!

CSR REG PREDICTOR : Skip getting package on traps

---

verif/tb/core/uvma_cva6pkg_utils.sv

Fxx issue openhwgroup/core-v-verif#2444: Fill the 'dram', 'dram_base' and 'dram_size' fields of the st_core_cntrl_cfg structure with reliable values.
The corresponding fields in the (virtual) base class of st_core_cntrl_cfg are declared with 'rand' modifier.  In particular, the 'dram' field could occasionally take value 1'b1, causing the Spike tandem interface to pass the random values of DRAM base address and DRAM size to Spike.  When DRAM size is not a strictly positive multiple of PAGE_SIZE, Spike throws a runtime exception causing issue openhwgroup/core-v-verif#2444.
NOTE: The comment added in the code is there purposely as a reminder that we need an overhaul of memory layout management.

[UVM TB] Initialize information about DRAM presence, address and size.

---

verif/regress/dhrystone.sh

When compiling dhrystone with gcc-14, there is below errors
```
Tue, 28 May 2024 11:55:02 INFO     GCC Version: 14.0.1
Tue, 28 May 2024 11:55:02 INFO     ../tests/riscv-tests/benchmarks/dhrystone/dhrystone_main.c: In function 'main':
../tests/riscv-tests/benchmarks/dhrystone/dhrystone_main.c:120:7: error: implicit declaration of function 'Proc_5' [-Wimplicit-function-declaration]
120 |       Proc_5();
|       ^~~~~~
../tests/riscv-tests/benchmarks/dhrystone/dhrystone_main.c: At top level:
../tests/riscv-tests/benchmarks/dhrystone/dhrystone_main.c:242:1: error: return type defaults to 'int' [-Wimplicit-int]
242 | Proc_1 (Ptr_Val_Par)
| ^~~~~~
```
As [Porting to GCC 14](https://gcc.gnu.org/gcc-14/porting_to.html) says, 
> For backwards compatibility, GCC 13 and earlier diagnosed use of …

fix gcc-14 compile error on dhrystone: implicit-function-declaration, implicit-int

---

config/gen_from_riscv_config/scripts/libs/utils.py

- format with black
- fix typos to get coherent .md/.rst files

gen_from_riscv_config utils.py: format and fix typos

---

config/riscv-config/cv32a65x/generated/custom_gen.yaml
config/riscv-config/cv32a65x/generated/isa_gen.yaml
config/riscv-config/cv32a65x/spec/custom_spec.yaml
config/riscv-config/cv32a65x/spec/isa_spec.yaml

- Add Zba, Zbb, Zbc and Zbs extensions (FIXME: implied B not handled yet)
- Update MVENDORID
- Update MARCHID
- Fix MSTATUS legal values and MSTATUS reset value
- Remove over-specification of unimp fields of MSTATUS
- Define the reserved bits of DCACHE as read-only 0.
- Remove unnecessary quotes.
- Regenerate files under cv32a65x/generated.

[riscv-config] Fix issues in CV32A65X input spec and regenerate output.

---

verif/sim/cva6.py

When Spike is not aligned with built Spike, Spike need to be cleaned-up. This PR allow to give information to the user.

Give information on how to clean-up Spike before build

---

core/cache_subsystem/cache_ctrl.sv
corev_apu/tb/tb_wb_dcache/hdl/cv32a6_config_pkg.sv

This PR adapts the WB cache so that it works with the 32 bits versions of CVA6. It was tested using the updated TB from PR #2151 and should also solve the issue #2006. It works by aligning the data to and from the AXI bus on the 64 bits of the bus (lower or upper 32 bits depending on the address).

32 bits WB cache

---

verif/env/uvme/cov/uvme_exception_covg.sv

Hello, this's a fix : we should only ignore exception code if there's a trap in exc code 0

Ignore instr_addr_misaligned exception only when also there's a trap

---

docs/06_cv32a65x_riscv/priv-isa-cv32a65x.html
docs/06_cv32a65x_riscv/src/machine.adoc

xPELP fields were added during last month in RISC-V spec

doc cv32a65x: update xPELP fields in mstatus

---

verif/sim/Makefile
verif/tb/core/uvma_cva6pkg_utils.sv

- Disabling MISA WE as cva6 does not allow writes
- Add YAML report for all the tests

Disable MISA WE in Reference Model

---

config/riscv-config/Makefile
vendor/patches/riscv/riscv-config/0001-enable-implied-B-ext.patch
vendor/patches/riscv/riscv-config/0002-add-mstatus-UBE-bit.patch
vendor/patches/riscv/riscv-config/0003-add-mtval-roconst0-schema.patch
vendor/riscv/riscv-config/riscv_config/isa_validator.py
vendor/riscv/riscv-config/riscv_config/schemas/schema_isa.yaml

- Enable 'B' extension if Zba, Zbb and Zbs are all present.
- Add misa.ube bit description to ISA schema (rv32 and rv64).
- Update spec Makefile to remove intermediate files and logs.
- Add 'read-only constant 0' alternative for mtval.
- Add corresponding riscv-config vendor patches.

Update riscv-config infra to better match expressivity needs of CV32A65X.

---

verif/sim/cov-exclude-mod.lst

This MR exclude the HPDCACHE module from Code coverage report

Exclude HPD cache module from code coverage

---

core/csr_regfile.sv

csr_regfile.sv: if no U-mode, mcounteren does not exist (fix #2221)

---

.gitlab-ci/expected_synth.yml
core/csr_regfile.sv

Do not gen exception when writing into MTVAL
The related logic will be removed in following PRs.

MTVAL is read-only zero when TvalEn = 0

---

core/csr_regfile.sv

force 0 in tw field when writing mstatus

csr_regfile.sv: if no U-mode, mstatus.tw is read-only 0 (fix #2228)

---

verif/env/corev-dv/simulator.yaml

This PR aims at adding xrun rule in `verif/env/corev-dv/simulator.yaml`, which is a step to support Cadence xcelium simulator while using riscv-dv instruction generator.
It contributes to task  #1829

[Xcelium flow] corev dv yaml

---

corev_apu/tb/ariane_tb.sv
corev_apu/tb/rvfi_tracer.sv
verif/env/uvme/uvme_cva6_pkg.sv
verif/env/uvme/vseq/uvme_axi_fw_preload_seq.sv
verif/tb/uvmt/cva6_tb_wrapper.sv

This PR aims at cleaning the DPI import in cva6 repository. It is preferable to let void at import and to not cast the result of the function when it is called.

[Xcelium flow] Clean DPI void function import

---

verif/sim/cva6.yaml

This PR aims at adding xrun rule in`verif/sim/cva6.yaml`, which is a step to support Cadence xcelium simulator **_without_** using riscv-dv instruction generator.
It contributes to task  #1829

[Xcelium flow] sim yaml

---

verif/sim/Makefile

This PR aims at updating the rules into `cva6/verif/sim/Makefile` to support **uvmt_cva6_tb** (in `cva6/verif/tb/uvmt`) on **Cadence Xcelium**.
Nevertheless, this PR is not enough to launch _cva6.py_ with _xrun_uvm DV_SIMULATOR_. Further PRs will follow.

[Xcelium flow] xrun uvm rules

---

docs/04_cv32a65x/index.rst
docs/04_cv32a65x/riscv/priv.rst
docs/04_cv32a65x/riscv/unpriv.rst

To have two different HTML pages for tailored RISC-V spec (one for unpriv and one for priv) on ReadTheDocs

cv32a65x doc: split unpriv and priv HTML pages

---

core/include/cv64a6_mmu_config_pkg.sv

RTL does not support >16 entries yet.

cv64a6_mmu: set NrPMPEntries to 16 (fixes #2244)

---

verif/env/uvme/cov/uvme_exception_covg.sv
verif/env/uvme/reg/cva6_csr_reg_block.sv
verif/env/uvme/reg/cva6_csr_reg_file.sv
verif/env/uvme/uvme_cva6_cfg.sv
verif/sim/cva6.hvp
verif/tests/custom/csr_embedded/csr_counters_overflow.S
verif/tests/custom/csr_embedded/csrcs_test.S
verif/tests/custom/csr_embedded/csrcsi_test.S
verif/tests/custom/csr_embedded/csrrst_test.S
verif/tests/custom/csr_embedded/csrrw_test.S
verif/tests/custom/csr_embedded/csrrwi_test.S

This MR has multiple changes on the CSRs verification env :
1. Update HVP remove write coverage on RO CSRs, also remove unsupported 
2. Update CSR tests
3. Update exception coverage
4. Update CSRs coverage model base on new spec

CSR verification : modify CSR env verif based on new specification

---

Makefile

This PR aims at updating the rules into `cva6/Makefile` to support **ariane_testharness** on **Cadence Xcelium**.
Nevertheless, this PR is not enough to launch `make xrun_all`. Further PRs will follow.

[Xcelium flow] xrun testharness rules

---

vendor/pulp-platform/tech_cells_generic/src/rtl/tc_sram.sv

This PR aims at fixing sram initialization in **tc_sram** memory model.
Initialization of SRAM in tc_sram.sv model is exceeding tool limit at runtime. Simple fix is to use a for loop instead of assigning the whole signal.

[Xcelium flow] Fix initialization of memory array for simulation

---

corev_apu/fpga/src/bootrom/src/main.c
corev_apu/fpga/src/bootrom/src/uart.c
corev_apu/fpga/src/bootrom/src/uart.h

In Keystone (https://github.com/keystone-enclave/keystone), we'd like to be able to run automated CI tests for all of our platforms to make sure that code changes don't break things, as much as possible. One difficulty is that many boards don't support updating firmware remotely. For CVA6 specifically, the firmware update process involves removing the microSD card, flashing a new image, and inserting it again. This does not work well for our remote tests.
This PR implements a simple UART-based updater in the bootrom. By hitting a key during boot, a user can then transfer an image of a specific size directly to memory and boot it. We plan to transfer a uboot image with TFTP capabilities, allowing us to then quickly flash the much bigger OS image as well.

Implement simple uart-based updater for the bootrom

---

core/load_store_unit.sv

This PR changes the fault type triggered on an LSU overflow to be compliant with the RISC-V privileged spec, which requires a page fault exception instead of an access fault. Fixes #2272.

Use correct fault type for VLSU overflow

---

core/decoder.sv

bits 22 and 23 must be equal to 0 for some B instructions

decoder.sv: add checks for some B instructions (fix #2276)

---

core/cache_subsystem/cva6_hpdcache_icache_if_adapter.sv

- I will discard PR #2238  and work on it here.
- changed base branch from `master` to `feature/interconnect`
- The parts highlighted in light pink are the ones we want to implement in this PR.

Feat: add add cva6_hpdcache_icache_if_adapter (supports the simplified icache kill mechanism)

---

core/csr_regfile.sv

The possible legal value depend on the cva6 config: RVU, RVH, RVS.
When writing an illegal value, the previous mstatus.mpp value is kept

Fix mstatus.mpp in relation to the possible legal values

---

Makefile

Add vcs `-full64` compile option back to make it same as above `vlogan` commands.

Add vcs -full64 compile option back

---

verif/env/uvme/uvme_cva6_cntxt.sv
verif/env/uvme/uvme_cva6_env.sv
verif/env/uvme/uvme_cva6_pkg.sv
verif/env/uvme/vseq/uvme_axi_fw_preload_seq.sv
verif/tb/uvmt/uvmt_cva6_pkg.sv

Refer to [core-v-verif's](https://github.com/openhwgroup/core-v-verif) below PR(s), this PR updates cva6 testbench accordingly.
https://github.com/openhwgroup/core-v-verif/pull/2480
https://github.com/openhwgroup/core-v-verif/pull/2481
https://github.com/openhwgroup/core-v-verif/pull/2482

Update uvml_mem use for core-v-verif's PR: 2480/2481/2482

---

verif/sim/Makefile

This a fix to actived the tandem mode only by export SPIKE_TANDEM=1, the param in the testbench has been changed but not in the Makefile

Makefile : passing the tandem_enable value into UVM testbench

---

core/cva6.sv
core/ex_stage.sv
core/issue_read_operands.sv
core/issue_stage.sv

With this PR, CVA6 can be configured to be superscalar.
There is still work in progress to improve performance further:
Make *superscalar* a configuration parameter instead of a `localparam`

superscalar add second ALU

---

verif/tests/custom/isacov/illegal_isa.S

This add another illegal test to cover ctz bitmanip instruction with [24:20] != 5'h1, to increase decoder's code coverage

Add illegal instruction to cover corner case in decoder

---

verif/regress/benchmark.sh

Fix #2250
Fixes to make benchmark tests compile since we not longer use their own Makefile

Fix benchmark.sh with correct GCC options and order (Fix #2250)

---

.gitlab-ci.yml

This job can sometime fail because of an unstable serial connection.
Most of the time, retrying the job fixes the issue, hence this PR.

Retry FPGA boot in CI when failed

---

docs/04_cv32a65x/riscv/priv-isa-cv32a65x.html
docs/06_cv64a6_mmu/riscv/priv-isa-cv64a6_mmu.html
docs/riscv-isa/src/machine.adoc

For CVA6, add table:
Encoding of A field in PMP configuration registers

machine.adoc: add missing table

---

core/issue_read_operands.sv

This is a bug fix:
- No speculative instructions after a CSR instruction
- Do not issue CSR instructions on the second issue port

superscalar: do not issue CSR with another instruction

---

README.md

cva6/gcc-toolchain-builder has been renamed to cva6/toolchain-builder in the main repo. 
README file should be aligned with this update.

Update README.md : Updated gcc-toolchain-builder path

---

corev_apu/tb/ariane_testharness.sv

Strings cannot be initially assigned to an integer without a cast.
Found by using Slang on CVA6 via [sv-tests](https://github.com/chipsalliance/sv-tests). This is the only error that Slang does not like, but it also prints some more warnings that probably should be fixed:
```
../../../third_party/cores/ariane/core/cache_subsystem/axi_adapter.sv:204:29: warning: finish argument must have value of 0, 1, or 2 [-Wfinish-num]
else $fatal("Bursts of atomic operations are not supported");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../third_party/cores/ariane/core/cache_subsystem/axi_adapter.sv:235:29: warning: finish argument must have value of 0, 1, or 2 [-Wfinish-num]
else $fatal("Bursts of atomic operations are not supported");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```

Fix non-standard usage of SystemVerilog

---

verif/README.md

The verif readme is out of date and its instructions are both duplicate from the root and toolchain README and are misleading (see https://github.com/openhwgroup/cva6/issues/2230)
This remove the duplicate part leaving only the verif/coverage-oriented instructions and potentially useful verif env variable with updated values.

Remove duplicate and out of date infos on verif readme

---

docs/01_cva6_user/CSR_CV64A6_MMU.rst
docs/01_cva6_user/CSR_CV64A6_MMU_list.rst
docs/01_cva6_user/CSR_Performance_Counters.rst
docs/01_cva6_user/CVX_Interface_Coprocessor.rst
docs/01_cva6_user/Interfaces.rst
docs/01_cva6_user/Introduction.rst
docs/01_cva6_user/Programmer_View.rst
docs/01_cva6_user/RISCV_Instructions_RV32A.rst
docs/01_cva6_user/RISCV_Instructions_RV32C.rst
docs/01_cva6_user/RISCV_Instructions_RV32I.rst
docs/01_cva6_user/RISCV_Instructions_RV32M.rst
docs/01_cva6_user/RISCV_Instructions_RV32ZCb.rst
docs/01_cva6_user/RISCV_Instructions_RVZba.rst
docs/01_cva6_user/RISCV_Instructions_RVZbb.rst
docs/01_cva6_user/RISCV_Instructions_RVZbc.rst
docs/01_cva6_user/RISCV_Instructions_RVZbs.rst
docs/01_cva6_user/RISCV_Instructions_RVZcmp.rst
docs/01_cva6_user/RISCV_Instructions_RVZicond.rst
docs/01_cva6_user/index.rst

In the CVA6 user manual, two configurations are already explicit. 
This commit adds another one : CV64A6_MMU.
This MR is independant from the MR adding design documentation for CV64A6_MMU

Add CV64A6_MMU core in user manual

---

verif/env/uvme/uvme_cva6_cfg.sv
verif/tests/custom/csr_embedded/csrcs_test.S
verif/tests/custom/csr_embedded/csrcsi_test.S
verif/tests/custom/csr_embedded/csrrwi_test.S
verif/tests/custom/isacov/isa_test.S

This MR related to increase pmp entries to be aligned with the last RTL modification

Increase supported PMP entries in UVM testbench

---

.gitlab-ci.yml
Makefile
config/gen_from_riscv_config/cv32a65x/spike/spike.yaml
corev_apu/tb/common/spike.sv
verif/regress/install-spike.sh
verif/sim/Makefile
verif/sim/cva6.py
verif/sim/cva6.yaml
verif/sim/cva6_spike_log_to_trace_csv.py

- always pass target info to 'make spike'
- add Yaml file arg only if target-specific file exists
- update core-v-verif
- update CV32A65X Spike Yaml configuration.

[Spike Yaml] Integrate Spike Yaml support.

---

verif/sim/Makefile

This PR fixes spurious CI failures during tandem job executions.
The root cause was an implicit path used to access the yaml-cpp shared library: instead of accessing the local copy of libyaml-cpp.so, the RTL simulators were accessing acopy of the lib located in the build space of Spike, and that space was eventually reclaimed for other CI jobs.

[Spike Yaml] HOTFIX: Add libyaml-cpp to preload list of RTL simulators.

---

.gitlab-ci.yml
verif/sim/cva6.py

Enable Spike Tandem on gen tests in CI.
Display tandem result on the gen tests logs.
Also, remove log collection from heavy tests since they are temporarily not retrieved by the dashboard.

Enable tandem on gen tests in ci

---

verif/regress/dv-csr-embedded-tests.sh

This MR increase simulation time for CSR tests, after enabling superscalar sumilation time increase and this lead to timeout error for some CSR tests

Increase simulation time on CSR tests

---

docs/04_cv32a65x/riscv/priv-isa-cv32a65x.html
docs/06_cv64a6_mmu/riscv/priv-isa-cv64a6_mmu.html
docs/riscv-isa/src/machine.adoc

Simplify the PMA by being always idempotent and without cache

Update PMA: cv32a65x is always idempotent and without caches

---

verif/env/uvme/uvme_cva6_cfg.sv

Set the HPDCache field in the environment config to be used by other verification components.

Enable HPDcache in the UVM config

---

.gitlab-ci/scripts/report_benchmark.py

https://github.com/openhwgroup/cva6/commit/4a223bee46ae98b46cd3243da45316ebb3823716 introduced a change in the dhrystone cycle count. The dhrystone required cycles count has to be changed accordingly.

change required dhrystone cycles count value

---

verif/env/uvme/cov/uvme_exception_covg.sv
verif/env/uvme/uvme_cva6_cfg.sv

This MR add mmu present parameter in UVM testbench, and use it to exclude page fault exceptions

Exclude page fault exceptions if mmu isn't supported

---

.gitlab-ci.yml
Makefile
README.md
verif/regress/install-spike.sh
verif/sim/Makefile
verif/sim/cva6.py

Add diagnostics messages to verif/sim/cva6.py to help tracking intermittent Spike failures seen in thales-invia CI runs.

[CI DEBUG] Track cause of failures in Spike version check.

---

common/local/util/instr_tracer.sv
common/local/util/sram.sv
core/cache_subsystem/cva6_hpdcache_wrapper.sv

This PR provides several fixes that allow Xcelium Cadence simulator to compile.
It provided the followings fixes:
- init_val data_type in sram
- size of scoreboard parameter for trace: at run time, not enough memory is dedicated (get trace output clean)
- init hpdcache config in parameter type
Nevertheless, this PR is not enough to launch cva6.py with xrun-uvm or xrun-testharness DV_SIMULATOR. Further PRs will follow.

[Xcelium flow] Xrun compile fixes

---

docs/06_cv64a6_mmu/index.rst
docs/index.rst

This PR adds the RISC-V Instruction Set Manual tailored for cv64a6_mmu.

cv64a6_mmu: add RISC-V ISA documentation to main page

---

config/gen_from_riscv_config/scripts/libs/utils.py
config/riscv-config/cv32a65x/generated/isa_gen.yaml
config/riscv-config/cv32a65x/spec/isa_spec.yaml

Align the specification of the PMPADDRn and PMPCFGn registers of CV32A65X on current design:
- all 64 PMP entries are accessible
- only 8 lowest-numbered entries are modifiable
- PMP entries 8 through 63 are read-only zero.
- bits 6:4 of lowest 8 PMPnCFG fields (located in PMPCFG0 and PMPCFG1) are read-only zero.

[riscv-config] Update PMP definitions in cv32q65x spec

---

config/gen_from_riscv_config/cv32a65x/csr/csr.adoc
config/gen_from_riscv_config/scripts/libs/utils.py
docs/04_cv32a65x/design/design-cv32a65x.html

- Correctly handle pipes in table cells
- Show "reserved" as italic instead of bold

docs: more fixes

---

config/riscv-config/cv32a65x/generated/platform_gen.yaml
config/riscv-config/cv32a65x/spec/platform_spec.yaml
vendor/riscv/riscv-config/riscv_config/schemas/schema_platform.yaml

Extend riscv-config to allow representing memory maps.  Add memory map information to CV32A65X platform spec.

[riscv-config] Add memory map entry to platform schema and to CV32A65X platform spec.

---

.gitlab-ci.yml
.gitlab-ci/scripts/report_spyglass_lint.py

since https://github.com/openhwgroup/cva6/commit/12be3adb81ef37f17ef9ac958fec57e4a01a6dcd, it is possible to have a "pass" report but the job will fail because of the diff between the 2 reports (see pipeline 46167 on the [dashboard](https://riscv-ci.pages.thales-invia.fr/dashboard/)).
This fixes it using the report "failed" field instead of running diff.
Also added the reference summary in gitlab artifacts for easier investigation.

fix Spyglass job falsely reporting fail

---

verif/env/uvme/uvme_cva6_sb.sv

This is a fix for an smoke-test fatal on a 64 config

Configure uvm scoreboard to bypass issue on 64-bit config

---

Makefile
config/gen_from_riscv_config/cv32a65x/spike/spike.yaml
config/riscv-config/cv32a65x/generated/isa_gen.yaml
config/riscv-config/cv32a65x/spec/isa_spec.yaml
verif/regress/install-spike.sh
verif/sim/Makefile
verif/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv

Fix incorrect structure of the Spike Yaml file.
Fix ISA strings in riscv-config spec and outputs.
Fix Questa tandem invocation.
Add 100 cycle delay after end of test to settle outstanding AXI requests when using UVM.

[Spike tandem] Fix Yaml config files for CV32A65X. Fix Questa tandem. Add workaround for AXI end-of-test asserts.

---

core/alu.sv
core/serdiv.sv
spyglass/reference_summary.rpt

Signed argument is passed to  system function call, or unsigned
argument passed to  system function call.

spyglass: remove WRN_1024 warnings

---

docs/_static/theme_overrides.css
docs/conf.py

RTD theme's default is 800px as max width for the content.
Expand full width of the view-port so that tables are more exposed.
Comment from yocto project theme_overrides.css

docs: expand wy-nav-content width to edge of screen

---

config/gen_from_riscv_config/cv32a65x/spike/spike.yaml
core/cva6_rvfi.sv
core/include/rvfi_types.svh
verif/env/uvme/cov/uvme_axi_covg.sv
verif/env/uvme/cov/uvme_axi_ext_covg.sv

* Connect intr as it was not connected on the RVFI tracer
* Lower verbosity to uvme_axi_covg
* Add unified_traps as a param for yaml

[RVFI] Connect RVFI.intr to enable interrupts on TANDEM

---

verif/sim/cva6.py

In the case where the tandem yaml report was not created, the CI post processing scripts were not able to detect the failure of a test.
This PR allows creating the tandem report before the test execution to avoid the issue.

fix simulation errors not detected on ci w/ tandem

---

.gitlab-ci/scripts/report_benchmark.py

after commit 111df66 the CVA6 configuration used for Dhrystone benchmark is rv64gc_zba_zbb_zbs_zbc instead of rv64imafdc_zicsr_zifencei
therefore the number of cycles is reduced

report_benchmark.py: fix Dhrystone cycles after PR #2484

---

verif/sim/link.ld
verif/tests/custom/common/test.ld

Fix broken heavy tests by aligning linker script content of the verification platform.
Future work: clean up linker script ecosystem so it uses a single verification linker script (with non-conflicting extensions if/where needed).

[interrupt verification] Add .uvmif support to global verif linker script

---

.gitlab-ci.yml
.gitlab-ci/scripts/report_benchmark.py
verif/regress/coremark.sh
verif/regress/dhrystone.sh
verif/regress/smoke-gen_tests.sh
verif/regress/smoke-tests.sh

Spike Tandem is used for all jobs.
As Spike Tandem does not work with Verilator, Verilator is replaced by VCS.
cv64_MMU configuration jobs are removed.
VCS-uvm is preferred to vcs-testharness.

Modify ci to always check with Tandem and promote UVM TB use

---

.gitlab-ci.yml

Coremark is too long for short regression, 21 minutes. Swapt with Dhrystone which i shorter, 10 minutes

put dhrystone in smoke job group and coremark in regress job group

---

core/frontend/btb.sv

Fixed a multiple driver error in the branch target buffer, when CVA6.FpgaEn == 1.

BUG FIX: Fixed btb for FPGA targets

---

config/gen_from_riscv_config/cv32a65x/csr/csr.adoc

Provide a CSR design design spec extended with PMPnCFG details.

[pmpcfg detailed spec] Add proposed CSR spec output.

---

.gitlab-ci.yml
.gitlab-ci/scripts/report_benchmark.py
verif/regress/coremark.sh
verif/regress/dhrystone.sh

Display  report at the end of dhrystone and coremark executions
Run benchmarks in single and dual issue
Use bigger cache config

Run benchmarks in single and dual issue config with big caches

---

.gitlab-ci.yml
.gitlab-ci/scripts/report_benchmark.py
verif/regress/dhrystone_smoke.sh

- Cache can slow down execution, enlarging them generates better bench results.
- As cv32a65x targets embedded devices, switch to -Os compiler option to reduce code size

cv32a65x CI: Enlarge cache to increase bench result and switch from -O3 to -Os compiler option

---

verif/env/uvme/cov/uvme_interrupt_covg.sv
verif/env/uvme/uvme_cva6_cfg.sv
verif/env/uvme/uvme_cva6_env.sv
verif/env/uvme/uvme_cva6_sb.sv
verif/regress/coremark.sh
verif/regress/dhrystone.sh
verif/regress/dv-riscv-arch-test.sh
verif/regress/dv-riscv-compliance.sh
verif/regress/dv-riscv-tests.sh
verif/tests/uvmt/base-tests/uvmt_cva6_base_test.sv

Add performance_mode to be set in line command using +tb_performance_mode to speed up simulation time by disabling functional coverage, agents logger, rvfi csr checks and scoreboard. 
This +tb_performance_mode switch has also been added in related regression tests

Performance tb

---

docs/04_cv32a65x/config/config.adoc
docs/04_cv32a65x/riscv/priv-isa-cv32a65x.html
docs/04_cv32a65x/riscv/unpriv-isa-cv32a65x.html
docs/06_cv64a6_mmu/config/config.adoc
docs/riscv-isa/src/colophon.adoc
docs/riscv-isa/src/counters.adoc
docs/riscv-isa/src/machine.adoc
docs/riscv-isa/src/priv-preface.adoc
docs/riscv-isa/src/riscv-privileged.adoc
docs/riscv-isa/src/riscv-unprivileged.adoc
docs/riscv-isa/src/rv64.adoc
docs/riscv-isa/src/supervisor.adoc
docs/riscv-isa/src/zpm.adoc

since last riscv-isa-manual update (CVA6 commit 3059b1cb2):
- Privileged Architecture 1.13 ratified
- minor documentation changes
- wavedrom file renamed to .edn

update riscv-isa-manual to riscv-isa-release-2c07aa2-2024-10-18

---

.gitlab-ci/scripts/report_benchmark.py
.gitlab-ci/scripts/report_builder.py

This modification allows:
- printing the results in the terminal
- running the script from the terminal (without the environment variables from CI)
The yaml report is only built in CI, but the results are always printed.
Pretty printing is not a goal of this PR and could be added later on.

ci: print results in job logs

---

core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv

The parameter `CVA6ConfigTechnoCut` is undefined and causes elaboration errors. Align this with the other configurations and set it to constant `0`.

cv64a6_imafdch_sv39_wb_config: Fix undefined parameter

---

core/acc_dispatcher.sv

The controller flushes the pipeline and all the unissued instructions in the presence of instructions with side effects (e.g., `fence`).
The accelerator dispatcher buffer (now used with the Ara RVV Vector processor) is flushed when this happens and avoids accepting a new instruction in that cycle, but it does not prevent the actual issuing of instructions during a flush cycle.
This fix avoids the issue during a flush cycle.

[Vector] :bug: Fix `fence` bug 

---

core/cache_subsystem/cache_ctrl.sv

For `XLEN = 64`, some tools (e.g. VCS) still elaborate the offset generation block for `XLEN = 32`, throwing an elaboration error (illegal bit access). Hence, VCS can currently not build the 64-bit WB configuration of CVA6. Fix this by generating the AXI offset in an equivalent, parameter-agnostic and tool-friendly way.

cache_ctrl: Generalise AXI offset generation

---

docs/design/design-manual/source/cva6_frontend.adoc
docs/design/design-manual/source/cva6_id_stage.adoc
docs/design/design-manual/source/design.adoc

Update the documentation of cv32a65x to make it superscalar.
This first PR only updates the documentation of the frontend and decode stages.

document superscalar cv32a65x (frontend + decode)

---

CONTRIBUTING.md

As mentioned in the meeting on 2024-10-25: https://mattermost.openhwgroup.org/all-users/pl/eosp73km5iggtdbaidkdp7p83w

mention that PR must be updated in CONTRIBUTING.md

---

corev_apu/tb/common/mock_uart.sv

The former kind of signal initialization generates compilation errors using VCS to simulate the design due to multiple drivers driving those signals. Since these signals are handled inside the `always_ff` block, they can just be reset.

Initialize `mock_uart` signals on reset

---

verif/regress/dhrystone.sh

Fix the dhrystone execution script so that any ISS options accumulated in shell variable `DV_OPTS` are duly propagated to `cva6.py`.

[benchmarks] Pass DV_OPTS to dhrystone execution.

---

core/acc_dispatcher.sv

Fix Ara's exception propagation using correct `exception_t` data type.

RVV: :bug: fix exception propagation from Ara

---

core/csr_regfile.sv

Since #2346, if Hypervisor extension is enabled, the logic required to properly trap to S mode is excluded. Fix this by adjusting the if condition.

csr_regfile: Fix S-mode traps when H extension is enabled

---

config/gen_from_riscv_config/cv32a60x/spike/spike.yaml
config/gen_from_riscv_config/cv32a65x/spike/spike.yaml
config/riscv-config/cv32a65x/generated/isa_gen.yaml
config/riscv-config/cv32a65x/spec/isa_spec.yaml

Update `riscv-config` spec files and Spike Yaml file for CV32A65X.
Bump CVV to change Spike default PMP granularity to 8 and to include corresponding Spike Yaml parameter.

Increase Spike PMP granularity to 8.  Update yaml spec files accordingly.

---

.gitlab-ci.yml
core/Flist.cva6_gate
pd/synth/Makefile
pd/synth/hpdcache_sram_1rw_00000006_0000001c_00000040.sv

Update hpdcache_sram black box which changed with bump of hpdcache repository

Fix gate simulation: Update hpdcache_sram black box

---

.gitlab-ci.yml
.gitlab-ci/scripts/report_simu.py
.gitlab-ci/scripts/report_tandem.py
verif/regress/smoke-gen_tests.sh

* Due to the increased count of warnings, provide tail of log instead of head on the dashboard
* Add tandem yaml report file on the jobs reports
* Reduce UVM Verbosity on smoke gen tests

improve dashboard-provided log

---

.readthedocs.yaml

Install the required packages for read the docs build.
This PR aims at fixing the documentation build on the infrastructure side.
The build process is still broken: executing `make -C docs` will throw an error, this will be solved on another pull request.

Provide the correct environment for doc build

---

verif/sim/cva6.py

check version check seem to have been commented by mistake, this pr fixes it

check spike version in cva6.py

---

core/cva6_mmu/cva6_mmu.sv

As mentioned in the spec, we need to perform a canonical check on the virtual address for instruction fetch, load, and store. If the check fails, it will cause the page-fault exception. 
This PR fixes the above two:
1) changes INSTR_ACCESS_FAULT to INSTR_PAGE_FAULT
2) Adding virtual address check on data accesses as well

bug fix: canonical check on virtual address for data accesses

---

core/csr_regfile.sv
core/cva6.sv

Only the first commit port is used by CSR.

csr: reduce to one commit port

---

.gitlab-ci.yml

This allows a more grained management of CI resources.

ci: use different variables for runner tags

---

core/cva6_rvfi.sv

According to RVFI spec, trap is for synchronous trap only, so we should check MCAUSE msb to distinguish between synchronous and asynchronous

RVFI : For synchronous trap, check mcause MSB also

---

verif/env/uvme/cov/uvme_interrupt_covg.sv

to be more precise should sample interrupt coverage when rvfi.intr in asserted.

Interrupt cov : sample when rvfi.intr is asserted

---

core/csr_regfile.sv

In RVH, traps and interrupts are currently delegated if `hxdeleg` is set but `mxdeleg` is not (`mxdeleg` is not considered in the else-if-block condition in old line 1807), violating the spec ("A trap/irq *that has been delegated to HS-mode (using `mxdeleg`)* is further delegated to VS-mode if the corresponding `hxdeleg` bit is set"). Fix and simplify the corresponding logic.
@ninolomata can you confirm this?

csr_regfile: Fix irq/ex delegation in RVH

---

core/cache_subsystem/wt_axi_adapter.sv

I think this bug was introduced by a [copy-paste mistake](https://github.com/openhwgroup/cva6/commit/9877af5eb6e28700adc32dc7229622e2afa618f1#diff-09a66c4298fd443b5dd467e6e8eac16c86a80c41ca9948b227c3c03ce707f8a9L180). 
`AxiRdBlenDcache` -> `AxiRdBlenIcache`

:bug: Fix icache AXI read len

---

core/cache_subsystem/wt_dcache_wbuffer.sv

If the data user signal is disabled and the user bus width is reduced, the slice operator into the user field will cause elaboration errors. Since the faulty else block is anyways without effect, just remove it.

wt_dcache_buffer: Avoid out-of-range user signal access

---

core/cache_subsystem/wt_axi_adapter.sv

#1571 zero-extended the `paddr`s to match the `axi_addr` width and thus fix lint warnings. However, this breaks elaboration  if `AxiAddrWidth <= PLEN`. To fix lint warnings without breaking parametrisation, use explicit casts to pad/truncate as required.

wt_axi_adapter: Fix addr width parametrisation

---

core/cva6_mmu/cva6_mmu.sv
core/cva6_mmu/cva6_ptw.sv

#2692 changed the bus width for `pmpcfg` and `pmpaddr` in most modules. Do the same in `cva6_mmu` and `cva6_ptw` to fix port width mismatches.

mmu: Fix pmpcfg, pmpaddr width

---

.readthedocs.yaml

as riscv-isa-manual has a submodule, clone it

.readthedocs.yaml: clone submodule recursively

---

docs/riscv-isa/src/smctr.adoc

smctr.adoc is a new file in riscv-isa-manual to be overwritten

fix 8e5872c03 (add missing smctr.adoc file)

---

.readthedocs.yaml

to avoid PATH export, define it in the same command with make

fix 023e67e9 (define PATH variable and make in one command)

---

docs/riscv-isa/src/mm-formal.adoc

as this appendix requires Java and as it is not relevant for CV32A65X

riscv-isa-manual: ignore mm-formal.adoc

---

docs/requirements.txt

this should fix build of design documents

docs/requirements.txt: add missing packages for RTD

---

config/gen_from_riscv_config/cv32a65x/spike/spike.yaml

This is a spike fix for cv32a65x config

Spike : mtvec doesn't support vectored mode for cv32a65x

---

docs/riscv-isa/src/priv-csrs.adoc

as priv-csrs.adoc was not yet tailored for CVA6, the file is copied
and tailored

docs: clarify WLRL CSR fields on CVA6 (fix #1053)

---

core/include/cv64a6_imafdc_sv39_hpdcache_wb_config_pkg.sv

The AXI AW channel in the HPDcache is shared by three components:
- Write Buffer
- Flush Controller
- Uncached Controller
The ID for each transaction is generated based on its source as follows:
- Write Buffer: `{1'b0, write_buffer_entry_index}`
- Flush Controller: `{1'b1, flush_controller_index}`
- Uncached Controller: `'1`
To distinguish between flush transactions and uncached transactions, the flush transaction ID must include at least one 0.
Currently, the AXI ID is limited to 4 bits, while the flush controller supports 8 entries. As a result, when a transaction is sent from the 8th entry of the flush controller, all bits of the ID are set to 1. This causes the HPDcache to misroute the response to the uncached controller instead of the flush controller.
The parameter …

config_pkg: fix HPDCache related parameter

---

core/cva6.sv
core/cva6_rvfi.sv
core/cva6_rvfi_probes.sv
core/include/rvfi_types.svh
core/issue_read_operands.sv
core/issue_stage.sv

RVFI rs1 and rs2 operands were VLEN, it has been fixed to be XLEN.

Fix RVFI rs1/rs2 len from VLEN to XLEN

---

core/frontend/instr_scan.sv

is_rvc is redundant with riscv::OpcodeC1, riscv::OpcodeC2

instr_scan.sv: remove useless condition

---

core/decoder.sv

to improve conditional coverage

decoder.sv: add condition CVA6Cfg.SoftwareInterruptEn

---

core/cva6_rvfi_probes.sv

rs1_i and rs2_i have XLEN width

cva6_rvfi_probes.sv: fix be5ac20e4 (PR 2749)

---

core/csr_regfile.sv

Use CVA6Cfg.DebugEn in an outer test instead of in inner tests

csr_regfile.sv: move CVA6Cfg.DebugEn to improve code coverage

---

verif/sim/Makefile

This is help the verif team, to be easy to generate verdi_cov to debug function coverage

Makefile : Add target to generate functional coverage using verdi tool

---

core/cache_subsystem/cva6_icache.sv

Run verible verilog format to fix upstream formatting.
Perhaps it would be a good idea to let CI fail if verible catches mismatches to prevent them from being accidentally merged. I can look into that.

cva6_icache: Fix formatting

---

.gitlab-ci.yml
core/include/build_config_pkg.sv
core/include/config_pkg.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a65x_config_pkg.sv
core/include/cv32a6_embedded_config_pkg_deprecated.sv
core/include/cv32a6_ima_sv32_fpga_config_pkg.sv
core/include/cv32a6_imac_sv0_config_pkg.sv
core/include/cv32a6_imac_sv32_config_pkg.sv
core/include/cv32a6_imafc_sv32_config_pkg.sv
core/include/cv64a6_imadfcv_sv39_polara_config_pkg.sv
core/include/cv64a6_imafdc_sv39_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_config_pkg.sv
core/include/cv64a6_imafdc_sv39_hpdcache_wb_config_pkg.sv
core/include/cv64a6_imafdc_sv39_openpiton_config_pkg.sv
core/include/cv64a6_imafdc_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdch_sv39_config_pkg.sv
core/include/cv64a6_imafdch_sv39_wb_config_pkg.sv
core/include/cv64a6_imafdcv_sv39_config_pkg.sv
core/include/cv64a6_mmu_config_pkg.sv
corev_apu/src/ariane.sv

Add parameter `CoproType` to select which coprocessor to instantiate when `CvxifEn == 1`

Add parameter type to define which coprocessor is instantiated on CVXIF

---

Makefile

`src/bootrom/bootrom_$(XLEN).sv` does not exist relative to the Makefile and is not built by the recipe. Like all other FPGA source files, prefix the full path to `bootrom_$(XLEN).sv`.

Makefile: Fix FPGA bootrom path

---

common/local/util/instr_tracer.sv

Currently, the instruction trace update logic is triggered on both clock edges, leading to double entries in the instruction trace and a wrong cycle count. Fix this by updating the trace only on positive clock edges.
Note that this was previously done through the interface: https://github.com/openhwgroup/cva6/blob/f886713754c9916df7ae23eab2a73959b58312d2/common/local/util/instr_tracer_if.sv#L63
But since [`38e8c059b`](https://github.com/openhwgroup/cva6/commit/38e8c059b#diff-86f1f47bb1bcb5af0e128339306dbcc972c80a4e7fdca22d6d5d819949cc9d96L1558), `clk_i` is directly assigned to `pck`.

instr_tracer.sv: Fix double sampling

---

core/scoreboard.sv

- no speculative scoreboard
- no Zcmp

scoreboard.sv: improve code coverage

---

config/gen_from_riscv_config/cv32a60x/spike/spike.yaml

Disable cv32a60x pmp writeable regions

Spike.yaml : disable pmp regions in cv32a60x

---

verif/sim/Makefile

Disable tgl coverage and add options to enable condition coverage for for loop and functions and tasks

Disable toggle coverage & add condition coverage options

---

README.md
util/toolchain-builder/config/global.sh

As discussed in https://github.com/openhwgroup/cva6/issues/2775#issuecomment-2676320205 , this pr enables gdb back on the toolchain build scripts. It also updates the README to use the current toolchain name for the gdb section.

Enable gdb on toolchain builder

---

corev_apu/altera/ip/io_pll.tcl
corev_apu/altera/src/cva6_altera.sv
corev_apu/altera/src/cva6_altera_peripherals.sv
corev_apu/fpga/src/bootrom/src/uart.c

Update Altera APU design to support linux in both 32 and 64 bits
- Move JTAG UART inside peripherals to properly connect the interruput request to PLIC
- Reduce the frequency of operation to 100MHz to avoid timing issues in 64bit version
- Update UART read and write operation in bootrom to allow keyboard interrupt

Altera fpga update

---

core/frontend/frontend.sv

The last instruction cannot be a 32 bit instruction when this instruction is not word aligned (in single or dual issue mode).
This cannot be (easily) conditioned. One solution was to exclude the lines, but as it is not so user friendly, Côme proposed to rewrite the code to hide the uncovered case.

Improve Code Coverage in Frontend

---

core/cva6_mmu/cva6_ptw.sv

Fix a small latch created when `RVH` is off.

Fix latch in `PTW` when `RVH` is disabled

---

core/cva6_mmu/cva6_mmu.sv

The load and store units sample the MMU exception one cycle after `dtlb_hit` is asserted (see below). However, misaligned exceptions are currently fed through the MMU, potentially attributing a misaligned exception to the *preceding* instruction. Fix this by latching the misaligned exception.
https://github.com/openhwgroup/cva6/blob/6e0cf8d7307f8e7b1aa4d9b09d1cd5254426de0a/core/load_unit.sv#L436-L442

mmu: Latch misaligned exception to fix misattribution

---

core/csr_regfile.sv

addr_mode[1] = 1 for NATOP and NA4. As cv32a60x supports only TOR and OFF, the line can be conditioned by CVA6Cfg.PMPNapotEn

Improve CC

---

core/cva6_mmu/cva6_mmu.sv

Adds to #2798. Sorry for noticing this only now. Together with #2798, this reverts a bug that was introduced in #2528.

mmu: Use latched value to determine if misaligned exception occurred

---

verif/env/corev-dv/target/rv32imcb/riscv_core_setting.sv
verif/sim/cva6.hvp

This MR relative to disabling fence_i from UVM TB
waiting disabling fence_i in RTL cv32a60x configue

FENCE_i : Remove fence_i from HVP and core-dv

---

verif/env/uvme/uvme_cva6_cfg.sv
verif/env/uvme/uvme_cva6_cntxt.sv
verif/env/uvme/uvme_cva6_env.sv
verif/tb/uvmt/cva6_tb_wrapper.sv
verif/tb/uvmt/uvmt_cva6_tb.sv

To improve the UVM tb, I condition instantiation of obi_amo_agent in the uvm env only when amo extension is enbaled, that's gonna gain more time in simulation also disabling coverage of amo_obi_agent

TB UVM : don't instanciate obi_amo_agent without amo extension enabled

---

config/gen_from_riscv_config/cv32a60x/spike/spike.yaml

This is a fix in spike.yaml, I added a mask as the cv32a60x doesn't support vectored mode

Spike.yaml : cv32a60x doesn't support vectored mode

---

core/frontend/frontend.sv
core/perf_counters.sv
core/scoreboard.sv

When resolved_branch_i.is_mispredict is 1, resolved_branch_i.valid is 1 (see branch_unit.sv code).
Simplify code to increase code coverage

Improve Code Coverage by simplifying resolved_branch condition

---

.gitlab-ci/scripts/report_benchmark.py
config/gen_from_riscv_config/cv32a60x/spike/spike.yaml
config/gen_from_riscv_config/cv32a65x/spike/spike.yaml
config/riscv-config/cv32a60x/generated/custom_gen.yaml
config/riscv-config/cv32a60x/generated/isa_gen.yaml
config/riscv-config/cv32a60x/generated/platform_gen.yaml
config/riscv-config/cv32a60x/spec/custom_spec.yaml
config/riscv-config/cv32a60x/spec/isa_spec.yaml
config/riscv-config/cv32a60x/spec/platform_spec.yaml
config/riscv-config/cv32a65x/generated/isa_gen.yaml
config/riscv-config/cv32a65x/spec/isa_spec.yaml
core/cva6_pipeline.sv
core/cva6_rvfi.sv
core/cva6_rvfi_probes.sv
core/decoder.sv
core/id_stage.sv
core/include/cv32a60x_config_pkg.sv
core/include/cv32a65x_config_pkg.sv
core/include/cvxif_types.svh
core/include/rvfi_types.svh
verif/regress/benchmark.sh
verif/regress/coremark.sh
verif/regress/cv32a6_tests.sh
verif/regress/cv64a6_imafdc_tests.sh
verif/regress/dhrystone.sh
verif/regress/hwconfig_tests.sh
verif/regress/smoke-tests-cv32a60x.sh
verif/regress/smoke-tests-cv32a65x.sh
verif/sim/cva6.py
verif/sim/setup-env.sh

This MR implements the non-RTL part of CVA6 project changes needed for https://github.com/openhwgroup/cva6/issues/2734:
* changes to scripts
* changes to configuration files
* turn off Zifencei support in RTL _configuration_.

[CV32A6*X] Disable Zifencei across the verification infrastructure.

---

core/decoder.sv

This PR assigns 0 to tinst by default. 
Even though tinst is only used when CVA6Cfg.RVH is enabled, I chose to assign it a default value in all configurations, since the signal is defined for all configurations.
Fixes #2803

Assign a default value to tinst in decoder

---

verif/regress/cvxif_verif_regression.sh
verif/regress/smoke-gen_tests.sh
verif/regress/smoke-tests-cv32a60x.sh
verif/regress/smoke-tests-cv32a65x.sh

Use only one uvm seed (=1) for light tests, to fix timeout error due to obi delays randomization

Fix uvm seed for regression tests (light tests)

---

core/csr_regfile.sv
core/frontend/frontend.sv
core/frontend/instr_queue.sv

Improve code condition knowing that:
- ex_rvalid is always 0 in cv32a60x : MMU and PMP are not present
- PRIV_LVL_M is always 1 in cv32a60x
- commi_ack and exception can be both at 1 if and only if CVA6Cfg.SpeculativeSb is 1
- Frontend generates exception only if MMU or PMP is present

Improve Code Coverage

---

core/id_stage.sv

Add `else` case to initialize signals going into decoder.
Should fix #2819

Initialize compressed related signals in id_stage when RVC is disabled

---

core/cvxif_compressed_if_driver.sv

Remove `compressed_valid_o` from condition since it is always `1` in this case.

cvxif_compressed_if_driver.sv: Improve code coverage

---

.github/workflows/dashboard-done.yml
.gitlab-ci/scripts/github_integration.py
.gitlab-ci/scripts/merge_job_reports.py
.gitlab-ci/scripts/source_branch_finder.py

Pipeline triggered by commits coming from cv32a60x branch will be pushed to the cv32a60x dashboard.
Also adds a wait time before commenting the pr to wait for the dashboard generation.

push reports to cv32a60x pipelines when applicable

---

core/include/cv32a60x_config_pkg.sv

to build correct RISC-V ISA privilege manual

cv32a60x_config_pkg.sv: set NrPMPEntries to 0

---

core/multiplier.sv

in mult.sv, mul_valid_op (becoming mult_valid_i in multiplier.sv) is
already computed with
&& (operation_i inside {MUL, MULH, MULHU, MULHSU, MULW, CLMUL, CLMULH, CLMULR})
Therefore, this operation is useless in multiplier.sv

multiplier.sv: improve code coverage

---

core/csr_regfile.sv

by adding if (CVA6Cfg.NrPMPEntries != 0)

csr_regfile.sv: improve code coverage (NrPMPEntries)

---

config/riscv-config/cv32a60x/generated/isa_gen.yaml
config/riscv-config/cv32a60x/spec/isa_spec.yaml
config/riscv-config/cv32a65x/generated/isa_gen.yaml
config/riscv-config/cv32a65x/spec/isa_spec.yaml

Since the CV32A60X and CV32A65X do not have a PMP unit, specify all PMP registers as read-only constant zero in riscv-config 'ISA' files.

[riscv-config] Mark all PMP registers as RO const zero.

---

CODEOWNERS

I haven't reviewed anything in quite a while so I believe its best for me to depart the `CODEOWNER`s file. I'll still be watching the repo and any mentions, and of course,e we are using CVA6 heavily internally so still supporting the project!

CODEOWNERS: remove `zarubaf` from global owners

---

core/frontend/frontend.sv

OBI protocol requires that addr field is align with BE field, Fetch bus performs only full BE access, and until now provides next PC in addr field, next pc is not necessary align so in that case we are not compliant to OBI protocol.
This PR fixes by force to zero LSB of addr obi.

frontend.sv: fix obi fetch align

---

config/gen_from_riscv_config/cv32a60x/spike/spike.yaml
config/gen_from_riscv_config/cv32a65x/spike/spike.yaml

Enable silent fetch/load of zeroes when accessing unmapped memory locations in Spike:
- Bump CVV to use Spike supporting unmapped accesses when core-specific parameter `allow_unmapped_mem_access` is set to `True`.
- Add `allow_unmapped_mem_access: True` field to core-specific section of CV32A60X and CV32A65X Spike Yaml files.

Fix #1625: Allow unmapped memory accesses in Spike for cv32a60x/cv32a65x.

---

core/csr_regfile.sv

Condition on RVU because you can have RVU with M mode but not RVS without RVU

Hotfix 2885: Condition on RVU

---

core/csr_regfile.sv
core/cva6_fifo_v3.sv
core/cvxif_example/compressed_instr_decoder.sv
core/cvxif_example/instr_decoder.sv
core/frontend/instr_queue.sv
core/include/config_pkg.sv
core/include/utils_macros.svh
core/issue_read_operands.sv
core/load_unit.sv
core/scoreboard.sv
core/store_buffer.sv
verif/sim/Makefile

Fix https://github.com/openhwgroup/cva6/issues/1624
Add macros for else clauses in immediate assertions throwing either SystemVerilog warnings/errors/fatals or UVM ones when applicable.
__FILE__ and __LINE__ are not displayed in the error message because Spyglass was throwing "Undefined Macros" errors. 
VCS does print them anyway.

add macros for assertions else clauses

---

core/cva6_mmu/cva6_mmu.sv

Fix the wrong connection of ASID in MMU. Should solve https://github.com/openhwgroup/cva6/issues/2912

Fix https://github.com/openhwgroup/cva6/issues/2912

---

verif/sim/cov-exclude-mod.lst

this exclude second instantiation for fifo instr & instr scan

Code coverage : exclude second instantiation

---

docs/07_cv32a60x/index.rst

This fixes the paths for the CV32A60X-specific documentation (from the `cv32a60x` branch).  Whenever the `cv32a60x` branch is updated, the documentation will be regenerated by RTD.

Fix URLs to point to CV32A60X-specific files on RTDs.

---

core/issue_read_operands.sv

Currently, cvxif_off_instr_n is assigned to orig_instr[i], with i being 0 or 1 depending on the issue port.
This assigns the original instruction value (which will be propagated, e.g., into tval in an exception) to the last bit of the instruction on issue port 0.
This commit assigns it to the full instruction on the corresponding issue port instead.
Fixes https://github.com/openhwgroup/cva6/issues/2935.

Fix cvxif_off_instr_n in issue_read_operands

---

ci/install-prereq.sh

The CI is currently broken due to an expired GPG key for the `edatools` repository. However, it seems like there is no real need for it in the current CI.
Removing it fixes the CI. I could not observe anything breaking due to this change. However, someone more knowledgeable about the CI could double check the proposed change.

Proposed CI fix: remove edatools repository from prerequisites

---

verif/env/uvme/uvme_cva6_sb.sv

return requires a value to be returned (detected as an xcelium compilation error). Set a default value of 0.

Add missing value to return

---

core/commit_stage.sv
core/include/ariane_pkg.sv

This commit makes two changes to the commit stage:
- It fixes incorrect parenthesis, causing dirty_fp_state_o not to be set on floating point instructions such as fld.
- It adds a condition for dirty_fp_state_o that only asserts the flag for floating point instructions that change any FPU registers.
This PR fixes #2934

Indicate dirty in mstatus.FS correctly

---

core/controller.sv
core/cva6.sv
core/frontend/frontend.sv

Fix fence.i synchronization issue with HPDCache write-back Data 
- Add [halt_frontend_o] signal to stall instruction fetch during fence.i
- Introduce [fence_i_active] state to track ICache+DCache flush progress
- Gate ICache requests and NPC updates when fence.i is active 
- Resolves stale instruction fetch in self-modifying code scenarios (riscv-tests/rv32ui/fence_i) 
- Enables Linux boot with HPDCache write-back data by ensuring ICache/DCache coherency
> Note: This was not seen with [std_dcache] in standard [fence_i] tests, since it normally finishes write‑back before the ICache flush completes. However, for large self‑modifying code regions, the write‑back can lag behind the ICache flush, leading to stale instruction fetches even with [std_dcache].
**Problem:**  
When executing …

[Fix] fence.i fails to synchronize ICache/DCache flushes in write-back mode

---

core/cva6_mmu/cva6_mmu.sv

With the MMU enabled (`MmuPresent = 1`), load/store operations to unaligned addresses silently complete instead of raising the required `LOAD_ADDR_MISALIGNED` or `STORE_ADDR_MISALIGNED` exceptions. When `MmuPresent = 0`, behavior is correct and matches Spike.
The MMU’s internal register that latches LSU misalignment errors `misaligned_ex_q` was only updated when Hypervisor support was enabled (`CVA6Cfg.RVH = 1`). If Hypervisor support is disabled (`RVH = 0`), misaligned_ex_q never captures the pending misalignment exception, and translation proceeds without triggering the exception.
https://github.com/openhwgroup/cva6/blob/c39333bdacf6e2a1d544b6cf264ad160a7b03f14/core/cva6_mmu/cva6_mmu.sv#L753-L759
Unconditionally update `misaligned_ex_q` on every cycle (or reset) so that misaligned …

Misaligned Load/Store Exceptions Ignored When MMU Is Enabled (Breaks rv32mi-ma_addr & I-MISALIGN_LDST_01)

---

docs/scripts/classes.py
docs/scripts/define_blacklist.py
docs/scripts/parameters_extractor.py
docs/scripts/spec_builder.py
tutorials/fpga.md
vendor/pulp-platform/fpga-support/README.md
verif/sim/cva6.py

A couple simple changes which adds a caveat to the README about #2535 and removes some unnecessary hard coded paths which makes development easier on platforms such as Nix

README caveat and hard coded paths

---

core/compressed_decoder.sv
verif/env/corev-dv/cva6_unsupported_instr.sv

bit 6 of c.sh must be equal to 0.
If bit 6 equals 1, an illegal instruction exception shall be raised.

compressed_decoder.sv: fix c.sh (issue #3051)
